/// Generated by gleaph-codegen. Do not edit.

module {
  public let GLEAPH_GRAPH_ID : Text = "fixture-graph";

  public type PreparedResponse<Row> = { row_count : Nat64; rows : [Row] };

  /// Find users by their search term.
  public type FindUsersParams = {
    /// Text to search for.
    term : Text;
  };

  public type FindUsersRow = {
    user_name : Text;
  };

  public type FindUsersExecutor = {
    executeQuery : (Text, FindUsersParams) -> async PreparedResponse<FindUsersRow>;
  };

  public class FindUsersQueries(executor : FindUsersExecutor) {
    /// Execute the prepared operation.
    public func execute(params : FindUsersParams) : async PreparedResponse<FindUsersRow> {
      await executor.executeQuery("find-users", params);
    };
  };
};
