// Generated by gleaph-codegen. Do not edit.

import type { ApiValue, GleaphClient, GleaphTransport, GleaphTransportOptions, GqlMutationResult, GqlQueryResult, PreparedSortSpec, GqlDecimal, GqlFloat16, GqlFloat128, Temporal } from "@gleaph/sdk";
import type { Principal } from "@icp-sdk/core/principal";
import { GleaphClientWrapper, createGleaphClient, createGleaphClientFromTransport, toApiValue, fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "default" as const;

type PreparedResponse<Row> = Omit<GqlQueryResult, "rows"> & { rows: Row[] };

export type PrincipalLike = string | { toText(): string };

/**
 * Find users whose name starts with the given term.
 */
export interface FindUsersParams {
  /**
   * Name prefix to search for.
   */
  term: string;
}

export interface FindUsersRow {
  user_name: string;
  user_id: bigint;
  joined_on: Temporal.PlainDate;
  rating: GqlFloat16 | null;
}

/**
 * Read an account profile with exotic scalar types.
 */
export interface UserAccountParams {
  user_id: bigint;
}

export interface UserAccountRow {
  balance: bigint;
  amount: GqlDecimal;
  score: GqlFloat128 | null;
  joined_at: Temporal.Instant;
  zoned_at: Temporal.ZonedDateTime;
  elapsed: Temporal.Duration;
  owner: Principal;
  tags: Array<string>;
}

/**
 * Create a user. Idempotent when retried with the same client mutation key.
 */
export interface CreateUserParams {
  user_id: bigint;
  user_name: string;
  joined_on: Temporal.PlainDate;
  signup_fee?: GqlDecimal | null;
  score?: GqlFloat128 | null;
}

export interface CreateUserRow {
  user_id: bigint;
}

export interface PreparedQueries {
  findUsers(params: FindUsersParams, sort?: PreparedSortSpec[]): Promise<PreparedResponse<FindUsersRow>>;
  userAccount(params: UserAccountParams): Promise<PreparedResponse<UserAccountRow>>;
  createUser(params: CreateUserParams, clientMutationKey: string): Promise<GqlMutationResult>;
}

export class PreparedGleaphClient extends GleaphClientWrapper implements PreparedQueries {
  constructor(client: GleaphClient) {
    super(client);
  }

  /**
   * Find users whose name starts with the given term.
   */
  async findUsers(params: FindUsersParams, sort?: PreparedSortSpec[]): Promise<PreparedResponse<FindUsersRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["term"] = toApiValue(params["term"], "Text");
    const response = await this.preparedQuery("find-users", encodedParams, sort);
    return { ...response, rows: response.rows.map((row) => ({
      user_name: fromApiValue(row["user_name"]) as string,
      user_id: fromApiValue(row["user_id"]) as bigint,
      joined_on: fromApiValue(row["joined_on"]) as Temporal.PlainDate,
      rating: fromApiValue(row["rating"]) as GqlFloat16 | null,
    })) };
  }

  /**
   * Read an account profile with exotic scalar types.
   */
  async userAccount(params: UserAccountParams): Promise<PreparedResponse<UserAccountRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["user_id"] = toApiValue(params["user_id"], "Uint64");
    const response = await this.preparedQuery("user-account", encodedParams);
    return { ...response, rows: response.rows.map((row) => ({
      balance: fromApiValue(row["balance"]) as bigint,
      amount: fromApiValue(row["amount"]) as GqlDecimal,
      score: fromApiValue(row["score"]) as GqlFloat128 | null,
      joined_at: fromApiValue(row["joined_at"]) as Temporal.Instant,
      zoned_at: fromApiValue(row["zoned_at"]) as Temporal.ZonedDateTime,
      elapsed: fromApiValue(row["elapsed"]) as Temporal.Duration,
      owner: fromApiValue(row["owner"]) as Principal,
      tags: fromApiValue(row["tags"]) as Array<string>,
    })) };
  }

  /**
   * Create a user. Idempotent when retried with the same client mutation key.
   */
  async createUser(params: CreateUserParams, clientMutationKey: string): Promise<GqlMutationResult> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["user_id"] = toApiValue(params["user_id"], "Uint64");
    encodedParams["user_name"] = toApiValue(params["user_name"], "Text");
    encodedParams["joined_on"] = toApiValue(params["joined_on"], "Date");
    if (params["signup_fee"] !== undefined) encodedParams["signup_fee"] = toApiValue(params["signup_fee"], "Decimal");
    if (params["score"] !== undefined) encodedParams["score"] = toApiValue(params["score"], "Float128");
    const response = await this.preparedMutate("create-user", encodedParams, clientMutationKey);
    return response;
  }
}

export function withPreparedQueries(client: GleaphClient): PreparedGleaphClient {
  return new PreparedGleaphClient(client);
}

/** Construct a client bound to the graph's prepared operations and dynamic GQL. */
export async function createPreparedGleaphClient(options: GleaphTransportOptions): Promise<PreparedGleaphClient> {
  return withPreparedQueries(await createGleaphClient(options));
}

/** Construct a prepared client over an existing SDK transport. */
export function createPreparedGleaphClientFromTransport(transport: GleaphTransport): PreparedGleaphClient {
  return withPreparedQueries(createGleaphClientFromTransport(transport));
}
