// Generated by gleaph-codegen. Do not edit.

import type { ApiValue, GleaphClient, GqlMutationResult, GqlQueryResult, PreparedSortSpec, GqlDecimal, GqlFloat16, GqlFloat128, Temporal } from "@gleaph/sdk";
import type { Principal } from "@icp-sdk/core/principal";
import { toApiValue } from "@gleaph/sdk";
import { fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "default" as const;

type PreparedResponse<Row> = Omit<GqlQueryResult, "rows"> & { rows: Row[] };

export type PrincipalLike = string | { toText(): string };

/**
 * Find users whose name starts with the given term.
 */
export interface FindUsersParams {
  /**
   * Name prefix to search for.
   */
  term: string;
}

export interface FindUsersRow {
  user_name: string;
  user_id: bigint;
  joined_on: Temporal.PlainDate;
  rating: GqlFloat16 | null;
}

/**
 * Read an account profile with exotic scalar types.
 */
export interface UserAccountParams {
  user_id: bigint;
}

export interface UserAccountRow {
  balance: bigint;
  amount: GqlDecimal;
  score: GqlFloat128 | null;
  joined_at: Temporal.Instant;
  zoned_at: Temporal.ZonedDateTime;
  elapsed: Temporal.Duration;
  owner: Principal;
  tags: Array<string>;
}

/**
 * Create a user. Idempotent when retried with the same client mutation key.
 */
export interface CreateUserParams {
  user_id: bigint;
  user_name: string;
  joined_on: Temporal.PlainDate;
  signup_fee?: GqlDecimal | null;
  score?: GqlFloat128 | null;
}

export interface CreateUserRow {
  user_id: bigint;
}

export interface PreparedQueries {
  /**
   * Find users whose name starts with the given term.
   */
  "find-users": (params: FindUsersParams, sort?: PreparedSortSpec[]) => Promise<PreparedResponse<FindUsersRow>>;
  /**
   * Read an account profile with exotic scalar types.
   */
  "user-account": (params: UserAccountParams) => Promise<PreparedResponse<UserAccountRow>>;
  /**
   * Create a user. Idempotent when retried with the same client mutation key.
   */
  "create-user": (params: CreateUserParams, clientMutationKey: string) => Promise<GqlMutationResult>;
}

export function withPreparedQueries(client: GleaphClient): PreparedQueries {
  return {
    "find-users": async (params, sort?: PreparedSortSpec[]) => {
      const encodedParams: Record<string, ApiValue> = {};
      encodedParams["term"] = toApiValue(params["term"], "Text");
      const response = await client.executePrepared("find-users", encodedParams, sort);
      return { ...response, rows: response.rows.map((row) => ({
        user_name: fromApiValue(row["user_name"]) as string,
        user_id: fromApiValue(row["user_id"]) as bigint,
        joined_on: fromApiValue(row["joined_on"]) as Temporal.PlainDate,
        rating: fromApiValue(row["rating"]) as GqlFloat16 | null,
      })) };
    },
    "user-account": async (params) => {
      const encodedParams: Record<string, ApiValue> = {};
      encodedParams["user_id"] = toApiValue(params["user_id"], "Uint64");
      const response = await client.executePrepared("user-account", encodedParams);
      return { ...response, rows: response.rows.map((row) => ({
        balance: fromApiValue(row["balance"]) as bigint,
        amount: fromApiValue(row["amount"]) as GqlDecimal,
        score: fromApiValue(row["score"]) as GqlFloat128 | null,
        joined_at: fromApiValue(row["joined_at"]) as Temporal.Instant,
        zoned_at: fromApiValue(row["zoned_at"]) as Temporal.ZonedDateTime,
        elapsed: fromApiValue(row["elapsed"]) as Temporal.Duration,
        owner: fromApiValue(row["owner"]) as Principal,
        tags: fromApiValue(row["tags"]) as Array<string>,
      })) };
    },
    "create-user": async (params, clientMutationKey) => {
      const encodedParams: Record<string, ApiValue> = {};
      encodedParams["user_id"] = toApiValue(params["user_id"], "Uint64");
      encodedParams["user_name"] = toApiValue(params["user_name"], "Text");
      encodedParams["joined_on"] = toApiValue(params["joined_on"], "Date");
      if (params["signup_fee"] !== undefined) encodedParams["signup_fee"] = toApiValue(params["signup_fee"], "Decimal");
      if (params["score"] !== undefined) encodedParams["score"] = toApiValue(params["score"], "Float128");
      const response = await client.executePreparedMutation("create-user", encodedParams, clientMutationKey);
      return response;
    },
  };
}
