//! Generated by gleaph-codegen. Do not edit.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use gleaph_sdk::GqlParams;
use gleaph_sdk::GqlValue;
use std::future::Future;

pub const GLEAPH_GRAPH_ID: &str = "fixture-graph";

/// Result returned by a prepared operation.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedResponse<Row> {
    /// Number of rows returned by the Router.
    pub row_count: u64,
    /// Typed rows decoded from the Router response.
    pub rows: Vec<Row>,
}

/// Find users by their search term.
/// Parameters for the prepared operation find-users.
#[derive(Clone, Debug)]
pub struct FindUsersParams {
    /// Text to search for.
    /// Wire parameter term.
    pub term: String,
}

impl FindUsersParams {
    /// Convert typed parameters to ordered logical GQL parameters.
    pub fn into_gql_params(self) -> Result<GqlParams, gleaph_sdk::CallError> {
        Ok(vec![("term".to_string(), GqlValue::Text(self.term))])
    }
}

/// One result row from the prepared operation find-users.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FindUsersRow {
    /// Wire column user_name.
    #[serde(rename = "user_name")]
    pub user_name: String,
}

/// Declared result columns of the prepared operation find-users.
pub const FIND_USERS_COLUMNS: &[gleaph_sdk::rows::Column] = &[
    gleaph_sdk::rows::Column { name: "user_name".to_owned(), semantic_type: gleaph_sdk::rows::SemanticType::Text, nullable: false, },
]

/// Marker enabling generated prepared operations on `gleaph_sdk::GleaphClient<Prepared>`.
pub struct Prepared;

/// Prepared operations generated from the manifest, available on
/// `gleaph_sdk::GleaphClient<Prepared>`.
///
/// Import this trait to call prepared operations on a client created with
/// `gleaph_sdk::GleaphClient::with_prepared::<Prepared>`.
pub trait PreparedExt {
    /// Execute the prepared operation find-users.
    fn find_users(
        &self,
        params: FindUsersParams,
    ) -> impl Future<Output = Result<PreparedResponse<FindUsersRow>, gleaph_sdk::CallError>> + Send;
}

impl PreparedExt for gleaph_sdk::GleaphClient<Prepared> {
    async fn find_users(
        &self,
        params: FindUsersParams,
    ) -> Result<PreparedResponse<FindUsersRow>, gleaph_sdk::CallError> {
        let params = params.into_gql_params()?;
        let params = gleaph_sdk::encode_gql_params(params).map_err(|error| {
            gleaph_sdk::CallError::Decode {
                message: format!("failed to encode GQL params: {error:?}"),
            }
        })?;
        let result = self
            .prepared_query("find-users", params, None, gleaph_sdk::ReadMode::Eventual)
            .await?;
        gleaph_sdk::rows::validate_result_rows(&result, FIND_USERS_COLUMNS)?;
        Ok(PreparedResponse {
            row_count: result.row_count,
            rows: result
                .decode_serde_rows::<FindUsersRow>()?
                .unwrap_or_default(),
        })
    }
}
