use gleaph_graph::PreparedQueryInfo;

use super::{
    JsParamStyle, doc_parts, format_gql_doc, has_dynamic_sort, optional_param_bindings,
    param_bindings, params_type_name, render_rs_union_enums, render_rust_wire_module,
    required_param_bindings, rs_param_type_ctx, rust_params_to_btree_map_expr, sanitize_ident,
    sort_spec_type_name,
};

/// Generate a self-contained `.rs` client: `serde_json::Value` params (Gleaph `ApiValue` JSON), optional `candid` for Principal.
pub fn generate_rs(stmts: &[PreparedQueryInfo], source_label: &str) -> String {
    let need_principal = super::needs_principal_import(stmts);
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by gleaph-codegen — DO NOT EDIT\n");
    out.push_str(&format!("// Source: {source_label}\n\n"));
    out.push_str("#![allow(unused, clippy::all)]\n\n");
    out.push_str("// Cargo: `serde_json`");
    if need_principal {
        out.push_str(" and `candid` (`Principal`; same type as in typical IC / `gleaph` stacks)");
    }
    out.push_str(". No `gleaph` / `gleaph-gql` in generated code.\n\n");
    out.push_str("use std::collections::BTreeMap;\n");
    out.push_str("use serde_json::Value;\n");
    if need_principal {
        out.push_str("use candid::Principal;\n");
    }
    out.push('\n');
    out.push_str(&render_rust_wire_module(need_principal));
    out.push_str(&render_rs_union_enums(stmts));
    out.push_str(&render_rs_sort_spec_structs(stmts));
    out.push_str(&render_rs_types(stmts));

    out.push_str(
        "/// Implement for your HTTP / canister client (deserialize `Value` as your API documents).\n\
         pub trait GleaphPreparedGraphOps: Send + Sync {\n\
         async fn gleaph_execute_prepared_query(\n\
         &self,\n\
         name: &str,\n\
         params: BTreeMap<String, Value>,\n\
         sort: Option<Value>,\n\
         ) -> Result<Value, String>;\n\n\
         async fn gleaph_execute_prepared_update(\n\
         &self,\n\
         name: &str,\n\
         params: BTreeMap<String, Value>,\n\
         ) -> Result<Value, String>;\n\
         }\n\n",
    );

    out.push_str("/// Type-safe wrapper for prepared statements.\n");
    out.push_str("pub struct PreparedClient<'a, C: GleaphPreparedGraphOps> {\n");
    out.push_str("    graph: &'a C,\n");
    out.push_str("}\n\n");

    out.push_str("impl<'a, C: GleaphPreparedGraphOps> PreparedClient<'a, C> {\n");
    out.push_str("    pub fn new(graph: &'a C) -> Self {\n");
    out.push_str("        Self { graph }\n");
    out.push_str("    }\n");

    for info in stmts {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        out.push('\n');
        out.push_str(&format_gql_doc(&info.source, "    ///"));
        for part in doc_parts(info) {
            out.push_str(&format!("    /// {part}\n"));
        }

        use gleaph_graph::PreparedQueryKind;
        let method = match info.kind {
            PreparedQueryKind::Query => "gleaph_execute_prepared_query",
            PreparedQueryKind::Update => "gleaph_execute_prepared_update",
        };

        let sort_on = has_dynamic_sort(info);

        match info.kind {
            PreparedQueryKind::Update => {
                if info.parameters.is_empty() {
                    out.push_str(&format!(
                        "    pub async fn {ident}(&self) -> Result<Value, String> {{\n"
                    ));
                    out.push_str(&format!(
                        "        self.graph.{method}(\"{}\", std::collections::BTreeMap::new()).await\n",
                        info.name
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub async fn {ident}(&self, params: {}) -> Result<Value, String> {{\n",
                        params_type_name(&ident)
                    ));
                    let map_expr = rust_params_to_btree_map_expr(info, &ident);
                    out.push_str(&format!(
                        "        self.graph.{method}(\"{}\", {map_expr}).await\n",
                        info.name
                    ));
                }
                out.push_str("    }\n");
            }
            PreparedQueryKind::Query => {
                let spec_t = sort_spec_type_name(&ident);
                let mut sig = Vec::new();
                if info.parameters.is_empty() {
                } else {
                    sig.push(format!("params: {}", params_type_name(&ident)));
                }
                if sort_on {
                    sig.push(format!("sort: Option<Vec<{spec_t}>>"));
                }
                let args = sig.join(", ");
                let head = if args.is_empty() {
                    format!("    pub async fn {ident}(&self)")
                } else {
                    format!("    pub async fn {ident}(&self, {args})")
                };
                out.push_str(&format!("{head} -> Result<Value, String> {{\n"));
                let map_expr = if info.parameters.is_empty() {
                    "std::collections::BTreeMap::new()".to_string()
                } else {
                    rust_params_to_btree_map_expr(info, &ident)
                };
                if sort_on {
                    out.push_str(&format!(
                        "        let sort_json = sort.and_then(|s| serde_json::to_value(s).ok());\n\
                         self.graph.{method}(\"{}\", {map_expr}, sort_json).await\n",
                        info.name
                    ));
                } else {
                    out.push_str(&format!(
                        "        self.graph.{method}(\"{}\", {map_expr}, None).await\n",
                        info.name
                    ));
                }
                out.push_str("    }\n");
            }
        }
    }

    out.push_str("}\n");
    out
}

fn render_rs_sort_spec_structs(stmts: &[PreparedQueryInfo]) -> String {
    let mut out = String::new();
    for info in stmts {
        if !has_dynamic_sort(info) {
            continue;
        }
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };
        let spec = sort_spec_type_name(&ident);
        out.push_str("#[derive(serde::Serialize)]\n");
        out.push_str(&format!("pub struct {spec} {{\n"));
        out.push_str("    pub key: String,\n");
        out.push_str("    pub descending: bool,\n");
        out.push_str(
            "    #[serde(skip_serializing_if = \"Option::is_none\")]\n    pub nulls_first: Option<bool>,\n}\n\n",
        );
    }
    out
}

fn render_rs_types(stmts: &[PreparedQueryInfo]) -> String {
    let mut out = String::new();

    for info in stmts {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        let params = param_bindings(info, JsParamStyle::Preserve);
        if params.is_empty() {
            continue;
        }

        let param_type_map: std::collections::HashMap<&str, Option<String>> = info
            .parameters
            .iter()
            .map(|p| (p.name.as_str(), rs_param_type_ctx(p, Some(&ident))))
            .collect();

        let params_type = params_type_name(&ident);
        let builder_type = format!("{params_type}Builder");
        let required = required_param_bindings(info, JsParamStyle::Preserve);
        let optional = optional_param_bindings(info, JsParamStyle::Preserve);
        out.push_str(&format!("/// Parameters for `{}`.\n", info.name));
        out.push_str(&format!("pub struct {params_type} {{\n"));

        for binding in &required {
            let field_type = param_type_map
                .get(binding.wire_name.as_str())
                .and_then(|t| t.as_deref())
                .unwrap_or("serde_json::Value");
            out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
            out.push_str(&format!("    pub {}: {field_type},\n", binding.api_name));
        }
        for binding in &optional {
            let inner_type = param_type_map
                .get(binding.wire_name.as_str())
                .and_then(|t| t.as_deref());
            match inner_type {
                Some(t) if t.starts_with("Option<") => {
                    out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
                    out.push_str(&format!("    pub {}: {t},\n", binding.api_name));
                }
                Some(t) => {
                    out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
                    out.push_str(&format!("    pub {}: Option<{t}>,\n", binding.api_name));
                }
                None => {
                    out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
                    out.push_str(&format!(
                        "    pub {}: Option<serde_json::Value>,\n",
                        binding.api_name
                    ));
                }
            }
        }
        out.push_str("}\n\n");

        let constructor_args: Vec<String> = required
            .iter()
            .map(|binding| {
                let ty = param_type_map
                    .get(binding.wire_name.as_str())
                    .and_then(|t| t.as_deref())
                    .unwrap_or("serde_json::Value");
                format!("{}: {ty}", binding.api_name)
            })
            .collect();

        out.push_str(&format!("impl {params_type} {{\n"));
        if !required.is_empty() {
            out.push_str(&format!(
                "    pub fn new({}) -> Self {{\n",
                constructor_args.join(", ")
            ));
            let mut fields: Vec<String> = required
                .iter()
                .map(|binding| binding.api_name.clone())
                .collect();
            fields.extend(
                optional
                    .iter()
                    .map(|binding| format!("{}: None", binding.api_name)),
            );
            out.push_str(&format!("        Self {{ {} }}\n", fields.join(", ")));
            out.push_str("    }\n");
            if !optional.is_empty() {
                out.push_str(&format!(
                    "    pub fn builder({}) -> {builder_type} {{\n",
                    constructor_args.join(", ")
                ));
                out.push_str(&format!(
                    "        {builder_type} {{ params: Self::new({}) }}\n",
                    required
                        .iter()
                        .map(|binding| binding.api_name.clone())
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
                out.push_str("    }\n");
            }
        } else {
            out.push_str("    pub fn new() -> Self {\n");
            out.push_str(&format!(
                "        Self {{ {} }}\n",
                optional
                    .iter()
                    .map(|binding| format!("{}: None", binding.api_name))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            out.push_str("    }\n");
            out.push_str(&format!("    pub fn builder() -> {builder_type} {{\n"));
            out.push_str(&format!(
                "        {builder_type} {{ params: Self::new() }}\n"
            ));
            out.push_str("    }\n");
        }
        out.push_str("}\n\n");

        if !optional.is_empty() {
            out.push_str(&format!("pub struct {builder_type} {{\n"));
            out.push_str(&format!("    params: {params_type},\n"));
            out.push_str("}\n\n");
            out.push_str(&format!("impl {builder_type} {{\n"));
            for binding in &optional {
                let inner_type = param_type_map
                    .get(binding.wire_name.as_str())
                    .and_then(|t| t.as_deref());
                let setter_type = match inner_type {
                    Some(t) if t.starts_with("Option<") => &t[7..t.len() - 1],
                    Some(t) => t,
                    None => "serde_json::Value",
                };
                out.push_str(&format!(
                    "    pub fn {}(mut self, value: {setter_type}) -> Self {{\n",
                    binding.api_name
                ));
                out.push_str(&format!(
                    "        self.params.{} = Some(value);\n",
                    binding.api_name
                ));
                out.push_str("        self\n");
                out.push_str("    }\n");
            }
            out.push_str(&format!("    pub fn build(self) -> {params_type} {{\n"));
            out.push_str("        self.params\n");
            out.push_str("    }\n");
            out.push_str("}\n\n");
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use gleaph_graph::PreparedParameterInfo;
    use gleaph_graph::PreparedQueryKind;

    use super::*;

    fn make_info(
        name: &str,
        kind: PreparedQueryKind,
        parameters: Vec<PreparedParameterInfo>,
        columns: &[&str],
        requires_caller: bool,
        source: &str,
    ) -> PreparedQueryInfo {
        let has_dml = matches!(kind, PreparedQueryKind::Update);
        PreparedQueryInfo {
            name: name.into(),
            kind,
            requires_caller,
            extension_types: vec![],
            source: source.into(),
            description: None,
            columns: columns
                .iter()
                .map(|s| gleaph_graph::PreparedColumnInfo {
                    name: (*s).to_string(),
                    expr: String::new(),
                    aliased: false,
                })
                .collect(),
            parameters,
            allowed_sorts: vec![],
            default_sort: None,
            type_warnings: vec![],
            explain: String::new(),
            summary: gleaph_graph::ApiPlanSummary {
                estimated_rows: None,
                estimated_cost: None,
                has_dml,
                dml_error_count: 0,
                dml_warning_count: 0,
                type_warning_count: 0,
            },
            use_graph_pushdown: vec![],
        }
    }

    fn with_sort(mut info: PreparedQueryInfo, key: &str, expr: &str) -> PreparedQueryInfo {
        use gleaph_graph::PreparedSortKey;
        info.allowed_sorts = vec![PreparedSortKey {
            key: key.into(),
            expr: expr.into(),
        }];
        info
    }

    #[test]
    fn rs_query_params_and_sort_stubs_absent() {
        let stmts = vec![make_info(
            "get_user",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "name".into(),
                required: true,
                nullable: false,
                inferred: false,
                type_hints: vec![],
            }],
            &["name"],
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name",
        )];
        let rs = generate_rs(&stmts, "t");
        assert!(rs.contains("pub struct GetUserParams"));
        assert!(rs.contains("pub name: serde_json::Value"));
        assert!(rs.contains("gleaph_execute_prepared_query"));
        assert!(rs.contains("sort: Option<Value>"));
        assert!(rs.contains("mod gleaph_prepared_wire"));
        assert!(!rs.contains("GetUserSortSpec"));
        assert!(!rs.contains("async_trait"));
        assert!(!rs.contains("gleaph_gql"));
        assert!(!rs.contains("gleaph_graph::"));
    }

    #[test]
    fn rs_query_includes_sort_spec_when_metadata_has_sorts() {
        let base = make_info(
            "get_user",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "name".into(),
                required: true,
                nullable: false,
                inferred: false,
                type_hints: vec![],
            }],
            &["name"],
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name",
        );
        let stmts = vec![with_sort(base, "age", "u.age")];
        let rs = generate_rs(&stmts, "t");
        assert!(rs.contains("pub struct GetUserSortSpec"));
        assert!(rs.contains("sort: Option<Vec<GetUserSortSpec>>",));
        assert!(rs.contains("sort_json"));
    }

    #[test]
    fn rs_mutation_empty_params() {
        let stmts = vec![make_info(
            "clear",
            PreparedQueryKind::Update,
            vec![],
            &[],
            false,
            "DELETE (:Temp)",
        )];
        let rs = generate_rs(&stmts, "t");
        assert!(rs.contains("gleaph_execute_prepared_update"));
        assert!(rs.contains("BTreeMap::new()"));
    }

    #[test]
    fn rs_typed_params() {
        let stmts = vec![make_info(
            "find_users",
            PreparedQueryKind::Query,
            vec![
                PreparedParameterInfo {
                    name: "min_age".into(),
                    required: true,
                    nullable: false,
                    inferred: true,
                    type_hints: vec!["Int64".into()],
                },
                PreparedParameterInfo {
                    name: "name".into(),
                    required: true,
                    nullable: false,
                    inferred: true,
                    type_hints: vec!["Text".into()],
                },
                PreparedParameterInfo {
                    name: "active".into(),
                    required: false,
                    nullable: false,
                    inferred: true,
                    type_hints: vec!["Bool".into()],
                },
            ],
            &["name"],
            false,
            "RETURN 1",
        )];
        let rs = generate_rs(&stmts, "t");
        assert!(rs.contains("pub min_age: i64"));
        assert!(rs.contains("pub name: String"));
        assert!(rs.contains("pub active: Option<bool>"));
        assert!(rs.contains("gleaph_prepared_wire::int64(params.min_age)"));
    }

    #[test]
    fn rs_union_enum() {
        let stmts = vec![make_info(
            "search",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "key".into(),
                required: true,
                nullable: false,
                inferred: true,
                type_hints: vec!["Int64".into(), "Text".into()],
            }],
            &["r"],
            false,
            "RETURN 1",
        )];
        let rs = generate_rs(&stmts, "t");
        assert!(rs.contains("pub enum SearchParamKey"));
        assert!(rs.contains("pub key: SearchParamKey"));
        assert!(rs.contains("impl From<SearchParamKey> for serde_json::Value"));
    }

    #[test]
    fn rs_requires_caller_doc() {
        let stmts = vec![make_info(
            "my_posts",
            PreparedQueryKind::Query,
            vec![],
            &["title"],
            true,
            "RETURN 1",
        )];
        let rs = generate_rs(&stmts, "t");
        assert!(rs.contains("Uses caller()"));
    }

    #[test]
    fn rs_principal_uses_candid_and_wire() {
        let stmts = vec![make_info(
            "by_owner",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "owner".into(),
                required: true,
                nullable: false,
                inferred: true,
                type_hints: vec!["ic.Principal".into()],
            }],
            &["x"],
            false,
            "RETURN 1",
        )];
        let rs = generate_rs(&stmts, "t");
        assert!(rs.contains("use candid::Principal"));
        assert!(rs.contains("gleaph_prepared_wire::principal(&params.owner)"));
        assert!(!rs.contains("gleaph_gql"));
        assert!(!rs.contains("gleaph_graph::"));
    }
}
