//! TypeScript / JavaScript (`+ .d.ts`) prepared client generation.
//! Runtime `.js` is derived from the same factory emission as `.ts` (no duplicated call semantics).

use gleaph_graph::PreparedQueryInfo;

use super::{
    JsParamStyle, doc_parts, format_gql_doc, needs_prepared_sort_import, needs_principal_import,
    render_ts_param_aliases, render_ts_sort_aliases, sanitize_ident, ts_factory_method_signature,
    ts_interface_method_signature,
};

fn autogen_header(source_label: &str) -> String {
    let mut s = String::new();
    s.push_str("// AUTO-GENERATED by gleaph-codegen — DO NOT EDIT\n");
    s.push_str(&format!("// Source: {source_label}\n\n"));
    s
}

/// Shared prologue: execute-result type alias + `import type` + param interfaces (TS / `.d.ts` use this).
fn emit_ts_shared_imports_and_param_types(
    stmts: &[PreparedQueryInfo],
    style: JsParamStyle,
) -> String {
    let mut out = String::new();
    out.push_str(
        "/**\n * Runtime shape should match `gleaph_graph::QueryResponse` / your HTTP prepared-execute DTO.\n */\n",
    );
    out.push_str("export type GleaphPreparedExecuteResult = unknown;\n\n");
    out.push_str("import type { GraphClient } from \"@gleaph/sdk\";\n");
    if needs_prepared_sort_import(stmts) {
        out.push_str("import type { PreparedSortSpec } from \"@gleaph/sdk\";\n");
    }
    if needs_principal_import(stmts) {
        out.push_str("import { Principal } from \"@icp-sdk/core/principal\";\n");
    }
    out.push('\n');
    out.push_str(&render_ts_param_aliases(stmts, style));
    out.push_str(&render_ts_sort_aliases(stmts));
    out
}

fn valid_stmt_idents(stmts: &[PreparedQueryInfo]) -> Vec<(&PreparedQueryInfo, String)> {
    stmts
        .iter()
        .filter_map(|info| sanitize_ident(&info.name).map(|id| (info, id)))
        .collect()
}

/// `GleaphPrepared` interface body (method signatures only).
fn emit_gleaph_prepared_interface(stmts: &[PreparedQueryInfo], style: JsParamStyle) -> String {
    let mut out = String::from("export interface GleaphPrepared {\n");
    for info in stmts {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };
        out.push_str("  /**\n");
        out.push_str(&format_gql_doc(&info.source, "   *"));
        for part in doc_parts(info) {
            out.push_str(&format!("   * {part}\n"));
        }
        out.push_str("   */\n");
        out.push_str(&ts_interface_method_signature(info, &ident, style));
    }
    out.push_str("}\n");
    out
}

#[derive(Clone, Copy)]
enum ObjectLiteralDocs {
    /// Implementation object in `.ts` (no extra per-method docs; interface already documents).
    None,
    /// `.js` runtime: `//` lines before each method.
    JsSlashSlash,
}

fn emit_prepared_client_object_literal(
    stmts: &[PreparedQueryInfo],
    style: JsParamStyle,
    docs: ObjectLiteralDocs,
) -> String {
    let mut out = String::new();
    let pairs = valid_stmt_idents(stmts);
    for (i, (info, ident)) in pairs.iter().enumerate() {
        match docs {
            ObjectLiteralDocs::None => {}
            ObjectLiteralDocs::JsSlashSlash => {
                out.push_str(&format_gql_doc(&info.source, "    //"));
                for part in doc_parts(info) {
                    out.push_str(&format!("    // {part}\n"));
                }
            }
        }
        out.push_str(&ts_factory_method_signature(info, ident, style));
        if i + 1 < pairs.len() {
            out.push_str(",\n\n");
        } else {
            out.push('\n');
        }
    }
    out
}

/// Single `.ts` file (types + implementation).
pub fn generate_ts(
    stmts: &[PreparedQueryInfo],
    source_label: &str,
    param_style: JsParamStyle,
) -> String {
    let mut out = autogen_header(source_label);
    out.push_str(&emit_ts_shared_imports_and_param_types(stmts, param_style));
    out.push_str(&emit_gleaph_prepared_interface(stmts, param_style));
    out.push_str("\n\n");
    out.push_str("export function createPreparedClient(graph: GraphClient): GleaphPrepared {\n");
    out.push_str("  return {\n");
    out.push_str(&emit_prepared_client_object_literal(
        stmts,
        param_style,
        ObjectLiteralDocs::None,
    ));
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

/// `.d.ts` companion: same types as `generate_ts` but `declare function` (no JS runtime).
pub fn generate_dts(
    stmts: &[PreparedQueryInfo],
    source_label: &str,
    param_style: JsParamStyle,
) -> String {
    let mut out = autogen_header(source_label);
    out.push_str(&emit_ts_shared_imports_and_param_types(stmts, param_style));
    out.push_str(&emit_gleaph_prepared_interface(stmts, param_style));
    out.push_str(
        "\n\nexport declare function createPreparedClient(graph: GraphClient): GleaphPrepared;\n",
    );
    out
}

/// `.js` runtime only. Types live in [`generate_dts`] (kept in sync via shared TS emission).
pub fn generate_js(
    stmts: &[PreparedQueryInfo],
    source_label: &str,
    param_style: JsParamStyle,
) -> String {
    let mut out = autogen_header(source_label);
    out.push_str("/** @param {import(\"@gleaph/sdk\").GraphClient} graph */\n");
    out.push_str("export function createPreparedClient(graph) {\n");
    out.push_str("  return {\n");
    out.push_str(&emit_prepared_client_object_literal(
        stmts,
        param_style,
        ObjectLiteralDocs::JsSlashSlash,
    ));
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use gleaph_graph::PreparedParameterInfo;
    use gleaph_graph::PreparedQueryKind;
    use gleaph_graph::PreparedSortKey;

    use super::super::{JsParamStyle, params_type_name, sort_key_type_name, sort_spec_type_name};
    use super::*;

    fn make_info(
        name: &str,
        kind: PreparedQueryKind,
        parameters: Vec<PreparedParameterInfo>,
        columns: &[&str],
        requires_caller: bool,
        source: &str,
    ) -> PreparedQueryInfo {
        let has_dml = matches!(kind, PreparedQueryKind::Update);
        PreparedQueryInfo {
            name: name.into(),
            kind,
            requires_caller,
            extension_types: vec![],
            source: source.into(),
            description: None,
            columns: columns
                .iter()
                .map(|s| gleaph_graph::PreparedColumnInfo {
                    name: (*s).to_string(),
                    expr: String::new(),
                    aliased: false,
                })
                .collect(),
            parameters,
            allowed_sorts: vec![],
            default_sort: None,
            type_warnings: vec![],
            explain: String::new(),
            summary: gleaph_graph::ApiPlanSummary {
                estimated_rows: None,
                estimated_cost: None,
                has_dml,
                dml_error_count: 0,
                dml_warning_count: 0,
                type_warning_count: 0,
            },
            use_graph_pushdown: vec![],
        }
    }

    fn with_sorts(mut info: PreparedQueryInfo, allowed: &[(&str, &str)]) -> PreparedQueryInfo {
        info.allowed_sorts = allowed
            .iter()
            .map(|(k, e)| PreparedSortKey {
                key: (*k).into(),
                expr: (*e).into(),
            })
            .collect();
        info.default_sort = None;
        info
    }

    #[test]
    fn ts_query_with_params_no_sort_in_metadata() {
        let stmts = vec![make_info(
            "find_user",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "name".into(),
                required: true,
                nullable: false,
                inferred: false,
                type_hints: vec![],
            }],
            &["name", "age"],
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name, u.age AS age",
        )];
        let ts = generate_ts(&stmts, "test", JsParamStyle::Camel);
        assert!(ts.contains("export interface FindUserParams"));
        assert!(
            ts.contains("find_user(params: FindUserParams): Promise<GleaphPreparedExecuteResult>")
        );
        assert!(ts.contains("graph.executePrepared(\"find_user\", params)"));
        assert!(!ts.contains("options?.sort"));
    }

    #[test]
    fn ts_query_with_dynamic_sort_emits_options_and_sort_types() {
        let base = make_info(
            "find_user",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "name".into(),
                required: true,
                nullable: false,
                inferred: false,
                type_hints: vec![],
            }],
            &["name", "age"],
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name, u.age AS age",
        );
        let stmts = vec![with_sorts(base, &[("name", "u.name")])];
        let ts = generate_ts(&stmts, "test", JsParamStyle::Camel);
        assert!(ts.contains("import type { PreparedSortSpec }"));
        assert!(ts.contains(&format!(
            "export const {} =",
            sort_key_type_name("find_user")
        )));
        assert!(ts.contains(
            "find_user(params: FindUserParams, options?: { sort?: FindUserSortSpec[] })"
        ));
        assert!(ts.contains("options?.sort"));
        assert_eq!(sort_spec_type_name("find_user"), "FindUserSortSpec");
    }

    #[test]
    fn ts_mutation_no_params() {
        let stmts = vec![make_info(
            "clear",
            PreparedQueryKind::Update,
            vec![],
            &[],
            false,
            "DELETE (:Temp)",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("clear(): Promise<GleaphPreparedExecuteResult>"));
        assert!(ts.contains("clear: () =>\n      graph.executePreparedMutation(\"clear\", {})"));
    }

    #[test]
    fn ts_preserve_param_style() {
        let stmts = vec![make_info(
            "find_user",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "user_name".into(),
                required: true,
                nullable: false,
                inferred: false,
                type_hints: vec![],
            }],
            &["name"],
            false,
            "MATCH (u:User) WHERE u.name = $user_name RETURN u.name AS name",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Preserve);
        assert!(ts.contains("user_name: unknown"));
        assert!(ts.contains("graph.executePrepared(\"find_user\", params)"));
    }

    #[test]
    fn ts_optional_params() {
        let stmts = vec![make_info(
            "search",
            PreparedQueryKind::Query,
            vec![
                PreparedParameterInfo {
                    name: "query".into(),
                    required: true,
                    nullable: false,
                    inferred: false,
                    type_hints: vec![],
                },
                PreparedParameterInfo {
                    name: "offset".into(),
                    required: false,
                    nullable: false,
                    inferred: false,
                    type_hints: vec![],
                },
            ],
            &["name"],
            false,
            "MATCH (u:User) RETURN u.name AS name",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("offset?: unknown"));
        assert!(ts.contains("params.offset !== undefined"));
    }

    #[test]
    fn ts_hints_native_types() {
        let stmts = vec![make_info(
            "search",
            PreparedQueryKind::Query,
            vec![
                PreparedParameterInfo {
                    name: "min_age".into(),
                    required: true,
                    nullable: false,
                    inferred: true,
                    type_hints: vec!["Int64".into()],
                },
                PreparedParameterInfo {
                    name: "name".into(),
                    required: true,
                    nullable: false,
                    inferred: true,
                    type_hints: vec!["Text".into()],
                },
                PreparedParameterInfo {
                    name: "active".into(),
                    required: false,
                    nullable: false,
                    inferred: true,
                    type_hints: vec!["Bool".into()],
                },
            ],
            &["name"],
            false,
            "RETURN 1",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("minAge: bigint"));
        assert!(ts.contains("name: string"));
        assert!(ts.contains("active?: boolean"));
    }

    #[test]
    fn ts_principal_hint() {
        let stmts = vec![make_info(
            "by_owner",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "owner".into(),
                required: true,
                nullable: false,
                inferred: true,
                type_hints: vec!["ic.Principal".into()],
            }],
            &["x"],
            false,
            "RETURN 1",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("import { Principal }"));
        assert!(ts.contains("owner: Principal"));
    }

    #[test]
    fn ts_union_hints() {
        let stmts = vec![make_info(
            "find",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "key".into(),
                required: true,
                nullable: false,
                inferred: true,
                type_hints: vec!["Int64".into(), "Text".into()],
            }],
            &["result"],
            false,
            "RETURN 1",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("key: bigint | string"));
    }

    #[test]
    fn js_matches_ts_call_semantics() {
        let stmts = vec![make_info(
            "find_user",
            PreparedQueryKind::Query,
            vec![PreparedParameterInfo {
                name: "name".into(),
                required: true,
                nullable: false,
                inferred: false,
                type_hints: vec![],
            }],
            &["name"],
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name",
        )];
        let ts = generate_ts(&stmts, "t", JsParamStyle::Camel);
        let js = generate_js(&stmts, "t", JsParamStyle::Camel);
        assert!(js.contains("export function createPreparedClient(graph)"));
        assert!(js.contains("graph.executePrepared(\"find_user\", params)"));
        assert!(ts.contains("graph.executePrepared(\"find_user\", params)"));
        assert!(js.contains("// MATCH (u:User)"));
    }

    #[test]
    fn dts_declare_and_aligns_with_ts_interface() {
        let stmts = vec![make_info(
            "clear",
            PreparedQueryKind::Update,
            vec![],
            &[],
            false,
            "DELETE (:Temp)",
        )];
        let dts = generate_dts(&stmts, "t", JsParamStyle::Camel);
        assert!(dts.contains("export declare function createPreparedClient"));
        assert!(dts.contains("export interface GleaphPrepared"));
        assert!(!dts.contains("executePreparedMutation(\"clear\", {})"));
        assert!(dts.contains("clear(): Promise<GleaphPreparedExecuteResult>"));
    }

    #[test]
    fn params_type_name_unchanged() {
        assert_eq!(params_type_name("find_user"), "FindUserParams");
    }
}
