//! JavaScript output profile for prepared-query adapters.
//!
//! Generated code delegates transport and common error handling to the JavaScript SDK and owns
//! only profile-specific runtime wrappers and value projection.

use crate::common::{append_jsdoc, encode_expression, json_string, ts_property};
use crate::ir::normalize_manifest;
use crate::{ManifestError, OperationKind, PreparedManifest};

/// Generate a JavaScript prepared adapter over the existing SDK GraphClient.
pub fn generate_javascript(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = normalize_manifest(manifest)?;
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        if operation.supports_consistency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "read consistency options",
            });
        }
        if operation.supports_idempotency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "idempotent updates",
            });
        }
    }

    let mut out = String::from("// Generated by gleaph-codegen. Do not edit.\n\n");
    out.push_str("import { fromApiValue } from \"@gleaph/sdk\";\n\n");
    out.push_str("export const GLEAPH_GRAPH_ID = ");
    out.push_str(&json_string(&ir.graph_id));
    out.push_str(";\n\n");
    out.push_str("export function withPreparedQueries(client) {\n  return {\n");
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        if let Some(description) = &operation.description {
            append_jsdoc(&mut out, "    ", description);
        }
        let method = match operation.kind {
            OperationKind::Query => "executePrepared",
            OperationKind::Update => "executePreparedMutation",
        };
        let params = if operation.parameters.is_empty() {
            "params = {}"
        } else {
            "params"
        };
        let sort = if operation.allowed_sorts.is_empty() {
            ""
        } else {
            ", sort"
        };
        out.push_str(&format!(
            "    {}: async ({params}{sort}) => {{\n",
            ts_property(&operation.name)
        ));
        out.push_str("      const encodedParams = {};\n");
        for parameter in &operation.parameters {
            let key = json_string(&parameter.name);
            let value = encode_expression(&format!("params[{key}]"), &parameter.semantic_type);
            if parameter.required {
                out.push_str(&format!("      encodedParams[{key}] = {value};\n"));
            } else {
                out.push_str(&format!(
                    "      if (params[{key}] !== undefined) encodedParams[{key}] = {value};\n"
                ));
            }
        }
        out.push_str(&format!(
            "      const response = await client.{method}({}, encodedParams{});\n",
            json_string(&operation_ir.wire_name),
            if operation.allowed_sorts.is_empty() {
                ""
            } else {
                ", sort"
            }
        ));
        if operation.kind == OperationKind::Query {
            out.push_str("      return { ...response, rows: response.rows.map((row) => ({\n");
            for column in &operation.result.columns {
                out.push_str(&format!(
                    "        {}: fromApiValue(row[{}]),\n",
                    ts_property(&column.name),
                    json_string(&column.name)
                ));
            }
            out.push_str("      })) };\n    },\n");
        } else {
            out.push_str("      return response;\n    },\n");
        }
    }
    out.push_str("  };\n}\n");
    Ok(out)
}
