//! Motoko canister output profile for prepared-query adapters.

use crate::common::{append_line_doc, pascal_case};
use crate::ir::normalize_manifest;
use crate::{CodegenIr, ManifestError, OperationKind, PreparedManifest, SemanticType};

/// Generate a Motoko canister-side prepared-query facade.
pub fn generate_motoko(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = normalize_manifest(manifest)?;
    Ok(generate_ir(&ir))
}

fn generate_ir(ir: &CodegenIr) -> String {
    let mut body = format!(
        "public let GLEAPH_GRAPH_ID : Text = {};\n\n\
         public type PreparedResponse<Row> = {{ row_count : Nat64; rows : [Row] }};\n\n",
        motoko_string(&ir.graph_id)
    );

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        if let Some(description) = &operation.description {
            append_line_doc(&mut body, "", "///", description);
        }
        body.push_str(&format!("public type {type_name}Params = {{\n"));
        for parameter in &operation.parameters {
            if let Some(description) = &parameter.description {
                append_line_doc(&mut body, "  ", "///", description);
            }
            let optional = if parameter.required && !parameter.nullable {
                ""
            } else {
                "?"
            };
            body.push_str(&format!(
                "  {} : {}{};\n",
                motoko_identifier(&parameter.name),
                motoko_type(&parameter.semantic_type),
                optional
            ));
        }
        body.push_str("};\n\n");

        body.push_str(&format!("public type {type_name}Row = {{\n"));
        for column in &operation.result.columns {
            body.push_str(&format!(
                "  {} : {};\n",
                motoko_identifier(&column.name),
                motoko_nullable_type(&column.semantic_type, column.nullable)
            ));
        }
        body.push_str("};\n\n");

        let executor_type = format!("{type_name}Executor");
        let response = format!("PreparedResponse<{type_name}Row>");
        let method = match operation.kind {
            OperationKind::Query => "executeQuery",
            OperationKind::Update => "executeUpdate",
        };
        body.push_str(&format!(
            "public type {executor_type} = {{\n  {method} : (Text, {type_name}Params) -> async {response};\n}};\n\n"
        ));
        body.push_str(&format!(
            "public class {type_name}Queries(executor : {executor_type}) {{\n  /// Execute the prepared operation.\n  public func execute(params : {type_name}Params) : async {response} {{\n    await executor.{method}({}, params)\n  }};\n}};\n\n",
            motoko_string(&operation.name)
        ));
    }

    let imports = if ir.operations.iter().any(operation_uses_principal) {
        "import Principal \"mo:core/Principal\";\n\n"
    } else {
        ""
    };
    let mut out = format!("/// Generated by gleaph-codegen. Do not edit.\n\n{imports}module {{\n");
    for line in body.trim_end().lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            out.push_str("  ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("};\n");
    out
}

fn operation_uses_principal(operation: &crate::ir::OperationIr) -> bool {
    operation
        .operation
        .parameters
        .iter()
        .any(|parameter| semantic_type_contains_principal(&parameter.semantic_type))
        || operation
            .operation
            .result
            .columns
            .iter()
            .any(|column| semantic_type_contains_principal(&column.semantic_type))
}

fn semantic_type_contains_principal(semantic_type: &SemanticType) -> bool {
    match semantic_type {
        SemanticType::Principal => true,
        SemanticType::List { element } => semantic_type_contains_principal(element),
        SemanticType::Record { fields } => fields
            .iter()
            .any(|field| semantic_type_contains_principal(&field.semantic_type)),
        _ => false,
    }
}

fn motoko_nullable_type(semantic_type: &SemanticType, nullable: bool) -> String {
    let ty = motoko_type(semantic_type);
    if nullable { format!("?{ty}") } else { ty }
}

fn motoko_type(semantic_type: &SemanticType) -> String {
    match semantic_type {
        SemanticType::Null => "Null".into(),
        SemanticType::Bool => "Bool".into(),
        SemanticType::Int8
        | SemanticType::Int16
        | SemanticType::Int32
        | SemanticType::Int64
        | SemanticType::Int128
        | SemanticType::Int256 => "Int".into(),
        SemanticType::Uint8
        | SemanticType::Uint16
        | SemanticType::Uint32
        | SemanticType::Uint64
        | SemanticType::Uint128
        | SemanticType::Uint256 => "Nat".into(),
        SemanticType::Float16 | SemanticType::Float32 | SemanticType::Float64 => "Float".into(),
        SemanticType::Float128 | SemanticType::Float256 => "Blob".into(),
        SemanticType::Decimal | SemanticType::Text => "Text".into(),
        SemanticType::Bytes | SemanticType::Path => "Blob".into(),
        SemanticType::Date | SemanticType::Time | SemanticType::LocalTime => "Nat64".into(),
        SemanticType::DateTime | SemanticType::LocalDateTime => {
            "{ seconds : Int64; nanos : Nat32 }".into()
        }
        SemanticType::ZonedDateTime => {
            "{ seconds : Int64; nanos : Nat32; offset_seconds : Int32 }".into()
        }
        SemanticType::ZonedTime => "{ nanos : Nat64; offset_seconds : Int32 }".into(),
        SemanticType::Duration => "{ months : Int32; nanos : Int64 }".into(),
        SemanticType::Principal => "Principal".into(),
        SemanticType::List { element } => format!("[{}]", motoko_type(element)),
        SemanticType::Record { fields } => {
            let fields = fields
                .iter()
                .map(|field| {
                    format!(
                        "{} : {}",
                        motoko_identifier(&field.name),
                        motoko_nullable_type(&field.semantic_type, field.nullable)
                    )
                })
                .collect::<Vec<_>>()
                .join("; ");
            format!("{{ {fields} }}")
        }
    }
}

fn motoko_identifier(name: &str) -> String {
    let identifier = name
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect::<String>();
    let identifier = if identifier.is_empty() {
        pascal_case(name).to_ascii_lowercase()
    } else {
        identifier
    };
    if identifier
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        format!("_{identifier}")
    } else {
        identifier
    }
}

fn motoko_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}
