//! Rust canister output profile for prepared-query adapters.
//!
//! The generated facade is transport-neutral. A canister runtime supplies the executor that
//! owns Candid encoding, Router calls, response decoding, and error conversion.

use crate::ir::CodegenIr;
use crate::rust::{rust_field, rust_type};
use crate::{ManifestError, OperationKind, PreparedManifest};

/// Generate Rust canister declarations and a runtime executor facade.
pub fn generate_rust_canister(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = manifest.normalize()?;
    Ok(generate_ir(&ir))
}

fn generate_ir(ir: &CodegenIr) -> String {
    let mut out = String::from(
        "// Generated by gleaph-codegen. Do not edit.\n\n\
         use std::collections::BTreeMap;\n\
         use std::future::Future;\n\
         use std::pin::Pin;\n\
         use gleaph_cdk::GqlParams;\n\
         use serde::de::DeserializeOwned;\n\
         use serde::{Deserialize, Serialize};\n\n",
    );
    out.push_str(&format!(
        "pub const GLEAPH_GRAPH_ID: &str = {:?};\n\n",
        ir.graph_id
    ));
    out.push_str(
        "/// Result returned by a canister-side prepared-query executor.\n\
         #[derive(Clone, Debug, Deserialize, Serialize)]\n\
         pub struct PreparedCanisterResponse<Row> {\n\
             /// Number of rows observed by the runtime.\n\
             pub row_count: u64,\n\
             /// Typed rows decoded by the runtime.\n\
             pub rows: Vec<Row>,\n\
         }\n\n\
         /// Runtime boundary used by generated canister methods.\n\
         pub trait PreparedCanisterExecutor {\n\
             /// Runtime-specific error type.\n\
             type Error;\n\n\
             /// Encode a generated parameter value for the Router wire contract.\n\
             fn encode_params<T: Serialize>(&self, params: &T) -> Result<Vec<u8>, Self::Error>;\n\n\
             /// Execute a prepared operation from logical GQL parameters.\n\
             fn execute_gql<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: GqlParams,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\n\
             /// Execute a read-only prepared operation.\n\
             fn execute_query<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: Vec<u8>,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\n\
             /// Execute a mutating prepared operation.\n\
             fn execute_update<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: Vec<u8>,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\
         }\n\n",
    );
    out.push_str(runtime_types());

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        out.push_str(&format!(
            "/// Parameters for the prepared operation {}.\n#[derive(Clone, Debug, Deserialize, Serialize)]\npub struct {}Params {{\n",
            operation.name, type_name
        ));
        for parameter in &operation.parameters {
            let field = rust_field(&parameter.name);
            let mut ty = rust_type(&parameter.semantic_type);
            if !parameter.required || parameter.nullable {
                ty = format!("Option<{ty}>");
            }
            out.push_str(&format!(
                "    /// Wire parameter {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                parameter.name, parameter.name
            ));
        }
        out.push_str("}\n\n");
        out.push_str(&format!(
            "/// One result row from the prepared operation {}.\n#[derive(Clone, Debug, Deserialize, Serialize)]\npub struct {}Row {{\n",
            operation.name, type_name
        ));
        for column in &operation.result.columns {
            let field = rust_field(&column.name);
            let ty = if column.nullable {
                format!("Option<{}>", rust_type(&column.semantic_type))
            } else {
                rust_type(&column.semantic_type)
            };
            out.push_str(&format!(
                "    /// Wire column {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                column.name, column.name
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str(
        "/// Typed facade over a canister-side prepared-query executor.\n\
         pub struct PreparedCanisterQueries<'a, E: PreparedCanisterExecutor> {\n\
             executor: &'a E,\n\
         }\n\n\
         impl<'a, E: PreparedCanisterExecutor> PreparedCanisterQueries<'a, E> {\n\
             /// Bind generated operations to a runtime executor.\n\
             pub fn new(executor: &'a E) -> Self {\n\
                 Self { executor }\n\
             }\n\n",
    );
    out.push_str(
        "    /// Execute a prepared operation using the shared logical GQL value model.\n\
         pub async fn execute_gql<Row>(\n\
             &self,\n\
             name: &'static str,\n\
             params: GqlParams,\n\
         ) -> Result<PreparedCanisterResponse<Row>, E::Error>\n\
         where\n\
             Row: DeserializeOwned,\n\
         {\n\
             self.executor.execute_gql::<Row>(name, params).await\n\
         }\n\n",
    );
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method = rust_field(&operation.name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let execute = match operation.kind {
            OperationKind::Query => "execute_query",
            OperationKind::Update => "execute_update",
        };
        out.push_str(&format!(
            "    /// Execute the prepared operation {}.\n    pub async fn {method}(&self, params: {params}) -> Result<PreparedCanisterResponse<{row}>, E::Error> {{\n        let params = self.executor.encode_params(&params)?;\n        self.executor.{execute}::<{row}>({:?}, params).await\n    }}\n\n",
            operation.name, operation.name
        ));
    }
    out.push_str("}\n");
    out
}

fn runtime_types() -> &'static str {
    "/// Date-time representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     pub struct PreparedDateTime { pub seconds: i64, pub nanos: u32 }\n\n\
     /// Zoned date-time representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     pub struct PreparedZonedDateTime { pub seconds: i64, pub nanos: u32, pub offset_seconds: i32 }\n\n\
     /// Zoned time representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     pub struct PreparedZonedTime { pub nanos: u64, pub offset_seconds: i32 }\n\n\
     /// Duration representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     pub struct PreparedDuration { pub months: i32, pub nanos: i64 }\n\n\
     /// Path element representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     pub enum PreparedPathElement { Vertex(Vec<u8>), Edge(Vec<u8>) }\n\n"
}
