//! Rust canister output profile for prepared-query adapters.
//!
//! The generated facade is transport-neutral. A canister runtime supplies the executor that
//! owns Candid encoding, Router calls, response decoding, and error conversion.

use crate::common::append_line_doc;
use crate::ir::CodegenIr;
use crate::ir::normalize_manifest;
use crate::rust::{rust_field, rust_type};
use crate::{ManifestError, OperationKind, PreparedManifest};

/// Generate Rust canister declarations and a runtime executor facade.
pub fn generate_rust_canister(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = normalize_manifest(manifest)?;
    Ok(generate_ir(&ir))
}

fn generate_ir(ir: &CodegenIr) -> String {
    let has_gql_params = ir.operations.iter().any(|operation_ir| {
        operation_ir
            .operation
            .parameters
            .iter()
            .all(|parameter| gql_value_expression("value", &parameter.semantic_type).is_some())
    });
    let mut out = String::from(
        "//! Generated by gleaph-codegen. Do not edit.\n\n\
         #![allow(dead_code)]\n\n\
         use gleaph_cdk::GqlParams;\n",
    );

    if has_gql_params {
        out.push_str("use gleaph_cdk::GqlValue;\n");
    }
    out.push_str(
        "use gleaph_cdk::serde::de::DeserializeOwned;\n\
         use gleaph_cdk::serde::{Deserialize, Serialize};\n\
         use std::future::Future;\n\
         use std::pin::Pin;\n\n",
    );
    out.push_str(&format!(
        "pub const GLEAPH_GRAPH_ID: &str = {:?};\n",
        ir.graph_id
    ));
    out.push_str(
        r#"
/// Result returned by a canister-side prepared-query executor.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedCanisterResponse<Row> {
    /// Number of rows observed by the runtime.
    pub row_count: u64,
    /// Typed rows decoded by the runtime.
    pub rows: Vec<Row>,
}

/// Runtime boundary used by generated canister methods.
pub trait PreparedCanisterExecutor {
    /// Runtime-specific error type.
    type Error;

    /// Encode a generated parameter value for the Router wire contract.
    fn encode_params<T: Serialize>(&self, params: &T) -> Result<Vec<u8>, Self::Error>;

    /// Execute a prepared operation from logical GQL parameters.
    fn execute_gql<'a, Row>(
        &'a self,
        name: &'static str,
        params: GqlParams,
    ) -> PreparedCanisterFuture<'a, Row, Self::Error>
    where
        Row: DeserializeOwned + 'a;

    /// Execute a read-only prepared operation.
    fn execute_query<'a, Row>(
        &'a self,
        name: &'static str,
        params: Vec<u8>,
    ) -> PreparedCanisterFuture<'a, Row, Self::Error>
    where
        Row: DeserializeOwned + 'a;

    /// Execute a mutating prepared operation.
    fn execute_update<'a, Row>(
        &'a self,
        name: &'static str,
        params: Vec<u8>,
    ) -> PreparedCanisterFuture<'a, Row, Self::Error>
    where
        Row: DeserializeOwned + 'a;
}

/// Boxed future returned by a generated canister executor.
pub type PreparedCanisterFuture<'a, Row, Error> =
    Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Error>> + 'a>>;

"#,
    );
    out.push_str(runtime_types());

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        if let Some(description) = &operation.description {
            append_line_doc(&mut out, "", "///", description);
        }
        out.push_str(&format!(
            "/// Parameters for the prepared operation {}.\n#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(crate = \"gleaph_cdk::serde\")]\npub struct {}Params {{\n",
            operation.name, type_name
        ));
        for parameter in &operation.parameters {
            let field = rust_field(&parameter.name);
            let mut ty = canister_param_rust_type(&parameter.semantic_type);
            if !parameter.required || parameter.nullable {
                ty = format!("Option<{ty}>");
            }
            if let Some(description) = &parameter.description {
                append_line_doc(&mut out, "    ", "///", description);
            }
            out.push_str(&format!(
                "    /// Wire parameter {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                parameter.name, parameter.name
            ));
        }
        out.push_str("}\n\n");
        if operation
            .parameters
            .iter()
            .all(|parameter| gql_value_expression("value", &parameter.semantic_type).is_some())
        {
            let entries = operation
                .parameters
                .iter()
                .map(|parameter| {
                    let field = rust_field(&parameter.name);
                    let value = parameter_value_expression(&format!("self.{field}"), parameter);
                    format!("({:?}.to_string(), {value})", parameter.name)
                })
                .collect::<Vec<_>>();
            let one_line = format!("vec![{}]", entries.join(", "));
            let params_body =
                if !crate::rust_format::exceeds_width(&one_line, crate::rust_format::ARRAY_WIDTH) {
                    format!("        {one_line}\n")
                } else {
                    format!(
                        "        vec![\n            {},\n        ]\n",
                        entries.join(",\n            ")
                    )
                };
            out.push_str(&format!(
                "impl {}Params {{\n    /// Convert typed parameters to ordered logical GQL parameters.\n    pub fn into_gql_params(self) -> GqlParams {{\n{params_body}    }}\n}}\n\n",
                type_name
            ));
        }
        out.push_str(&format!(
            "/// One result row from the prepared operation {}.\n#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(crate = \"gleaph_cdk::serde\")]\npub struct {}Row {{\n",
            operation.name, type_name
        ));
        for column in &operation.result.columns {
            let field = rust_field(&column.name);
            let ty = if column.nullable {
                format!("Option<{}>", canister_rust_type(&column.semantic_type))
            } else {
                canister_rust_type(&column.semantic_type)
            };
            out.push_str(&format!(
                "    /// Wire column {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                column.name, column.name
            ));
        }
        out.push_str("}\n\n");
        if operation
            .result
            .columns
            .iter()
            .all(|column| row_value_expression(&column.semantic_type).is_some())
        {
            out.push_str(&format!(
                "impl gleaph_cdk::FromGqlRow for {}Row {{\n    fn from_gql_row(mut row: gleaph_cdk::GqlRow) -> Result<Self, gleaph_cdk::GqlWireDecodeError> {{\n",
                type_name
            ));
            for column in &operation.result.columns {
                let field = rust_field(&column.name);
                let value = row_value_expression(&column.semantic_type)
                    .expect("row conversion was checked before rendering");
                let value = if column.nullable {
                    format!(
                        "match gleaph_cdk::take_gql_row_field(&mut row, {:?})? {{ gleaph_cdk::GqlValue::Null => None, value => Some({value}) }}",
                        column.name
                    )
                } else {
                    format!(
                        "{{ let value = gleaph_cdk::take_gql_row_field(&mut row, {:?})?; {value} }}",
                        column.name
                    )
                };
                if !column.nullable && matches!(column.semantic_type, crate::SemanticType::Text) {
                    out.push_str(&format!(
                        "        let {field} = {{\n            let value = gleaph_cdk::take_gql_row_field(&mut row, {:?})?;\n            match value {{\n                GqlValue::Text(value) => value,\n                _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Text\")),\n            }}\n        }};\n",
                        column.name
                    ));
                } else {
                    out.push_str(&format!("        let {field} = {value};\n"));
                }
            }
            if operation.result.columns.len() == 1 {
                let field = rust_field(&operation.result.columns[0].name);
                let literal = format!("Self {{ {field} }}");
                if crate::rust_format::exceeds_width(&literal, crate::rust_format::STRUCT_LIT_WIDTH)
                {
                    out.push_str(&format!(
                        "        Ok(Self {{\n            {field},\n        }})\n    }}\n}}\n\n"
                    ));
                } else {
                    out.push_str(&format!("        Ok({literal})\n    }}\n}}\n\n"));
                }
            } else {
                out.push_str("        Ok(Self {\n");
                for column in &operation.result.columns {
                    let field = rust_field(&column.name);
                    out.push_str(&format!("            {field},\n"));
                }
                out.push_str("        })\n    }\n}\n\n");
            }
        }
    }

    out.push_str(
        r#"/// Typed facade over a canister-side prepared-query executor.
pub struct PreparedCanisterQueries<'a, E: PreparedCanisterExecutor> {
    executor: &'a E,
}

impl<'a, E: PreparedCanisterExecutor> PreparedCanisterQueries<'a, E> {
    /// Bind generated operations to a runtime executor.
    pub fn new(executor: &'a E) -> Self {
        Self { executor }
    }

    /// Execute a prepared operation using the shared logical GQL value model.
    pub async fn execute_gql<Row>(
        &self,
        name: &'static str,
        params: GqlParams,
    ) -> Result<PreparedCanisterResponse<Row>, E::Error>
    where
        Row: DeserializeOwned,
    {
        self.executor.execute_gql::<Row>(name, params).await
    }

"#,
    );
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method = rust_field(&operation.name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let execute = match operation.kind {
            OperationKind::Query => "execute_query",
            OperationKind::Update => "execute_update",
        };
        if operation
            .parameters
            .iter()
            .all(|parameter| gql_value_expression("value", &parameter.semantic_type).is_some())
        {
            out.push_str(&format!(
                "    /// Execute the prepared operation {}.\n    pub async fn {method}(\n        &self,\n        params: {params},\n    ) -> Result<PreparedCanisterResponse<{row}>, E::Error> {{\n        self.executor\n            .execute_gql::<{row}>({:?}, params.into_gql_params())\n            .await\n    }}\n\n",
                operation.name, operation.name
            ));
        } else {
            out.push_str(&format!(
                "    /// Execute the prepared operation {}.\n    pub async fn {method}(\n        &self,\n        params: {params},\n    ) -> Result<PreparedCanisterResponse<{row}>, E::Error> {{\n        let params = self.executor.encode_params(&params)?;\n        self.executor.{execute}::<{row}>({:?}, params).await\n    }}\n\n",
                operation.name, operation.name
            ));
        }
    }
    if out.ends_with("\n\n") {
        out.pop();
    }
    out.push_str("}\n");
    out
}

fn parameter_value_expression(access: &str, parameter: &crate::Parameter) -> String {
    if parameter.required && !parameter.nullable {
        return gql_value_expression(access, &parameter.semantic_type)
            .expect("parameter conversion was checked before rendering");
    }

    let value = gql_value_expression("value", &parameter.semantic_type)
        .expect("parameter conversion was checked before rendering");
    format!("match {access} {{ Some(value) => {value}, None => GqlValue::Null }}")
}

fn gql_value_expression(access: &str, semantic_type: &crate::SemanticType) -> Option<String> {
    let value = match semantic_type {
        crate::SemanticType::Null => "GqlValue::Null".to_string(),
        crate::SemanticType::Bool => format!("GqlValue::Bool({access})"),
        crate::SemanticType::Int8 => format!("GqlValue::Int8({access})"),
        crate::SemanticType::Int16 => format!("GqlValue::Int16({access})"),
        crate::SemanticType::Int32 => format!("GqlValue::Int32({access})"),
        crate::SemanticType::Int64 => format!("GqlValue::Int64({access})"),
        crate::SemanticType::Uint8 => format!("GqlValue::Uint8({access})"),
        crate::SemanticType::Uint16 => format!("GqlValue::Uint16({access})"),
        crate::SemanticType::Uint32 => format!("GqlValue::Uint32({access})"),
        crate::SemanticType::Uint64 => format!("GqlValue::Uint64({access})"),
        crate::SemanticType::Int128 => format!("GqlValue::Int128({access})"),
        crate::SemanticType::Uint128 => format!("GqlValue::Uint128({access})"),
        crate::SemanticType::Int256 => format!("GqlValue::Int256({access}.into_inner())"),
        crate::SemanticType::Uint256 => format!("GqlValue::Uint256({access}.into_inner())"),
        crate::SemanticType::Float16 => {
            format!("GqlValue::Float16(gleaph_cdk::GqlFloat16::from_bits({access}).into_inner())")
        }
        crate::SemanticType::Float32 => format!("GqlValue::Float32({access})"),
        crate::SemanticType::Float64 => format!("GqlValue::Float64({access})"),
        crate::SemanticType::Float128 => {
            format!("GqlValue::Float128({access}.into_inner())")
        }
        crate::SemanticType::Float256 => {
            format!("GqlValue::Float256({access}.into_inner())")
        }
        crate::SemanticType::Decimal => format!("GqlValue::Decimal({access}.into_inner())"),
        crate::SemanticType::Text => format!("GqlValue::Text({access})"),
        crate::SemanticType::Bytes => format!("GqlValue::Bytes({access})"),
        crate::SemanticType::Principal => {
            format!("gleaph_cdk::gql_principal_value({access})")
        }
        crate::SemanticType::Date => format!("GqlValue::Date({access})"),
        crate::SemanticType::Time => format!("GqlValue::Time({access})"),
        crate::SemanticType::LocalTime => format!("GqlValue::LocalTime({access})"),
        crate::SemanticType::DateTime | crate::SemanticType::LocalDateTime => {
            let variant = match semantic_type {
                crate::SemanticType::DateTime => "DateTime",
                crate::SemanticType::LocalDateTime => "LocalDateTime",
                _ => unreachable!(),
            };
            format!("GqlValue::{variant}({access}.seconds, {access}.nanos)")
        }
        crate::SemanticType::ZonedDateTime => {
            format!(
                "GqlValue::ZonedDateTime({access}.seconds, {access}.nanos, {access}.offset_seconds)"
            )
        }
        crate::SemanticType::ZonedTime => {
            format!("GqlValue::ZonedTime({access}.nanos, {access}.offset_seconds)")
        }
        crate::SemanticType::Duration => {
            format!("GqlValue::Duration({access}.months, {access}.nanos)")
        }
        crate::SemanticType::Record { .. } => format!("GqlValue::Record({access})"),
        crate::SemanticType::Path => format!(
            "GqlValue::Path({access}.into_iter().map(|value| match value {{ PreparedPathElement::Vertex(value) => gleaph_cdk::GqlPathElement::Vertex(value.into()), PreparedPathElement::Edge(value) => gleaph_cdk::GqlPathElement::Edge(value.into()) }}).collect())"
        ),
        crate::SemanticType::List { element } => {
            let element = gql_value_expression("value", element)?;
            format!("GqlValue::List({access}.into_iter().map(|value| {element}).collect())")
        }
    };
    Some(value)
}

fn row_value_expression(semantic_type: &crate::SemanticType) -> Option<String> {
    let value = match semantic_type {
        crate::SemanticType::Null => {
            "match value { GqlValue::Null => (), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Null\")) }"
        }
        crate::SemanticType::Bool => {
            "match value { GqlValue::Bool(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Bool\")) }"
        }
        crate::SemanticType::Int8 => {
            "match value { GqlValue::Int8(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int8\")) }"
        }
        crate::SemanticType::Int16 => {
            "match value { GqlValue::Int16(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int16\")) }"
        }
        crate::SemanticType::Int32 => {
            "match value { GqlValue::Int32(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int32\")) }"
        }
        crate::SemanticType::Int64 => {
            "match value { GqlValue::Int64(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int64\")) }"
        }
        crate::SemanticType::Uint8 => {
            "match value { GqlValue::Uint8(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint8\")) }"
        }
        crate::SemanticType::Uint16 => {
            "match value { GqlValue::Uint16(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint16\")) }"
        }
        crate::SemanticType::Uint32 => {
            "match value { GqlValue::Uint32(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint32\")) }"
        }
        crate::SemanticType::Uint64 => {
            "match value { GqlValue::Uint64(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint64\")) }"
        }
        crate::SemanticType::Int128 => {
            "match value { GqlValue::Int128(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int128\")) }"
        }
        crate::SemanticType::Uint128 => {
            "match value { GqlValue::Uint128(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint128\")) }"
        }
        crate::SemanticType::Int256 => {
            "match value { GqlValue::Int256(value) => gleaph_cdk::GqlInt256::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int256\")) }"
        }
        crate::SemanticType::Uint256 => {
            "match value { GqlValue::Uint256(value) => gleaph_cdk::GqlUint256::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint256\")) }"
        }
        crate::SemanticType::Float16 => {
            "match value { GqlValue::Float16(value) => gleaph_cdk::GqlFloat16::from_bits(value.to_bits()), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float16\")) }"
        }
        crate::SemanticType::Float32 => {
            "match value { GqlValue::Float32(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float32\")) }"
        }
        crate::SemanticType::Float64 => {
            "match value { GqlValue::Float64(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float64\")) }"
        }
        crate::SemanticType::Float128 => {
            "match value { GqlValue::Float128(value) => gleaph_cdk::GqlFloat128::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float128\")) }"
        }
        crate::SemanticType::Float256 => {
            "match value { GqlValue::Float256(value) => gleaph_cdk::GqlFloat256::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float256\")) }"
        }
        crate::SemanticType::Decimal => {
            "match value { GqlValue::Decimal(value) => gleaph_cdk::GqlDecimal::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Decimal\")) }"
        }
        crate::SemanticType::Text => {
            "match value { GqlValue::Text(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Text\")) }"
        }
        crate::SemanticType::Bytes => {
            "match value { GqlValue::Bytes(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Bytes\")) }"
        }
        crate::SemanticType::Date => {
            "match value { GqlValue::Date(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Date\")) }"
        }
        crate::SemanticType::Time => {
            "match value { GqlValue::Time(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Time\")) }"
        }
        crate::SemanticType::LocalTime => {
            "match value { GqlValue::LocalTime(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"LocalTime\")) }"
        }
        crate::SemanticType::DateTime => {
            "match value { GqlValue::DateTime(seconds, nanos) => PreparedDateTime { seconds, nanos }, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"DateTime\")) }"
        }
        crate::SemanticType::LocalDateTime => {
            "match value { GqlValue::LocalDateTime(seconds, nanos) => PreparedDateTime { seconds, nanos }, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"LocalDateTime\")) }"
        }
        crate::SemanticType::ZonedDateTime => {
            "match value { GqlValue::ZonedDateTime(seconds, nanos, offset_seconds) => PreparedZonedDateTime { seconds, nanos, offset_seconds }, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"ZonedDateTime\")) }"
        }
        crate::SemanticType::ZonedTime => {
            "match value { GqlValue::ZonedTime(nanos, offset_seconds) => PreparedZonedTime { nanos, offset_seconds }, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"ZonedTime\")) }"
        }
        crate::SemanticType::Duration => {
            "match value { GqlValue::Duration(months, nanos) => PreparedDuration { months, nanos }, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Duration\")) }"
        }
        crate::SemanticType::Principal => "gleaph_cdk::gql_principal_from_value(value)?",
        crate::SemanticType::Path => {
            "match value { GqlValue::Path(value) => value.into_iter().map(|value| match value { gleaph_cdk::GqlPathElement::Vertex(value) => PreparedPathElement::Vertex(value.as_ref().to_vec()), gleaph_cdk::GqlPathElement::Edge(value) => PreparedPathElement::Edge(value.as_ref().to_vec()) }).collect(), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Path\")) }"
        }
        crate::SemanticType::Record { .. } => "gleaph_cdk::gql_record_to_json_map(value)?",
        crate::SemanticType::List { element } => {
            let element = row_value_expression(element)?;
            return Some(format!(
                "match value {{ GqlValue::List(value) => value.into_iter().map(|value| {{ {element} }}).collect::<Result<Vec<_>, _>>()?, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"List\")) }}"
            ));
        }
    };
    Some(value.to_string())
}

fn runtime_types() -> &'static str {
    r#"/// Date-time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedDateTime {
    pub seconds: i64,
    pub nanos: u32,
}

/// Zoned date-time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedZonedDateTime {
    pub seconds: i64,
    pub nanos: u32,
    pub offset_seconds: i32,
}

/// Zoned time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedZonedTime {
    pub nanos: u64,
    pub offset_seconds: i32,
}

/// Duration representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedDuration {
    pub months: i32,
    pub nanos: i64,
}

/// Path element representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "gleaph_cdk::serde")]
pub enum PreparedPathElement {
    Vertex(Vec<u8>),
    Edge(Vec<u8>),
}

"#
}

fn canister_rust_type(semantic_type: &crate::SemanticType) -> String {
    match semantic_type {
        crate::SemanticType::Int256 => "gleaph_cdk::GqlInt256".to_string(),
        crate::SemanticType::Uint256 => "gleaph_cdk::GqlUint256".to_string(),
        crate::SemanticType::Float128 => "gleaph_cdk::GqlFloat128".to_string(),
        crate::SemanticType::Float256 => "gleaph_cdk::GqlFloat256".to_string(),
        crate::SemanticType::Decimal => "gleaph_cdk::GqlDecimal".to_string(),
        crate::SemanticType::Principal => "gleaph_cdk::GqlPrincipal".to_string(),
        crate::SemanticType::Record { .. } => {
            "std::collections::BTreeMap<String, gleaph_cdk::serde_json::Value>".to_string()
        }
        crate::SemanticType::List { element } => {
            format!("Vec<{}>", canister_rust_type(element))
        }
        _ => rust_type(semantic_type),
    }
}

fn canister_param_rust_type(semantic_type: &crate::SemanticType) -> String {
    match semantic_type {
        crate::SemanticType::Record { .. } => "gleaph_cdk::GqlRecord".to_string(),
        crate::SemanticType::List { element } => {
            format!("Vec<{}>", canister_param_rust_type(element))
        }
        _ => canister_rust_type(semantic_type),
    }
}
