//! Rust application-client output profile for prepared-query adapters.
//!
//! The generated module contains operation-specific parameter and row declarations plus a small
//! executor trait. Transport, response decoding, and error policy remain owned by the Rust
//! runtime that implements the trait.

use crate::{CodegenIr, ManifestError, OperationKind, PreparedManifest, SemanticType};

/// Generate Rust declarations and an executor facade for a prepared-query manifest.
pub fn generate_rust(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = manifest.normalize()?;
    validate_runtime_features(&ir)?;
    Ok(generate_rust_ir(&ir))
}

fn validate_runtime_features(ir: &CodegenIr) -> Result<(), ManifestError> {
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        if operation.supports_consistency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "read consistency options",
            });
        }
        if operation.supports_idempotency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "idempotent updates",
            });
        }
    }
    Ok(())
}

fn generate_rust_ir(ir: &CodegenIr) -> String {
    let mut out = String::from(
        "// Generated by gleaph-codegen. Do not edit.\n\n\
         use std::collections::BTreeMap;\n\
         use std::future::Future;\n\
         use std::pin::Pin;\n\
         use serde::de::DeserializeOwned;\n\
         use serde::{Deserialize, Serialize};\n\n",
    );
    out.push_str(&format!(
        "pub const GLEAPH_GRAPH_ID: &str = {:?};\n\n",
        ir.graph_id
    ));
    out.push_str(
        "/// Sort specification accepted by a generated prepared query.\n\
         #[derive(Clone, Debug, Deserialize, Serialize)]\n\
         pub struct PreparedSortSpec {\n\
             /// Stable sort-key identifier.\n\
             pub key: String,\n\
             /// Sort direction.\n\
             pub direction: String,\n\
         }\n\n\
         /// Response envelope decoded by a runtime executor.\n\
         #[derive(Clone, Debug, Deserialize, Serialize)]\n\
         pub struct PreparedResponse<Row> {\n\
             /// Query execution metadata.\n\
             pub explain: serde_json::Value,\n\
             /// Planner summary.\n\
             pub plan_summary: serde_json::Value,\n\
             /// Execution result containing typed rows.\n\
             pub execution: PreparedExecution<Row>,\n\
         }\n\n\
         /// Typed execution result inside a prepared response.\n\
         #[derive(Clone, Debug, Deserialize, Serialize)]\n\
         pub struct PreparedExecution<Row> {\n\
             /// Rows returned by the operation.\n\
             pub rows: Vec<Row>,\n\
             /// Non-fatal execution warnings.\n\
             pub warnings: Vec<String>,\n\
             /// Runtime-specific execution summary.\n\
             pub summary: serde_json::Value,\n\
         }\n\n\
         /// Runtime boundary implemented by the selected Rust SDK or canister adapter.\n\
         pub trait PreparedExecutor {\n\
             /// Error returned by the runtime boundary.\n\
             type Error;\n\n\
             /// Execute a read-only prepared operation.\n\
             fn execute_query<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: BTreeMap<String, serde_json::Value>,\n\
                 sort: Option<Vec<PreparedSortSpec>>,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\n\
             /// Execute a mutating prepared operation.\n\
             fn execute_update<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: BTreeMap<String, serde_json::Value>,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\
         }\n\n",
    );

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        out.push_str(&format!(
            "/// Parameters for the `{}` prepared operation.\n#[derive(Clone, Debug, Deserialize, Serialize)]\npub struct {}Params {{\n",
            operation.name, type_name
        ));
        for parameter in &operation.parameters {
            let field = rust_field(&parameter.name);
            let ty = rust_type(&parameter.semantic_type);
            let ty = if parameter.required {
                if parameter.nullable {
                    format!("Option<{ty}>")
                } else {
                    ty
                }
            } else {
                format!("Option<{ty}>")
            };
            out.push_str(&format!(
                "    /// Wire parameter `{}`.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                parameter.name, parameter.name
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "/// One result row from the `{}` prepared operation.\n#[derive(Clone, Debug, Deserialize, Serialize)]\npub struct {}Row {{\n",
            operation.name, type_name
        ));
        for column in &operation.result.columns {
            let field = rust_field(&column.name);
            let ty = rust_type(&column.semantic_type);
            let ty = if column.nullable {
                format!("Option<{ty}>")
            } else {
                ty
            };
            out.push_str(&format!(
                "    /// Wire column `{}`.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                column.name, column.name
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str("/// Typed facade over a [`PreparedExecutor`].\npub struct PreparedQueries<'a, E: PreparedExecutor> {\n    executor: &'a E,\n}\n\nimpl<'a, E: PreparedExecutor> PreparedQueries<'a, E> {\n    /// Bind generated operations to a runtime executor.\n    pub fn new(executor: &'a E) -> Self {\n        Self { executor }\n    }\n\n");
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method = rust_field(&operation.name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let executor_method = match operation.kind {
            OperationKind::Query => "execute_query",
            OperationKind::Update => "execute_update",
        };
        let mut method_args = Vec::new();
        if !operation.parameters.is_empty() {
            method_args.push(format!("params: {params}"));
        }
        if !operation.allowed_sorts.is_empty() {
            method_args.push("sort: Option<Vec<PreparedSortSpec>>".to_string());
        }
        let method_signature = method_args.join(", ");
        let params_body = if operation.parameters.is_empty() {
            "        let params = BTreeMap::new();\n".to_string()
        } else {
            "        let params = serde_json::to_value(params)\n            .expect(\"generated parameter struct must serialize\")\n            .as_object()\n            .expect(\"generated parameter struct must serialize to an object\")\n            .clone()\n            .into_iter()\n            .collect();\n"
                .to_string()
        };
        let call = if operation.kind == OperationKind::Query {
            format!(
                "self.executor.{executor_method}::<{row}>({:?}, params, {}).await",
                operation.name,
                if operation.allowed_sorts.is_empty() {
                    "None"
                } else {
                    "sort"
                }
            )
        } else {
            format!(
                "self.executor.{executor_method}::<{row}>({:?}, params).await",
                operation.name
            )
        };
        out.push_str(&format!(
            "    /// Execute the `{}` prepared operation.\n    pub async fn {method}(&self{}{}) -> Result<PreparedResponse<{row}>, E::Error> {{\n{params_body}        {call}\n    }}\n\n",
            operation.name,
            if method_signature.is_empty() { "" } else { ", " },
            method_signature
        ));
    }
    out.push_str("}\n");
    out
}

fn rust_field(name: &str) -> String {
    let mut result = String::new();
    for (index, c) in name.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' {
            if index == 0 && c.is_ascii_digit() {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push('_');
        }
    }
    if result.is_empty() {
        "value".to_string()
    } else if matches!(
        result.as_str(),
        "type" | "match" | "ref" | "self" | "Self" | "crate"
    ) {
        format!("r#{result}")
    } else {
        result
    }
}

fn rust_type(semantic_type: &SemanticType) -> String {
    match semantic_type {
        SemanticType::Null => "()".to_string(),
        SemanticType::Bool => "bool".to_string(),
        SemanticType::Int64 => "i64".to_string(),
        SemanticType::Uint64 => "u64".to_string(),
        SemanticType::Int128 => "i128".to_string(),
        SemanticType::Uint128 => "u128".to_string(),
        SemanticType::Int256 | SemanticType::Uint256 | SemanticType::Decimal => {
            "String".to_string()
        }
        SemanticType::Float64 => "f64".to_string(),
        SemanticType::Text => "String".to_string(),
        SemanticType::Bytes => "Vec<u8>".to_string(),
        SemanticType::Date | SemanticType::Time => "i64".to_string(),
        SemanticType::Principal => "String".to_string(),
        SemanticType::List { element } => format!("Vec<{}>", rust_type(element)),
    }
}
