//! Rust canister output profile for prepared-query adapters.
//!
//! The generated facade is transport-neutral. A canister runtime supplies the executor that
//! owns Candid encoding, Router calls, response decoding, and error conversion.

use crate::ir::CodegenIr;
use crate::rust::{rust_field, rust_type};
use crate::{ManifestError, OperationKind, PreparedManifest};

/// Generate Rust canister declarations and a runtime executor facade.
pub fn generate_rust_canister(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = manifest.normalize()?;
    Ok(generate_ir(&ir))
}

fn generate_ir(ir: &CodegenIr) -> String {
    let has_gql_params = ir.operations.iter().any(|operation_ir| {
        operation_ir
            .operation
            .parameters
            .iter()
            .all(|parameter| gql_value_expression("value", &parameter.semantic_type).is_some())
    });
    let mut out = String::from(
        "// Generated by gleaph-codegen. Do not edit.\n\n\
         use std::collections::BTreeMap;\n\
         use std::future::Future;\n\
         use std::pin::Pin;\n\
         use gleaph_cdk::GqlParams;\n\
         use gleaph_cdk::serde::de::DeserializeOwned;\n\
         use gleaph_cdk::serde::{Deserialize, Serialize};\n\n",
    );
    if has_gql_params {
        out.push_str("use gleaph_cdk::GqlValue;\n\n");
    }
    out.push_str(&format!(
        "pub const GLEAPH_GRAPH_ID: &str = {:?};\n\n",
        ir.graph_id
    ));
    out.push_str(
        "/// Result returned by a canister-side prepared-query executor.\n\
         #[derive(Clone, Debug, Deserialize, Serialize)]\n\
         #[serde(crate = \"gleaph_cdk::serde\")]\n\
         pub struct PreparedCanisterResponse<Row> {\n\
             /// Number of rows observed by the runtime.\n\
             pub row_count: u64,\n\
             /// Typed rows decoded by the runtime.\n\
             pub rows: Vec<Row>,\n\
         }\n\n\
         /// Runtime boundary used by generated canister methods.\n\
         pub trait PreparedCanisterExecutor {\n\
             /// Runtime-specific error type.\n\
             type Error;\n\n\
             /// Encode a generated parameter value for the Router wire contract.\n\
             fn encode_params<T: Serialize>(&self, params: &T) -> Result<Vec<u8>, Self::Error>;\n\n\
             /// Execute a prepared operation from logical GQL parameters.\n\
             fn execute_gql<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: GqlParams,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\n\
             /// Execute a read-only prepared operation.\n\
             fn execute_query<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: Vec<u8>,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\n\
             /// Execute a mutating prepared operation.\n\
             fn execute_update<'a, Row>(\n\
                 &'a self,\n\
                 name: &'static str,\n\
                 params: Vec<u8>,\n\
             ) -> Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Self::Error>> + 'a>>\n\
             where\n\
                 Row: DeserializeOwned + 'a;\n\
         }\n\n",
    );
    out.push_str(runtime_types());

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        out.push_str(&format!(
            "/// Parameters for the prepared operation {}.\n#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(crate = \"gleaph_cdk::serde\")]\npub struct {}Params {{\n",
            operation.name, type_name
        ));
        for parameter in &operation.parameters {
            let field = rust_field(&parameter.name);
            let mut ty = canister_param_rust_type(&parameter.semantic_type);
            if !parameter.required || parameter.nullable {
                ty = format!("Option<{ty}>");
            }
            out.push_str(&format!(
                "    /// Wire parameter {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                parameter.name, parameter.name
            ));
        }
        out.push_str("}\n\n");
        if operation
            .parameters
            .iter()
            .all(|parameter| gql_value_expression("value", &parameter.semantic_type).is_some())
        {
            out.push_str(&format!(
                "impl {}Params {{\n    /// Convert typed parameters to ordered logical GQL parameters.\n    pub fn into_gql_params(self) -> GqlParams {{\n        vec![\n",
                type_name
            ));
            for parameter in &operation.parameters {
                let field = rust_field(&parameter.name);
                let value = parameter_value_expression(&format!("self.{field}"), parameter);
                out.push_str(&format!(
                    "            ({:?}.to_string(), {value}),\n",
                    parameter.name
                ));
            }
            out.push_str("        ]\n    }\n}\n\n");
        }
        out.push_str(&format!(
            "/// One result row from the prepared operation {}.\n#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(crate = \"gleaph_cdk::serde\")]\npub struct {}Row {{\n",
            operation.name, type_name
        ));
        for column in &operation.result.columns {
            let field = rust_field(&column.name);
            let ty = if column.nullable {
                format!("Option<{}>", canister_rust_type(&column.semantic_type))
            } else {
                canister_rust_type(&column.semantic_type)
            };
            out.push_str(&format!(
                "    /// Wire column {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                column.name, column.name
            ));
        }
        out.push_str("}\n\n");
        if operation
            .result
            .columns
            .iter()
            .all(|column| row_value_expression(&column.semantic_type).is_some())
        {
            out.push_str(&format!(
                "impl gleaph_cdk::FromGqlRow for {}Row {{\n    fn from_gql_row(mut row: gleaph_cdk::GqlRow) -> Result<Self, gleaph_cdk::GqlWireDecodeError> {{\n",
                type_name
            ));
            for column in &operation.result.columns {
                let field = rust_field(&column.name);
                let value = row_value_expression(&column.semantic_type)
                    .expect("row conversion was checked before rendering");
                let value = if column.nullable {
                    format!(
                        "match gleaph_cdk::take_gql_row_field(&mut row, {:?})? {{ gleaph_cdk::GqlValue::Null => None, value => Some({value}) }}",
                        column.name
                    )
                } else {
                    format!(
                        "{{ let value = gleaph_cdk::take_gql_row_field(&mut row, {:?})?; {value} }}",
                        column.name
                    )
                };
                out.push_str(&format!("        let {field} = {value};\n"));
            }
            out.push_str("        Ok(Self {\n");
            for column in &operation.result.columns {
                let field = rust_field(&column.name);
                out.push_str(&format!("            {field},\n"));
            }
            out.push_str("        })\n    }\n}\n\n");
        }
    }

    out.push_str(
        "/// Typed facade over a canister-side prepared-query executor.\n\
         pub struct PreparedCanisterQueries<'a, E: PreparedCanisterExecutor> {\n\
             executor: &'a E,\n\
         }\n\n\
         impl<'a, E: PreparedCanisterExecutor> PreparedCanisterQueries<'a, E> {\n\
             /// Bind generated operations to a runtime executor.\n\
             pub fn new(executor: &'a E) -> Self {\n\
                 Self { executor }\n\
             }\n\n",
    );
    out.push_str(
        "    /// Execute a prepared operation using the shared logical GQL value model.\n\
         pub async fn execute_gql<Row>(\n\
             &self,\n\
             name: &'static str,\n\
             params: GqlParams,\n\
         ) -> Result<PreparedCanisterResponse<Row>, E::Error>\n\
         where\n\
             Row: DeserializeOwned,\n\
         {\n\
             self.executor.execute_gql::<Row>(name, params).await\n\
         }\n\n",
    );
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method = rust_field(&operation.name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let execute = match operation.kind {
            OperationKind::Query => "execute_query",
            OperationKind::Update => "execute_update",
        };
        if operation
            .parameters
            .iter()
            .all(|parameter| gql_value_expression("value", &parameter.semantic_type).is_some())
        {
            out.push_str(&format!(
                "    /// Execute the prepared operation {}.\n    pub async fn {method}(&self, params: {params}) -> Result<PreparedCanisterResponse<{row}>, E::Error> {{\n        self.executor.execute_gql::<{row}>({:?}, params.into_gql_params()).await\n    }}\n\n",
                operation.name, operation.name
            ));
        } else {
            out.push_str(&format!(
                "    /// Execute the prepared operation {}.\n    pub async fn {method}(&self, params: {params}) -> Result<PreparedCanisterResponse<{row}>, E::Error> {{\n        let params = self.executor.encode_params(&params)?;\n        self.executor.{execute}::<{row}>({:?}, params).await\n    }}\n\n",
                operation.name, operation.name
            ));
        }
    }
    out.push_str("}\n");
    out
}

fn parameter_value_expression(access: &str, parameter: &crate::Parameter) -> String {
    if parameter.required && !parameter.nullable {
        return gql_value_expression(access, &parameter.semantic_type)
            .expect("parameter conversion was checked before rendering");
    }

    let value = gql_value_expression("value", &parameter.semantic_type)
        .expect("parameter conversion was checked before rendering");
    format!("match {access} {{ Some(value) => {value}, None => GqlValue::Null }}")
}

fn gql_value_expression(access: &str, semantic_type: &crate::SemanticType) -> Option<String> {
    let value = match semantic_type {
        crate::SemanticType::Null => "GqlValue::Null".to_string(),
        crate::SemanticType::Bool => format!("GqlValue::Bool({access})"),
        crate::SemanticType::Int8 => format!("GqlValue::Int8({access})"),
        crate::SemanticType::Int16 => format!("GqlValue::Int16({access})"),
        crate::SemanticType::Int32 => format!("GqlValue::Int32({access})"),
        crate::SemanticType::Int64 => format!("GqlValue::Int64({access})"),
        crate::SemanticType::Uint8 => format!("GqlValue::Uint8({access})"),
        crate::SemanticType::Uint16 => format!("GqlValue::Uint16({access})"),
        crate::SemanticType::Uint32 => format!("GqlValue::Uint32({access})"),
        crate::SemanticType::Uint64 => format!("GqlValue::Uint64({access})"),
        crate::SemanticType::Int128 => format!("GqlValue::Int128({access})"),
        crate::SemanticType::Uint128 => format!("GqlValue::Uint128({access})"),
        crate::SemanticType::Int256 => format!("GqlValue::Int256({access}.into_inner())"),
        crate::SemanticType::Uint256 => format!("GqlValue::Uint256({access}.into_inner())"),
        crate::SemanticType::Float16 => {
            format!("GqlValue::Float16(gleaph_cdk::GqlFloat16::from_bits({access}).into_inner())")
        }
        crate::SemanticType::Float32 => format!("GqlValue::Float32({access})"),
        crate::SemanticType::Float64 => format!("GqlValue::Float64({access})"),
        crate::SemanticType::Float128 => {
            format!("GqlValue::Float128({access}.into_inner())")
        }
        crate::SemanticType::Float256 => {
            format!("GqlValue::Float256({access}.into_inner())")
        }
        crate::SemanticType::Decimal => format!("GqlValue::Decimal({access}.into_inner())"),
        crate::SemanticType::Text => format!("GqlValue::Text({access})"),
        crate::SemanticType::Bytes => format!("GqlValue::Bytes({access})"),
        crate::SemanticType::Principal => {
            format!("gleaph_cdk::gql_principal_value({access})")
        }
        crate::SemanticType::Date => format!("GqlValue::Date({access})"),
        crate::SemanticType::Time => format!("GqlValue::Time({access})"),
        crate::SemanticType::LocalTime => format!("GqlValue::LocalTime({access})"),
        crate::SemanticType::DateTime | crate::SemanticType::LocalDateTime => {
            let variant = match semantic_type {
                crate::SemanticType::DateTime => "DateTime",
                crate::SemanticType::LocalDateTime => "LocalDateTime",
                _ => unreachable!(),
            };
            format!("GqlValue::{variant}({access}.seconds, {access}.nanos)")
        }
        crate::SemanticType::ZonedDateTime => {
            format!(
                "GqlValue::ZonedDateTime({access}.seconds, {access}.nanos, {access}.offset_seconds)"
            )
        }
        crate::SemanticType::ZonedTime => {
            format!("GqlValue::ZonedTime({access}.nanos, {access}.offset_seconds)")
        }
        crate::SemanticType::Duration => {
            format!("GqlValue::Duration({access}.months, {access}.nanos)")
        }
        crate::SemanticType::Record { .. } => format!("GqlValue::Record({access})"),
        crate::SemanticType::Path => format!(
            "GqlValue::Path({access}.into_iter().map(|value| match value {{ PreparedPathElement::Vertex(value) => gleaph_cdk::GqlPathElement::Vertex(value.into()), PreparedPathElement::Edge(value) => gleaph_cdk::GqlPathElement::Edge(value.into()) }}).collect())"
        ),
        crate::SemanticType::List { element } => {
            let element = gql_value_expression("value", element)?;
            format!("GqlValue::List({access}.into_iter().map(|value| {element}).collect())")
        }
    };
    Some(value)
}

fn row_value_expression(semantic_type: &crate::SemanticType) -> Option<String> {
    let value = match semantic_type {
        crate::SemanticType::Bool => {
            "match value { GqlValue::Bool(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Bool\")) }"
        }
        crate::SemanticType::Int8 => {
            "match value { GqlValue::Int8(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int8\")) }"
        }
        crate::SemanticType::Int16 => {
            "match value { GqlValue::Int16(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int16\")) }"
        }
        crate::SemanticType::Int32 => {
            "match value { GqlValue::Int32(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int32\")) }"
        }
        crate::SemanticType::Int64 => {
            "match value { GqlValue::Int64(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int64\")) }"
        }
        crate::SemanticType::Uint8 => {
            "match value { GqlValue::Uint8(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint8\")) }"
        }
        crate::SemanticType::Uint16 => {
            "match value { GqlValue::Uint16(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint16\")) }"
        }
        crate::SemanticType::Uint32 => {
            "match value { GqlValue::Uint32(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint32\")) }"
        }
        crate::SemanticType::Uint64 => {
            "match value { GqlValue::Uint64(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint64\")) }"
        }
        crate::SemanticType::Int128 => {
            "match value { GqlValue::Int128(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int128\")) }"
        }
        crate::SemanticType::Uint128 => {
            "match value { GqlValue::Uint128(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint128\")) }"
        }
        crate::SemanticType::Int256 => {
            "match value { GqlValue::Int256(value) => gleaph_cdk::GqlInt256::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Int256\")) }"
        }
        crate::SemanticType::Uint256 => {
            "match value { GqlValue::Uint256(value) => gleaph_cdk::GqlUint256::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Uint256\")) }"
        }
        crate::SemanticType::Float16 => {
            "match value { GqlValue::Float16(value) => gleaph_cdk::GqlFloat16::from_bits(value.to_bits()), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float16\")) }"
        }
        crate::SemanticType::Float32 => {
            "match value { GqlValue::Float32(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float32\")) }"
        }
        crate::SemanticType::Float64 => {
            "match value { GqlValue::Float64(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float64\")) }"
        }
        crate::SemanticType::Float256 => {
            "match value { GqlValue::Float256(value) => gleaph_cdk::GqlFloat256::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Float256\")) }"
        }
        crate::SemanticType::Decimal => {
            "match value { GqlValue::Decimal(value) => gleaph_cdk::GqlDecimal::from_inner(value), _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Decimal\")) }"
        }
        crate::SemanticType::Text => {
            "match value { GqlValue::Text(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Text\")) }"
        }
        crate::SemanticType::Bytes => {
            "match value { GqlValue::Bytes(value) => value, _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch(\"Bytes\")) }"
        }
        _ => return None,
    };
    Some(value.to_string())
}

fn runtime_types() -> &'static str {
    "/// Date-time representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     #[serde(crate = \"gleaph_cdk::serde\")]\n\
     pub struct PreparedDateTime { pub seconds: i64, pub nanos: u32 }\n\n\
     /// Zoned date-time representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     #[serde(crate = \"gleaph_cdk::serde\")]\n\
     pub struct PreparedZonedDateTime { pub seconds: i64, pub nanos: u32, pub offset_seconds: i32 }\n\n\
     /// Zoned time representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     #[serde(crate = \"gleaph_cdk::serde\")]\n\
     pub struct PreparedZonedTime { pub nanos: u64, pub offset_seconds: i32 }\n\n\
     /// Duration representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     #[serde(crate = \"gleaph_cdk::serde\")]\n\
     pub struct PreparedDuration { pub months: i32, pub nanos: i64 }\n\n\
     /// Path element representation used by generated declarations.\n\
     #[derive(Clone, Debug, Deserialize, Serialize)]\n\
     #[serde(crate = \"gleaph_cdk::serde\")]\n\
     pub enum PreparedPathElement { Vertex(Vec<u8>), Edge(Vec<u8>) }\n\n"
}

fn canister_rust_type(semantic_type: &crate::SemanticType) -> String {
    match semantic_type {
        crate::SemanticType::Int256 => "gleaph_cdk::GqlInt256".to_string(),
        crate::SemanticType::Uint256 => "gleaph_cdk::GqlUint256".to_string(),
        crate::SemanticType::Float128 => "gleaph_cdk::GqlFloat128".to_string(),
        crate::SemanticType::Float256 => "gleaph_cdk::GqlFloat256".to_string(),
        crate::SemanticType::Decimal => "gleaph_cdk::GqlDecimal".to_string(),
        crate::SemanticType::Principal => "gleaph_cdk::GqlPrincipal".to_string(),
        crate::SemanticType::Record { .. } => {
            "std::collections::BTreeMap<String, gleaph_cdk::serde_json::Value>".to_string()
        }
        crate::SemanticType::List { element } => {
            format!("Vec<{}>", canister_rust_type(element))
        }
        _ => rust_type(semantic_type),
    }
}

fn canister_param_rust_type(semantic_type: &crate::SemanticType) -> String {
    match semantic_type {
        crate::SemanticType::Record { .. } => "gleaph_cdk::GqlRecord".to_string(),
        crate::SemanticType::List { element } => {
            format!("Vec<{}>", canister_param_rust_type(element))
        }
        _ => canister_rust_type(semantic_type),
    }
}
