//! TypeScript output profile for prepared-query adapters.
//!
//! Generated code delegates transport and common error handling to the TypeScript SDK while
//! emitting operation-specific parameter and result declarations.

use crate::common::{
    append_jsdoc, camel_case, column_const_name, encode_expression, json_string, ts_column_specs,
    ts_property,
};
use crate::ir::normalize_manifest;
use crate::{CodegenIr, ManifestError, OperationKind, PreparedManifest, SemanticType};

/// Generate a TypeScript prepared adapter over the existing SDK GleaphClient.
pub fn generate_typescript(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = normalize_manifest(manifest)?;
    validate_runtime_features(&ir)?;
    generate_typescript_ir(&ir)
}

fn generate_typescript_ir(ir: &CodegenIr) -> Result<String, ManifestError> {
    let has_sorts = ir
        .operations
        .iter()
        .any(|operation| !operation.operation.allowed_sorts.is_empty());
    let has_queries = ir
        .operations
        .iter()
        .any(|operation| operation.operation.kind == OperationKind::Query);
    let has_updates = ir
        .operations
        .iter()
        .any(|operation| operation.operation.kind == OperationKind::Update);
    let has_params = ir
        .operations
        .iter()
        .any(|operation| !operation.operation.parameters.is_empty());
    let mut uses = TypeUses::default();
    for operation_ir in &ir.operations {
        for parameter in &operation_ir.operation.parameters {
            collect_type_uses(&parameter.semantic_type, &mut uses, false);
        }
        for column in &operation_ir.operation.result.columns {
            collect_type_uses(&column.semantic_type, &mut uses, true);
        }
    }
    let mut type_imports = vec![
        "ApiValue".to_string(),
        "GleaphClient".to_string(),
        "GleaphTransport".to_string(),
        "GleaphTransportOptions".to_string(),
    ];
    if has_updates {
        type_imports.push("GqlMutationResult".to_string());
    }
    if has_queries {
        type_imports.push("GqlQueryResult".to_string());
        type_imports.push("PreparedManifestColumn".to_string());
    }
    if has_sorts {
        type_imports.push("PreparedSortSpec".to_string());
    }
    if uses.path {
        type_imports.push("ApiPathElement".to_string());
    }
    if uses.decimal {
        type_imports.push("GqlDecimal".to_string());
    }
    if uses.float16 {
        type_imports.push("GqlFloat16".to_string());
    }
    if uses.float128 {
        type_imports.push("GqlFloat128".to_string());
    }
    if uses.float256 {
        type_imports.push("GqlFloat256".to_string());
    }
    if uses.zoned_time {
        type_imports.push("GqlZonedTime".to_string());
    }
    if uses.temporal {
        type_imports.push("Temporal".to_string());
    }
    let mut out = String::from("// Generated by gleaph-codegen. Do not edit.\n\n");
    out.push_str(&format!(
        "import type {{ {} }} from \"@gleaph/sdk\";\n",
        type_imports.join(", ")
    ));
    if uses.principal {
        out.push_str("import type { Principal } from \"@icp-sdk/core/principal\";\n");
    }
    let mut value_imports = vec![
        "GleaphClientWrapper".to_string(),
        "createGleaphClient".to_string(),
        "createGleaphClientFromTransport".to_string(),
    ];
    if has_params {
        value_imports.push("toApiValue".to_string());
    }
    if has_queries {
        value_imports.push("decodeRows".to_string());
    }
    out.push_str(&format!(
        "import {{ {} }} from \"@gleaph/sdk\";\n",
        value_imports.join(", ")
    ));
    out.push('\n');
    out.push_str("export const GLEAPH_GRAPH_ID = ");
    out.push_str(&json_string(&ir.graph_id));
    out.push_str(" as const;\n\n");
    if has_queries {
        out.push_str(
            "type PreparedResponse<Row> = Omit<GqlQueryResult, \"rows\"> & { rows: Row[] };\n\n",
        );
    }
    out.push_str("export type PrincipalLike = string | { toText(): string };\n\n");

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let base = &operation_ir.type_name;
        if let Some(description) = &operation.description {
            append_jsdoc(&mut out, "", description);
        }
        out.push_str(&format!("export interface {base}Params {{\n"));
        for parameter in &operation.parameters {
            let optional = if parameter.required { "" } else { "?" };
            if let Some(description) = &parameter.description {
                append_jsdoc(&mut out, "  ", description);
            }
            out.push_str(&format!(
                "  {}{}: {};\n",
                ts_property(&parameter.name),
                optional,
                ts_type(&parameter.semantic_type, parameter.nullable, false)
            ));
        }
        out.push_str("}\n\n");
        out.push_str(&format!("export interface {base}Row {{\n"));
        for column in &operation.result.columns {
            out.push_str(&format!(
                "  {}: {};\n",
                ts_property(&column.name),
                ts_type(&column.semantic_type, column.nullable, true)
            ));
        }
        out.push_str("}\n\n");
        if operation.kind == OperationKind::Query {
            out.push_str(&format!(
                "const {}: PreparedManifestColumn[] = {};\n\n",
                column_const_name(&operation_ir.wire_name),
                ts_column_specs(&operation.result.columns)
            ));
        }
    }

    out.push_str("export interface PreparedQueries {\n");
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method_name = camel_case(&operation_ir.wire_name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let mut signature_args = Vec::new();
        if !operation.parameters.is_empty() {
            signature_args.push(format!("params: {params}"));
        } else if operation.kind == OperationKind::Query {
            signature_args.push(format!("params?: {params}"));
        }
        if operation.kind == OperationKind::Update {
            signature_args.push("clientMutationKey: string".to_string());
        }
        if !operation.allowed_sorts.is_empty() {
            signature_args.push("sort?: PreparedSortSpec[]".to_string());
        }
        let response = match operation.kind {
            OperationKind::Query => format!("PreparedResponse<{row}>"),
            OperationKind::Update => "GqlMutationResult".to_string(),
        };
        out.push_str(&format!(
            "  {method_name}({}): Promise<{response}>;\n",
            signature_args.join(", ")
        ));
    }
    out.push_str("}\n\n");
    out.push_str(
        "export class PreparedGleaphClient extends GleaphClientWrapper implements PreparedQueries {\n",
    );
    out.push_str("  constructor(client: GleaphClient) {\n    super(client);\n  }\n\n");
    for (index, operation_ir) in ir.operations.iter().enumerate() {
        if index > 0 {
            out.push('\n');
        }
        let operation = &operation_ir.operation;
        if let Some(description) = &operation.description {
            append_jsdoc(&mut out, "  ", description);
        }
        let method_name = camel_case(&operation_ir.wire_name);
        let method = match operation.kind {
            OperationKind::Query => "preparedQuery",
            OperationKind::Update => "preparedMutate",
        };
        let params_type = &operation_ir.params_type_name;
        let mut impl_args = Vec::new();
        if !operation.parameters.is_empty() {
            impl_args.push(format!("params: {params_type}"));
        } else if operation.kind == OperationKind::Query {
            impl_args.push(format!("params: {params_type} = {{}}"));
        }
        if operation.kind == OperationKind::Update {
            impl_args.push("clientMutationKey: string".to_string());
        }
        if !operation.allowed_sorts.is_empty() {
            impl_args.push("sort?: PreparedSortSpec[]".to_string());
        }
        let row = &operation_ir.row_type_name;
        let response = match operation.kind {
            OperationKind::Query => format!("PreparedResponse<{row}>"),
            OperationKind::Update => "GqlMutationResult".to_string(),
        };
        out.push_str(&format!(
            "  async {method_name}({}): Promise<{response}> {{\n",
            impl_args.join(", ")
        ));
        out.push_str("    const encodedParams: Record<string, ApiValue> = {};\n");
        append_encoded_params(&mut out, operation, "    ");
        let call_args = if operation.kind == OperationKind::Update {
            format!(
                "{}, encodedParams, clientMutationKey{}",
                json_string(&operation_ir.wire_name),
                if operation.allowed_sorts.is_empty() {
                    ""
                } else {
                    ", sort"
                }
            )
        } else {
            format!(
                "{}, encodedParams{}",
                json_string(&operation_ir.wire_name),
                if operation.allowed_sorts.is_empty() {
                    ""
                } else {
                    ", sort"
                }
            )
        };
        out.push_str(&format!(
            "    const response = await this.{method}({call_args});\n"
        ));
        if operation.kind == OperationKind::Query {
            out.push_str(&format!(
                "    return {{ ...response, rows: decodeRows(response.rows, {}) as unknown as {}[] }};\n",
                column_const_name(&operation_ir.wire_name),
                row
            ));
        } else {
            out.push_str("    return response;\n");
        }
        out.push_str("  }\n");
    }
    out.push_str("}\n\n");
    out.push_str(
        "export function withPreparedQueries(client: GleaphClient): PreparedGleaphClient {\n",
    );
    out.push_str("  return new PreparedGleaphClient(client);\n");
    out.push_str("}\n\n");
    out.push_str(
        "/** Construct a client bound to the graph's prepared operations and dynamic GQL. */\n",
    );
    out.push_str(
        "export async function createPreparedGleaphClient(options: GleaphTransportOptions): Promise<PreparedGleaphClient> {\n",
    );
    out.push_str("  return withPreparedQueries(await createGleaphClient(options));\n");
    out.push_str("}\n\n");
    out.push_str("/** Construct a prepared client over an existing SDK transport. */\n");
    out.push_str(
        "export function createPreparedGleaphClientFromTransport(transport: GleaphTransport): PreparedGleaphClient {\n",
    );
    out.push_str("  return withPreparedQueries(createGleaphClientFromTransport(transport));\n");
    out.push_str("}\n");
    Ok(out)
}

/// Tracks which SDK type imports the generated bindings need.
#[derive(Default)]
struct TypeUses {
    decimal: bool,
    float16: bool,
    float128: bool,
    float256: bool,
    zoned_time: bool,
    temporal: bool,
    path: bool,
    principal: bool,
}

fn collect_type_uses(semantic_type: &SemanticType, uses: &mut TypeUses, row: bool) {
    match semantic_type {
        SemanticType::Decimal => uses.decimal = true,
        SemanticType::Float16 => uses.float16 = true,
        SemanticType::Float128 => uses.float128 = true,
        SemanticType::Float256 => uses.float256 = true,
        SemanticType::ZonedTime => uses.zoned_time = true,
        SemanticType::Date
        | SemanticType::Time
        | SemanticType::LocalTime
        | SemanticType::DateTime
        | SemanticType::LocalDateTime
        | SemanticType::ZonedDateTime
        | SemanticType::Duration => uses.temporal = true,
        SemanticType::Path => uses.path = true,
        SemanticType::Principal => {
            if row {
                uses.principal = true;
            }
        }
        SemanticType::List { element } => collect_type_uses(element, uses, row),
        SemanticType::Record { fields } => {
            for field in fields {
                collect_type_uses(&field.semantic_type, uses, row);
            }
        }
        _ => {}
    }
}

fn validate_runtime_features(ir: &CodegenIr) -> Result<(), ManifestError> {
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        if operation.supports_consistency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "read consistency options",
            });
        }
        if operation.supports_idempotency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "idempotent updates",
            });
        }
    }
    Ok(())
}

fn append_encoded_params(out: &mut String, operation: &crate::PreparedOperation, indent: &str) {
    for parameter in &operation.parameters {
        let key = json_string(&parameter.name);
        let value = encode_expression(&format!("params[{key}]"), &parameter.semantic_type);
        if parameter.required {
            out.push_str(&format!("{indent}encodedParams[{key}] = {value};\n"));
        } else {
            out.push_str(&format!(
                "{indent}if (params[{key}] !== undefined) encodedParams[{key}] = {value};\n"
            ));
        }
    }
}

fn ts_type(semantic_type: &SemanticType, nullable: bool, row: bool) -> String {
    let base = match semantic_type {
        SemanticType::Null => "null".to_string(),
        SemanticType::Bool => "boolean".to_string(),
        SemanticType::Int8
        | SemanticType::Int16
        | SemanticType::Int32
        | SemanticType::Uint8
        | SemanticType::Uint16
        | SemanticType::Uint32 => "number".to_string(),
        SemanticType::Int64
        | SemanticType::Uint64
        | SemanticType::Int128
        | SemanticType::Uint128
        | SemanticType::Int256
        | SemanticType::Uint256 => "bigint".to_string(),
        SemanticType::Decimal => "GqlDecimal".to_string(),
        SemanticType::Float16 => "GqlFloat16".to_string(),
        SemanticType::Float32 | SemanticType::Float64 => "number".to_string(),
        SemanticType::Float128 => "GqlFloat128".to_string(),
        SemanticType::Float256 => "GqlFloat256".to_string(),
        SemanticType::Date => "Temporal.PlainDate".to_string(),
        SemanticType::Time | SemanticType::LocalTime => "Temporal.PlainTime".to_string(),
        SemanticType::DateTime => "Temporal.Instant".to_string(),
        SemanticType::LocalDateTime => "Temporal.PlainDateTime".to_string(),
        SemanticType::ZonedDateTime => "Temporal.ZonedDateTime".to_string(),
        SemanticType::ZonedTime => "GqlZonedTime".to_string(),
        SemanticType::Duration => "Temporal.Duration".to_string(),
        SemanticType::Text => "string".to_string(),
        // Parameters accept a principal text or object; decoded rows always carry a real
        // `Principal` instance.
        SemanticType::Principal => {
            if row {
                "Principal".to_string()
            } else {
                "PrincipalLike".to_string()
            }
        }
        SemanticType::Bytes => "Uint8Array".to_string(),
        SemanticType::List { element } => {
            format!("Array<{}>", ts_type(element, false, row))
        }
        SemanticType::Path => "ApiPathElement[]".to_string(),
        SemanticType::Record { fields } => {
            let fields = fields
                .iter()
                .map(|field| {
                    format!(
                        "{}: {}",
                        ts_property(&field.name),
                        ts_type(&field.semantic_type, field.nullable, row)
                    )
                })
                .collect::<Vec<_>>()
                .join("; ");
            format!("{{ {fields} }}")
        }
    };
    if nullable {
        format!("{base} | null")
    } else {
        base
    }
}
