use crate::common::{encode_expression, json_string, pascal_case, ts_property};
use crate::{ManifestError, OperationKind, PreparedManifest, SemanticType};

/// Generate a TypeScript prepared adapter over the existing SDK GraphClient.
pub fn generate_typescript(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    manifest.validate()?;
    validate_runtime_features(manifest)?;
    let mut out = String::from("// Generated by gleaph-codegen. Do not edit.\n\n");
    out.push_str(
        "import type { ApiQueryResponse, ApiValue, GraphClient, PreparedSortSpec } from \"@gleaph/sdk\";\n",
    );
    out.push_str("import { fromApiValue } from \"@gleaph/sdk\";\n\n");
    out.push_str("export const GLEAPH_GRAPH_ID = ");
    out.push_str(&json_string(&manifest.graph.id));
    out.push_str(" as const;\n\n");
    out.push_str("type PreparedResponse<Row> = Omit<ApiQueryResponse, \"execution\"> & { execution: Omit<ApiQueryResponse[\"execution\"], \"rows\"> & { rows: Row[] } };\n\n");
    out.push_str("export type PrincipalLike = string | { toText(): string };\n\n");

    for operation in &manifest.operations {
        let base = pascal_case(&operation.name);
        out.push_str(&format!("export interface {base}Params {{\n"));
        for parameter in &operation.parameters {
            let optional = if parameter.required { "" } else { "?" };
            out.push_str(&format!(
                "  {}{}: {};\n",
                ts_property(&parameter.name),
                optional,
                ts_type(&parameter.semantic_type, parameter.nullable)
            ));
        }
        out.push_str("}\n\n");
        out.push_str(&format!("export interface {base}Row {{\n"));
        for column in &operation.result.columns {
            out.push_str(&format!(
                "  {}: {};\n",
                ts_property(&column.name),
                ts_type(&column.semantic_type, column.nullable)
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str("export interface PreparedQueries {\n");
    for operation in &manifest.operations {
        let params = format!("{}Params", pascal_case(&operation.name));
        let row = format!("{}Row", pascal_case(&operation.name));
        let optional = if operation.parameters.is_empty() {
            "?"
        } else {
            ""
        };
        let sort = if operation.allowed_sorts.is_empty() {
            ""
        } else {
            ", sort?: PreparedSortSpec[]"
        };
        out.push_str(&format!(
            "  {}: (params{}: {}{}) => Promise<PreparedResponse<{}>>;\n",
            ts_property(&operation.name),
            optional,
            params,
            sort,
            row
        ));
    }
    out.push_str("}\n\n");
    out.push_str(
        "export function withPreparedQueries(client: GraphClient): PreparedQueries {\n  return {\n",
    );
    for operation in &manifest.operations {
        let method = match operation.kind {
            OperationKind::Query => "executePrepared",
            OperationKind::Update => "executePreparedMutation",
        };
        let params = if operation.parameters.is_empty() {
            "params = {}"
        } else {
            "params"
        };
        let sort = if operation.allowed_sorts.is_empty() {
            ""
        } else {
            ", sort?: PreparedSortSpec[]"
        };
        out.push_str(&format!(
            "    {}: async ({params}{sort}) => {{\n",
            ts_property(&operation.name)
        ));
        out.push_str("      const encodedParams: Record<string, ApiValue> = {};\n");
        append_encoded_params(&mut out, operation);
        out.push_str(&format!(
            "      const response = await client.{method}({}, encodedParams{});\n",
            json_string(&operation.name),
            if operation.allowed_sorts.is_empty() {
                ""
            } else {
                ", sort"
            }
        ));
        out.push_str("      return { ...response, execution: { ...response.execution, rows: response.execution.rows.map((row) => ({\n");
        for column in &operation.result.columns {
            out.push_str(&format!(
                "        {}: fromApiValue(row[{}]) as {},\n",
                ts_property(&column.name),
                json_string(&column.name),
                ts_type(&column.semantic_type, column.nullable)
            ));
        }
        out.push_str("      })) } };\n    },\n");
    }
    out.push_str("  };\n}\n");
    Ok(out)
}

fn validate_runtime_features(manifest: &PreparedManifest) -> Result<(), ManifestError> {
    for operation in &manifest.operations {
        if operation.supports_consistency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "read consistency options",
            });
        }
        if operation.supports_idempotency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "idempotent updates",
            });
        }
    }
    Ok(())
}

fn append_encoded_params(out: &mut String, operation: &crate::PreparedOperation) {
    for parameter in &operation.parameters {
        let key = json_string(&parameter.name);
        let value = encode_expression(&format!("params[{key}]"), &parameter.semantic_type);
        if parameter.required {
            out.push_str(&format!("      encodedParams[{key}] = {value};\n"));
        } else {
            out.push_str(&format!(
                "      if (params[{key}] !== undefined) encodedParams[{key}] = {value};\n"
            ));
        }
    }
}

fn ts_type(semantic_type: &SemanticType, nullable: bool) -> String {
    let base = match semantic_type {
        SemanticType::Null => "null".to_string(),
        SemanticType::Bool => "boolean".to_string(),
        SemanticType::Int64
        | SemanticType::Uint64
        | SemanticType::Int128
        | SemanticType::Uint128 => "bigint | number".to_string(),
        SemanticType::Int256 | SemanticType::Uint256 | SemanticType::Decimal => {
            "string".to_string()
        }
        SemanticType::Float64 | SemanticType::Date => "number".to_string(),
        SemanticType::Time => "bigint | number".to_string(),
        SemanticType::Text => "string".to_string(),
        SemanticType::Principal => "PrincipalLike".to_string(),
        SemanticType::Bytes => "Uint8Array".to_string(),
        SemanticType::List { element } => format!("Array<{}>", ts_type(element, false)),
    };
    if nullable {
        format!("{base} | null")
    } else {
        base
    }
}
