//! Generated by gleaph-codegen. Do not edit.

#![allow(dead_code)]

use gleaph_cdk::GqlParams;
use gleaph_cdk::GqlValue;
use gleaph_cdk::candid::CandidType;
use gleaph_cdk::serde::de::DeserializeOwned;
use gleaph_cdk::serde::{Deserialize, Serialize};
use std::future::Future;
use std::pin::Pin;

pub const GLEAPH_GRAPH_ID: &str = "default";

/// Result returned by a canister-side prepared-query executor.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedCanisterResponse<Row> {
    /// Number of rows observed by the runtime.
    pub row_count: u64,
    /// Typed rows decoded by the runtime.
    pub rows: Vec<Row>,
}

/// Runtime boundary used by generated canister methods.
pub trait PreparedCanisterExecutor {
    /// Runtime-specific error type.
    type Error;

    /// Encode a generated parameter value for the Router wire contract.
    fn encode_params<T: Serialize>(&self, params: &T) -> Result<Vec<u8>, Self::Error>;

    /// Execute a prepared operation from logical GQL parameters.
    fn execute_gql<'a, Row>(
        &'a self,
        name: &'static str,
        params: GqlParams,
    ) -> PreparedCanisterFuture<'a, Row, Self::Error>
    where
        Row: DeserializeOwned + 'a;

    /// Execute a read-only prepared operation.
    fn execute_query<'a, Row>(
        &'a self,
        name: &'static str,
        params: Vec<u8>,
    ) -> PreparedCanisterFuture<'a, Row, Self::Error>
    where
        Row: DeserializeOwned + 'a;

    /// Execute a mutating prepared operation.
    fn execute_update<'a, Row>(
        &'a self,
        name: &'static str,
        params: Vec<u8>,
    ) -> PreparedCanisterFuture<'a, Row, Self::Error>
    where
        Row: DeserializeOwned + 'a;
}

/// Boxed future returned by a generated canister executor.
pub type PreparedCanisterFuture<'a, Row, Error> =
    Pin<Box<dyn Future<Output = Result<PreparedCanisterResponse<Row>, Error>> + 'a>>;

/// Date-time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedDateTime {
    pub seconds: i64,
    pub nanos: u32,
}

/// Zoned date-time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedZonedDateTime {
    pub seconds: i64,
    pub nanos: u32,
    pub offset_seconds: i32,
}

/// Zoned time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedZonedTime {
    pub nanos: u64,
    pub offset_seconds: i32,
}

/// Duration representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedDuration {
    pub months: i32,
    pub nanos: i64,
}

/// Path element representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub enum PreparedPathElement {
    Vertex(Vec<u8>),
    Edge(Vec<u8>),
}

/// Find users whose name starts with the given term.
/// Parameters for the prepared operation find-users.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct FindUsersParams {
    /// Name prefix to search for.
    /// Wire parameter term.
    #[serde(rename = "term")]
    pub term: String,
}

impl FindUsersParams {
    /// Convert typed parameters to ordered logical GQL parameters.
    pub fn into_gql_params(self) -> GqlParams {
        vec![("term".to_string(), GqlValue::Text(self.term))]
    }
}

/// One result row from the prepared operation find-users.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct FindUsersRow {
    /// Wire column user_name.
    #[serde(rename = "user_name")]
    pub user_name: String,
    /// Wire column user_id.
    #[serde(rename = "user_id")]
    pub user_id: u64,
}

impl gleaph_cdk::FromGqlRow for FindUsersRow {
    fn from_gql_row(mut row: gleaph_cdk::GqlRow) -> Result<Self, gleaph_cdk::GqlWireDecodeError> {
        let user_name = {
            let value = gleaph_cdk::take_gql_row_field(&mut row, "user_name")?;
            match value {
                GqlValue::Text(value) => value,
                _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch("Text")),
            }
        };
        let user_id = {
            let value = gleaph_cdk::take_gql_row_field(&mut row, "user_id")?;
            match value {
                GqlValue::Uint64(value) => value,
                _ => return Err(gleaph_cdk::GqlWireDecodeError::TypeMismatch("Uint64")),
            }
        };
        Ok(Self { user_name, user_id })
    }
}

/// Typed facade over a canister-side prepared-query executor.
pub struct PreparedCanisterQueries<'a, E: PreparedCanisterExecutor> {
    executor: &'a E,
}

impl<'a, E: PreparedCanisterExecutor> PreparedCanisterQueries<'a, E> {
    /// Bind generated operations to a runtime executor.
    pub fn new(executor: &'a E) -> Self {
        Self { executor }
    }

    /// Execute a prepared operation using the shared logical GQL value model.
    pub async fn execute_gql<Row>(
        &self,
        name: &'static str,
        params: GqlParams,
    ) -> Result<PreparedCanisterResponse<Row>, E::Error>
    where
        Row: DeserializeOwned,
    {
        self.executor.execute_gql::<Row>(name, params).await
    }

    /// Execute the prepared operation find-users.
    pub async fn find_users(
        &self,
        params: FindUsersParams,
    ) -> Result<PreparedCanisterResponse<FindUsersRow>, E::Error> {
        self.executor
            .execute_gql::<FindUsersRow>("find-users", params.into_gql_params())
            .await
    }
}
