//! Generated by gleaph-codegen. Do not edit.

#![allow(dead_code)]

use gleaph_cdk::GqlParams;
use gleaph_cdk::GqlValue;
use gleaph_cdk::candid::CandidType;
use gleaph_cdk::serde::{Deserialize, Serialize};
use std::future::Future;

pub const GLEAPH_GRAPH_ID: &str = "default";

/// Result returned by a prepared operation.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedResponse<Row> {
    /// Number of rows returned by the Router.
    pub row_count: u64,
    /// Typed rows decoded from the Router response.
    pub rows: Vec<Row>,
}

/// Date-time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedDateTime {
    pub seconds: i64,
    pub nanos: u32,
}

/// Zoned date-time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedZonedDateTime {
    pub seconds: i64,
    pub nanos: u32,
    pub offset_seconds: i32,
}

/// Zoned time representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedZonedTime {
    pub nanos: u64,
    pub offset_seconds: i32,
}

/// Duration representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedDuration {
    pub months: i32,
    pub nanos: i64,
}

/// Path element representation used by generated declarations.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub enum PreparedPathElement {
    Vertex(Vec<u8>),
    Edge(Vec<u8>),
}

/// Find users whose name starts with the given term.
/// Parameters for the prepared operation find-users.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct FindUsersParams {
    /// Name prefix to search for.
    /// Wire parameter term.
    #[serde(rename = "term")]
    pub term: String,
}

impl FindUsersParams {
    /// Convert typed parameters to ordered logical GQL parameters.
    pub fn into_gql_params(self) -> GqlParams {
        vec![("term".to_string(), GqlValue::Text(self.term))]
    }
}

/// One result row from the prepared operation find-users.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct FindUsersRow {
    /// Wire column user_name.
    #[serde(rename = "user_name")]
    pub user_name: String,
    /// Wire column user_id.
    #[serde(rename = "user_id")]
    pub user_id: u64,
}

/// Marker enabling generated prepared operations on `gleaph_cdk::GleaphClient<Prepared>`.
pub struct Prepared;

/// Prepared operations generated from the manifest, available on
/// `gleaph_cdk::GleaphClient<Prepared>`.
///
/// Import this trait to call prepared operations on a client created with
/// `gleaph_cdk::GleaphClient::with_prepared::<Prepared>`.
pub trait PreparedExt {
    /// Execute the prepared operation find-users.
    fn find_users(
        &self,
        params: FindUsersParams,
    ) -> impl Future<Output = Result<PreparedResponse<FindUsersRow>, gleaph_cdk::CallError>> + Send;
}

impl PreparedExt for gleaph_cdk::GleaphClient<Prepared> {
    async fn find_users(
        &self,
        params: FindUsersParams,
    ) -> Result<PreparedResponse<FindUsersRow>, gleaph_cdk::CallError> {
        let params = gleaph_cdk::encode_gql_params(params.into_gql_params()).map_err(|error| {
            gleaph_cdk::CallError::Decode {
                message: format!("failed to encode GQL params: {error:?}"),
            }
        })?;
        let result = self
            .prepared_query("find-users", params, None, gleaph_cdk::ReadMode::Eventual)
            .await?;
        Ok(PreparedResponse {
            row_count: result.row_count,
            rows: result
                .decode_serde_rows::<FindUsersRow>()?
                .unwrap_or_default(),
        })
    }
}
