/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppQueryRouteImport } from './routes/_app/query'
import { Route as AppPreparedIndexRouteImport } from './routes/_app/prepared/index'
import { Route as AppSettingsRolesRouteImport } from './routes/_app/settings/roles'
import { Route as AppPreparedIdRouteImport } from './routes/_app/prepared/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppQueryRoute = AppQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppRoute,
} as any)
const AppPreparedIndexRoute = AppPreparedIndexRouteImport.update({
  id: '/prepared/',
  path: '/prepared/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPreparedIdRoute = AppPreparedIdRouteImport.update({
  id: '/prepared/$id',
  path: '/prepared/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/query': typeof AppQueryRoute
  '/prepared/$id': typeof AppPreparedIdRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/prepared/': typeof AppPreparedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/query': typeof AppQueryRoute
  '/': typeof AppIndexRoute
  '/prepared/$id': typeof AppPreparedIdRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/prepared': typeof AppPreparedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/query': typeof AppQueryRoute
  '/_app/': typeof AppIndexRoute
  '/_app/prepared/$id': typeof AppPreparedIdRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/prepared/': typeof AppPreparedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/query'
    | '/prepared/$id'
    | '/settings/roles'
    | '/prepared/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/query'
    | '/'
    | '/prepared/$id'
    | '/settings/roles'
    | '/prepared'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/query'
    | '/_app/'
    | '/_app/prepared/$id'
    | '/_app/settings/roles'
    | '/_app/prepared/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/query': {
      id: '/_app/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AppQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prepared/': {
      id: '/_app/prepared/'
      path: '/prepared'
      fullPath: '/prepared/'
      preLoaderRoute: typeof AppPreparedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prepared/$id': {
      id: '/_app/prepared/$id'
      path: '/prepared/$id'
      fullPath: '/prepared/$id'
      preLoaderRoute: typeof AppPreparedIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppQueryRoute: typeof AppQueryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPreparedIdRoute: typeof AppPreparedIdRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppPreparedIndexRoute: typeof AppPreparedIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppQueryRoute: AppQueryRoute,
  AppIndexRoute: AppIndexRoute,
  AppPreparedIdRoute: AppPreparedIdRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppPreparedIndexRoute: AppPreparedIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
