//! Application-owned public read gateway for the social demo.
//!
//! Exposes exactly five fixed read-only scenarios. Each scenario maps internally to a
//! registered Router prepared query and is delegated to the configured Router canister as a
//! bounded-wait composite query. The Gateway principal is graph-visible so the Router can resolve
//! the prepared plan; no arbitrary GQL, query name, graph name, or client parameters are accepted.
//!
//! Semantic scenarios carry an internally generated, fixed query-vector parameter blob encoded
//! with the `gleaph-gql-ic` parameter wire format. The vector is loaded at init time from the
//! generated scenario JSON produced by `frontend/apps/social-demo/scripts/build-config.mjs`.

// The `include_str!` below declares a compile-time dependency on the generated scenario
// JSON. Cargo tracks `include_str!` inputs automatically, so the canister rebuilds when the
// frontend config changes without needing a separate `build.rs`.
#[allow(dead_code)]
const _: &str =
    include_str!("../../../frontend/apps/social-demo/src/data/scenarios.generated.json");

use candid::{CandidType, Deserialize, Principal};
use gleaph_cdk::call_prepared_query;
use gleaph_graph_kernel::federation::RouterError;
use gleaph_graph_kernel::plan_exec::GqlQueryResult;
use ic_cdk_macros::{init, post_upgrade, query};
use std::cell::RefCell;

/// Fixed public scenarios. The Gateway maps each variant to a single prepared-query name
/// registered by the deploy administrator; callers cannot supply GQL, names, graph names,
/// raw vectors, or parameters.
#[derive(CandidType, Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SocialDemoScenario {
    PublicTimeline,
    AliceHomeFeed,
    TopicPath,
    SemanticDiscovery,
    AliceSemanticFeed,
}

#[derive(CandidType, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GatewayInitArgs {
    pub router_canister: Principal,
}

/// Errors that originate in the Gateway boundary, distinct from errors returned by Router.
#[derive(CandidType, Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SocialDemoGatewayError {
    /// Router rejected the prepared query.
    Router(RouterError),
    /// Inter-canister call failed (rejected, timed out, or could not be decoded).
    CallFailed(String),
    /// Gateway has not been initialized with a Router principal.
    NotConfigured,
}

thread_local! {
    static ROUTER_CANISTER: RefCell<Option<Principal>> = const { RefCell::new(None) };
}

/// Fixed dimension of the deterministic Post embedding vectors used by the semantic scenarios.
pub const SEMANTIC_EMBEDDING_DIMS: u16 = 8;

/// Fixed embedding name shared by all canonical Post embeddings and the vector index.
pub const SEMANTIC_EMBEDDING_NAME: &str = "post_vec";

#[init]
fn init(args: GatewayInitArgs) {
    do_init(args);
}

#[post_upgrade]
fn post_upgrade(args: GatewayInitArgs) {
    do_init(args);
}

fn do_init(args: GatewayInitArgs) {
    validate_router_principal(args.router_canister).unwrap_or_else(|e| ic_cdk::trap(&e));
    ROUTER_CANISTER.with(|rc| *rc.borrow_mut() = Some(args.router_canister));
    let vectors = load_semantic_vectors();
    SEMANTIC_VECTORS.with(|v| *v.borrow_mut() = Some(vectors));
}

fn validate_router_principal(router_canister: Principal) -> Result<(), String> {
    if router_canister == Principal::anonymous() {
        return Err("router_canister must not be anonymous".to_string());
    }
    Ok(())
}

fn router_canister() -> Result<Principal, SocialDemoGatewayError> {
    ROUTER_CANISTER.with(|rc| rc.borrow().ok_or(SocialDemoGatewayError::NotConfigured))
}

/// Raw generated scenario JSON embedded at compile time. The path is relative to
/// `crates/social-demo-gateway/src/lib.rs` and points to the resource regenerated by
/// `pnpm -C frontend/apps/social-demo run build:config`.
const SEMANTIC_VECTORS_JSON: &str =
    include_str!("../../../frontend/apps/social-demo/src/data/scenarios.generated.json");

thread_local! {
    /// Per-scenario semantic query vectors parsed from the embedded JSON at init time.
    /// Index order matches the `SocialDemoScenario` discriminants for the two semantic variants.
    static SEMANTIC_VECTORS: RefCell<Option<Vec<Vec<f32>>>> = const { RefCell::new(None) };
}

/// Parse the embedded scenario JSON and extract the `semanticVector` arrays for the two
/// semantic scenarios. Non-semantic scenarios receive `None`.
fn load_semantic_vectors() -> Vec<Vec<f32>> {
    // The generated JSON schema has `{ "scenarios": [ { "id": "...", "semanticVector": [...]|null } ] }`.
    let manifest: serde_json::Value =
        serde_json::from_str(SEMANTIC_VECTORS_JSON).expect("embedded scenario JSON parses");
    let scenarios = manifest
        .get("scenarios")
        .and_then(|v| v.as_array())
        .expect("scenario JSON must contain a scenarios array");

    let lookup = |scenario_id: &str| -> Vec<f32> {
        scenarios
            .iter()
            .find(|s| s.get("id").and_then(|v| v.as_str()) == Some(scenario_id))
            .and_then(|s| s.get("semanticVector"))
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .map(|v| v.as_f64().expect("semanticVector entry must be a number") as f32)
                    .collect()
            })
            .unwrap_or_else(|| panic!("semantic vector missing for {scenario_id}"))
    };

    vec![lookup("SemanticDiscovery"), lookup("AliceSemanticFeed")]
}

/// Return the semantic query vector for a scenario, if any.
///
/// In production `do_init` populates the thread-local once at canister install time. In
/// unit-test contexts the thread-local may be uninitialized, so this helper lazily loads
/// the embedded JSON on first access. The embedded JSON is the same deterministic
/// resource, so the parsed vector is identical whether loaded eagerly by `do_init` or
/// lazily here.
fn semantic_query_vector_for(scenario: SocialDemoScenario) -> Option<Vec<f32>> {
    let index = match scenario {
        SocialDemoScenario::SemanticDiscovery => 0,
        SocialDemoScenario::AliceSemanticFeed => 1,
        _ => return None,
    };
    SEMANTIC_VECTORS.with(|v| {
        if v.borrow().is_none() {
            *v.borrow_mut() = Some(load_semantic_vectors());
        }
        v.borrow().as_ref().map(|vecs| vecs[index].clone())
    })
}

/// Encode a per-scenario semantic query vector as a compact-binary GQL parameter blob.
fn encode_semantic_query_params_for(scenario: SocialDemoScenario) -> Vec<u8> {
    let vector = semantic_query_vector_for(scenario).expect("scenario has a semantic vector");
    let bytes: Vec<u8> = vector
        .into_iter()
        .flat_map(|v| v.to_le_bytes().to_vec())
        .collect();
    gleaph_gql_ic::encode_gql_params_blob(vec![(
        "query".to_string(),
        gleaph_gql::Value::Bytes(bytes),
    )])
    .expect("semantic query vector encodes")
}

/// Internal mapping from scenario to prepared-query name and parameter blob.
fn scenario_to_request(scenario: SocialDemoScenario) -> (&'static str, Vec<u8>) {
    match scenario {
        SocialDemoScenario::PublicTimeline => ("public_timeline", Vec::new()),
        SocialDemoScenario::AliceHomeFeed => ("alice_home_feed", Vec::new()),
        SocialDemoScenario::TopicPath => ("topic_path_explanation", Vec::new()),
        SocialDemoScenario::SemanticDiscovery => (
            "semantic_discovery",
            encode_semantic_query_params_for(SocialDemoScenario::SemanticDiscovery),
        ),
        SocialDemoScenario::AliceSemanticFeed => (
            "alice_semantic_feed",
            encode_semantic_query_params_for(SocialDemoScenario::AliceSemanticFeed),
        ),
    }
}

/// Public composite query: execute one fixed social-demo scenario through the configured Router.
#[query(composite = true)]
async fn execute_social_demo_scenario(
    scenario: SocialDemoScenario,
) -> Result<GqlQueryResult, SocialDemoGatewayError> {
    let router = router_canister()?;
    let (name, params) = scenario_to_request(scenario);

    let router_result: Result<GqlQueryResult, RouterError> =
        call_prepared_query(router, name, params)
            .await
            .map_err(|e| SocialDemoGatewayError::CallFailed(e.to_string()))?;
    router_result.map_err(SocialDemoGatewayError::Router)
}

ic_cdk::export_candid!();

#[cfg(test)]
mod tests {
    use super::*;

    fn reset_config() {
        ROUTER_CANISTER.with(|rc| *rc.borrow_mut() = None);
    }

    #[test]
    fn scenario_names_match_expected_prepared_queries() {
        assert_eq!(
            scenario_to_request(SocialDemoScenario::PublicTimeline).0,
            "public_timeline"
        );
        assert_eq!(
            scenario_to_request(SocialDemoScenario::AliceHomeFeed).0,
            "alice_home_feed"
        );
        assert_eq!(
            scenario_to_request(SocialDemoScenario::TopicPath).0,
            "topic_path_explanation"
        );
        assert_eq!(
            scenario_to_request(SocialDemoScenario::SemanticDiscovery).0,
            "semantic_discovery"
        );
        assert_eq!(
            scenario_to_request(SocialDemoScenario::AliceSemanticFeed).0,
            "alice_semantic_feed"
        );
    }

    #[test]
    fn semantic_query_params_decode_to_fixed_vector() {
        let (_, params) = scenario_to_request(SocialDemoScenario::SemanticDiscovery);
        let decoded = gleaph_gql_ic::decode_gql_params_blob(&params).expect("decode params");
        assert_eq!(decoded.len(), 1);
        let query = match decoded.get("query").expect("query parameter") {
            gleaph_gql::Value::Bytes(b) => b.clone(),
            other => panic!("expected Bytes query parameter, got {other:?}"),
        };
        assert_eq!(query.len(), SEMANTIC_EMBEDDING_DIMS as usize * 4);
        let values: Vec<f32> = query
            .chunks_exact(4)
            .map(|chunk| f32::from_le_bytes(chunk.try_into().expect("4 bytes")))
            .collect();
        assert_eq!(
            values,
            semantic_query_vector_for(SocialDemoScenario::SemanticDiscovery)
                .expect("discovery vector")
        );

        let (_, alice_params) = scenario_to_request(SocialDemoScenario::AliceSemanticFeed);
        assert_eq!(
            alice_params, params,
            "both semantic scenarios share the fixed query vector"
        );
    }

    #[test]
    fn validate_router_principal_rejects_anonymous() {
        assert_eq!(
            validate_router_principal(Principal::anonymous()),
            Err("router_canister must not be anonymous".to_string())
        );
    }

    #[test]
    fn validate_router_principal_accepts_non_anonymous() {
        let principal = Principal::from_slice(&[0xAB; 29]);
        assert_eq!(validate_router_principal(principal), Ok(()));
    }

    #[test]
    fn router_canister_fails_when_uninitialized() {
        reset_config();
        assert_eq!(
            router_canister(),
            Err(SocialDemoGatewayError::NotConfigured)
        );
    }

    #[test]
    fn init_stores_router_canister() {
        reset_config();
        let principal = Principal::from_slice(&[0xCD; 29]);
        init(GatewayInitArgs {
            router_canister: principal,
        });
        assert_eq!(router_canister(), Ok(principal));
    }
}
