[package]
name = "gleaph-account"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid = { workspace = true }
gleaph-graph-kernel = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-stable-memory-backend = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { workspace = true }
sha2 = "0.11"
thiserror = { workspace = true }

[dev-dependencies]
candid_parser = "0.4.0"
futures = "0.3"
