// Generated by frontend/apps/social-demo/scripts/build-config.mjs.
// Do not edit manually; change the YAML files under config/ and rerun the build.

import { SocialDemoScenario } from "~/generated/social_demo_gateway";

export const DEMO_ID_MAP: Record<string, bigint> = {
  "alice": 1n,
  "bob": 2n,
  "carol": 3n,
  "dave": 4n,
  "eve": 5n,
  "fiona": 6n,
  "george": 7n,
  "hana": 8n,
  "ian": 9n,
  "jules": 10n,
  "kira": 11n,
  "community-ic": 12n,
  "topic-graph": 13n,
  "topic-ic": 14n,
  "p_527ca1ee79b9dbe7cbe5": 15n,
  "p_d373f0f6c736c9b01eb3": 16n,
  "p_384b3fd3ef400d8f0997": 17n,
  "p_23e7b97d27b0432b56b7": 18n,
  "p_e7de9e807a5d38801adb": 19n,
  "p_7ee887afb8bd964fec00": 20n,
  "p_20fa73e4909aa56c8d1a": 21n,
  "p_908ff6eeb14cf509302a": 22n,
  "p_38f48fa92d37e88da97f": 23n,
  "p_7264349104bc7d26aef1": 24n,
  "p_9ba8c08932c3519c5c79": 25n,
  "p_8d35f0923adfcd762381": 26n,
  "p_33b218fd6e3c6dc87557": 27n,
  "p_33c5c9e02a6ec9d0277c": 28n,
  "p_b36194e3f8d0b0c4b209": 29n,
  "p_835dec60e898af443b3f": 30n,
  "p_813e48aa7cba92c18c80": 31n,
  "p_d837758c2032acdb19a0": 32n,
  "p_e64442f3158619339629": 33n,
  "p_5af2ceebecccc91529dc": 34n,
  "p_4ee40311214ecc674271": 35n,
  "p_3e48614ec19943b3953e": 36n,
  "p_ecb01d5d5c87aae5e75c": 37n,
  "p_0a16972aa298f4fb5c75": 38n,
  "p_e8d507b0783f3cc277fd": 39n,
  "public-feed": 40n
};


export const SOCIAL_DEMO_SCENARIO_IDS = ["PublicTimeline", "AliceHomeFeed", "TopicPath", "SemanticDiscovery", "AliceSemanticFeed"] as const;

export type ScenarioId = (typeof SOCIAL_DEMO_SCENARIO_IDS)[number];

export type ScenarioDefinition = {
  id: ScenarioId;
  preparedQueryId: string;
  label: string;
  shortLabel: string;
  feedTitle: string;
  explanationTitle: string;
  rdbSummary: string;
  graphSummary: string;
  preparedQuery: string;
  semanticVector: number[] | null;
  scenario: SocialDemoScenario;
};

export const SCENARIO_DEFINITIONS: Record<ScenarioId, ScenarioDefinition> = {
  PublicTimeline: {
    id: "PublicTimeline",
    preparedQueryId: "public_timeline",
    label: "Public timeline",
    shortLabel: "Timeline",
    feedTitle: "Public posts",
    explanationTitle: "Relational baseline",
    rdbSummary: "A chronological list of public rows is exactly what an RDB does well: one index on created_at, a simple visibility predicate, and no joins.",
    graphSummary: "The graph materializes `IN_PUBLIC_FEED` edges from every public Post to a dedicated Feed vertex at seed time. Gleaph's labeled-edge insertion order is exposed explicitly through `GLEAPH.SEQUENCE(e)`, so a single fixed-label expansion with `LIMIT` returns newest-first without depending on undocumented default scan order. The value is not speed; it is that the same vertex model will later power relationship-aware feeds without a new schema.",
    preparedQuery: "MATCH (feed:Feed {demo_id: 40})<-[e:IN_PUBLIC_FEED]-(p:Post)<-[:POSTED]-(author:User) OPTIONAL MATCH (p)-[:REPLY_TO]->(parent:Post) RETURN p.demo_id AS post_id, parent.demo_id AS parent_post_id, author.name AS author_name, p.body AS body, p.created_at AS created_at ORDER BY GLEAPH.SEQUENCE(e) DESC LIMIT 20",
    semanticVector: null,
    scenario: SocialDemoScenario.PublicTimeline,
  },
  AliceHomeFeed: {
    id: "AliceHomeFeed",
    preparedQueryId: "alice_home_feed",
    label: "Alice home feed",
    shortLabel: "Home",
    feedTitle: "Alice's home feed",
    explanationTitle: "Graph traversal",
    rdbSummary: "An RDB needs a follows join table and a two-hop join (follower → followee → posts). The query is still SQL-shaped, but the relationship is now a traversal, not a foreign-key lookup.",
    graphSummary: "Gleaph materializes `IN_HOME_FEED` edges from every public Post to its author and each follower User at seed time, so Alice's feed is a single bounded expansion from her user vertex and includes her own posts. The feed is ordered explicitly with `GLEAPH.SEQUENCE(e)` on the labeled feed edge, returning newest posts first with a deterministic, declared sort key rather than an implicit scan assumption.",
    preparedQuery: "MATCH (u:User {demo_id: 1})<-[e:IN_HOME_FEED]-(p:Post)<-[:POSTED]-(author:User) WHERE p.is_public = TRUE OPTIONAL MATCH (p)-[:REPLY_TO]->(parent:Post) RETURN p.demo_id AS post_id, parent.demo_id AS parent_post_id, author.name AS author_name, p.body AS body, p.created_at AS created_at ORDER BY GLEAPH.SEQUENCE(e) DESC LIMIT 20",
    semanticVector: null,
    scenario: SocialDemoScenario.AliceHomeFeed,
  },
  TopicPath: {
    id: "TopicPath",
    preparedQueryId: "topic_path_explanation",
    label: "Topic path",
    shortLabel: "Topic",
    feedTitle: "Topic explanation path",
    explanationTitle: "Explainable recommendation",
    rdbSummary: "Proving why a post was recommended requires re-running and documenting the joins: follow, post, topic. The answer is scattered across tables.",
    graphSummary: "Gleaph returns the same result plus the edge identities that caused it: Alice follows Bob, Bob authored the post, and that post has the Graph databases topic. The path is part of the query result.",
    preparedQuery: "MATCH (p:Post)-[has_topic:HAS_TOPIC]->(t:Topic) WHERE t.demo_id = 13 MATCH (u:User)-[follows:FOLLOWS]->(author:User)-[posted:POSTED]->(p) WHERE u.demo_id = 1 RETURN p.demo_id AS post_id, author.name AS author_name, t.demo_id AS topic_id, p.body AS body, p.created_at AS created_at",
    semanticVector: null,
    scenario: SocialDemoScenario.TopicPath,
  },
  SemanticDiscovery: {
    id: "SemanticDiscovery",
    preparedQueryId: "semantic_discovery",
    label: "Semantic discovery",
    shortLabel: "Semantic",
    feedTitle: "Vector-only semantic discovery",
    explanationTitle: "Vector retrieval",
    rdbSummary: "Pure vector search has no join table: it scores every public Post against a fixed query vector and returns the nearest neighbors by L2-squared distance.",
    graphSummary: "Gleaph stores canonical Post embeddings on the Graph shard and routes vector SEARCH through the derived index. Dave's retrieval note is deliberately nearest even though Alice does not follow Dave.",
    preparedQuery: "MATCH (p:Post)<-[:POSTED]-(author:User) WHERE p.is_public = TRUE SEARCH p IN (VECTOR INDEX post_vec FOR $query LIMIT 10) DISTANCE AS distance RETURN p.demo_id AS post_id, author.name AS author_name, p.body AS body, distance ORDER BY distance ASC",
    semanticVector: [8,0,0,0,0,0,0,0],
    scenario: SocialDemoScenario.SemanticDiscovery,
  },
  AliceSemanticFeed: {
    id: "AliceSemanticFeed",
    preparedQueryId: "alice_semantic_feed",
    label: "Alice semantic feed",
    shortLabel: "Semantic+Graph",
    feedTitle: "Alice's graph-constrained semantic feed",
    explanationTitle: "Hybrid retrieval",
    rdbSummary: "Combining vector similarity with a relational filter requires joining the vector result set back to followee authorship, usually in application code.",
    graphSummary: "Gleaph applies the same vector SEARCH inside the graph pattern `Alice → FOLLOWS → author → POSTED → Post`. Dave's nearer post is excluded because he is not a followee; posts from Alice's followed authors are returned in semantic order.",
    preparedQuery: "MATCH (u:User)-[:FOLLOWS]->(author:User)-[:POSTED]->(p:Post) WHERE u.demo_id = 1 AND p.is_public = TRUE SEARCH p IN (VECTOR INDEX post_vec FOR $query LIMIT 10) DISTANCE AS distance RETURN p.demo_id AS post_id, author.name AS author_name, p.body AS body, distance ORDER BY distance ASC",
    semanticVector: [8,0,0,0,0,0,0,0],
    scenario: SocialDemoScenario.AliceSemanticFeed,
  },
};

export const displayPostId = (postId: bigint): string => postId.toString();

export const scenarioDefinitionById = (id: ScenarioId): ScenarioDefinition => {
  const definition = SCENARIO_DEFINITIONS[id];
  if (!definition) {
    throw new Error(`Unknown social demo scenario: ${id}`);
  }
  return definition;
};
