// Generated by frontend/apps/social-demo/scripts/build-config.mjs.
// Do not edit manually; change the YAML files under config/ and rerun the build.

import { SocialDemoScenario } from "~/generated/social_demo_gateway";

export const DEMO_ID_MAP: Record<string, bigint> = {
  "alice": 1n,
  "bob": 2n,
  "carol": 3n,
  "dave": 4n,
  "eve": 5n,
  "fiona": 6n,
  "george": 7n,
  "hana": 8n,
  "ian": 9n,
  "jules": 10n,
  "kira": 11n,
  "community-ic": 12n,
  "topic-graph": 13n,
  "topic-ic": 14n,
  "p_527ca1ee79b9dbe7cbe5": 15n,
  "p_d373f0f6c736c9b01eb3": 16n,
  "p_384b3fd3ef400d8f0997": 17n,
  "p_23e7b97d27b0432b56b7": 18n,
  "p_e7de9e807a5d38801adb": 19n,
  "p_7ee887afb8bd964fec00": 20n,
  "p_20fa73e4909aa56c8d1a": 21n,
  "p_908ff6eeb14cf509302a": 22n,
  "p_38f48fa92d37e88da97f": 23n,
  "p_7264349104bc7d26aef1": 24n,
  "p_9ba8c08932c3519c5c79": 25n,
  "p_8d35f0923adfcd762381": 26n,
  "p_33b218fd6e3c6dc87557": 27n,
  "p_33c5c9e02a6ec9d0277c": 28n,
  "p_b36194e3f8d0b0c4b209": 29n,
  "p_835dec60e898af443b3f": 30n,
  "p_813e48aa7cba92c18c80": 31n,
  "p_d837758c2032acdb19a0": 32n,
  "p_e64442f3158619339629": 33n,
  "p_5af2ceebecccc91529dc": 34n,
  "p_4ee40311214ecc674271": 35n,
  "p_3e48614ec19943b3953e": 36n,
  "p_ecb01d5d5c87aae5e75c": 37n,
  "p_0a16972aa298f4fb5c75": 38n,
  "p_e8d507b0783f3cc277fd": 39n,
  "public-feed": 40n
};


export const SOCIAL_DEMO_SCENARIO_IDS = ["PublicTimeline", "AliceHomeFeed", "TopicPath", "SemanticDiscovery", "AliceSemanticFeed"] as const;

export type ScenarioId = (typeof SOCIAL_DEMO_SCENARIO_IDS)[number];

export type ScenarioDefinition = {
  id: ScenarioId;
  preparedQueryId: string;
  label: string;
  shortLabel: string;
  feedTitle: string;
  rdbSummary: string;
  graphSummary: string;
  preparedQuery: string;
  semanticVector: number[] | null;
  scenario: SocialDemoScenario;
};

export const SCENARIO_DEFINITIONS: Record<ScenarioId, ScenarioDefinition> = {
  PublicTimeline: {
    id: "PublicTimeline",
    preparedQueryId: "public_timeline",
    label: "Public timeline",
    shortLabel: "Timeline",
    feedTitle: "Public posts",
    rdbSummary: "This is the straightforward RDB case: index public posts by created_at, apply the visibility condition, and read the newest rows. There is no meaningful relational advantage to demonstrate here; the important baseline is a simple, well-indexed table query.",
    graphSummary: "Gleaph materializes `IN_PUBLIC_FEED` edges from each public Post to a Feed vertex, then reads one fixed-label edge stream. This is not presented as faster than the RDB baseline; it shows that the same Post/User/edge model can extend from a public timeline to relationship-aware feeds without introducing a separate feed schema.",
    preparedQuery: "MATCH (feed:Feed {demo_id: 40})<-[e:IN_PUBLIC_FEED]-(p:Post)<-[:POSTED]-(author:User) OPTIONAL MATCH (p)-[:REPLY_TO]->(parent:Post) RETURN p.demo_id AS post_id, parent.demo_id AS parent_post_id, author.name AS author_name, p.body AS body, p.created_at AS created_at ORDER BY GLEAPH.SEQUENCE(e) DESC LIMIT 20",
    semanticVector: null,
    scenario: SocialDemoScenario.PublicTimeline,
  },
  AliceHomeFeed: {
    id: "AliceHomeFeed",
    preparedQueryId: "alice_home_feed",
    label: "Alice home feed",
    shortLabel: "Home",
    feedTitle: "Alice's home feed",
    rdbSummary: "At small scale, an RDB can build Alice's feed on read: first get the followee IDs from follows, then fetch their public posts from tweets (a join or subquery). Twitter-like systems often avoid repeating that work for every read by using fan-out on write: copy each new post into followers' home-feed inboxes. At larger scale, a hybrid is common—push ordinary accounts and pull or merge posts from celebrity accounts.",
    graphSummary: "Gleaph's social-demo uses fan-out on write: when the seed is built, each public Post creates an `IN_HOME_FEED` edge to its author and every follower User. Alice then reads those pre-materialized edges with one bounded expansion, including her own posts. This shifts work from feed reads to post ingestion; a production system can combine it with pull/merge for accounts with very large audiences.",
    preparedQuery: "MATCH (u:User {demo_id: 1})<-[e:IN_HOME_FEED]-(p:Post)<-[:POSTED]-(author:User) WHERE p.is_public = TRUE OPTIONAL MATCH (p)-[:REPLY_TO]->(parent:Post) RETURN p.demo_id AS post_id, parent.demo_id AS parent_post_id, author.name AS author_name, p.body AS body, p.created_at AS created_at ORDER BY GLEAPH.SEQUENCE(e) DESC LIMIT 20",
    semanticVector: null,
    scenario: SocialDemoScenario.AliceHomeFeed,
  },
  TopicPath: {
    id: "TopicPath",
    preparedQueryId: "topic_path_explanation",
    label: "Topic path",
    shortLabel: "Topic",
    feedTitle: "Topic explanation path",
    rdbSummary: "An RDB can answer this with joins across follows, posts, and topics. The extra work is explaining the result: the application must select and preserve the matching follow, authorship, and topic rows as recommendation evidence instead of returning only the post.",
    graphSummary: "The graph pattern describes the reason directly: Alice follows Bob, Bob authored the post, and the post has the selected topic. Gleaph returns the matching edge identities alongside the post, so the relationship path is part of the result rather than an explanation reconstructed afterward.",
    preparedQuery: "MATCH (p:Post)-[has_topic:HAS_TOPIC]->(t:Topic) WHERE t.demo_id = 13 MATCH (u:User)-[follows:FOLLOWS]->(author:User)-[posted:POSTED]->(p) WHERE u.demo_id = 1 RETURN p.demo_id AS post_id, author.name AS author_name, t.demo_id AS topic_id, p.body AS body, p.created_at AS created_at, ELEMENT_ID(follows) AS follows_edge_id, ELEMENT_ID(posted) AS posted_edge_id, ELEMENT_ID(has_topic) AS topic_edge_id",
    semanticVector: null,
    scenario: SocialDemoScenario.TopicPath,
  },
  SemanticDiscovery: {
    id: "SemanticDiscovery",
    preparedQueryId: "semantic_discovery",
    label: "Semantic discovery",
    shortLabel: "Semantic",
    feedTitle: "Vector-only semantic discovery",
    rdbSummary: "An RDB with a vector extension can also run this query: search the Post embedding index, filter public posts, and return the nearest neighbors. The key capability here is vector indexing, not a relational join; a separate vector service is another common implementation.",
    graphSummary: "Gleaph keeps the canonical Post embeddings with the graph data and routes `SEARCH` through its derived vector index. This scenario intentionally has no relationship constraint, so Dave's note appears because it is the nearest public Post—not because the graph has inferred a social connection.",
    preparedQuery: "MATCH (p:Post)<-[:POSTED]-(author:User) WHERE p.is_public = TRUE SEARCH p IN (VECTOR INDEX post_vec FOR $query LIMIT 10) DISTANCE AS distance RETURN p.demo_id AS post_id, author.name AS author_name, p.body AS body, distance ORDER BY distance ASC",
    semanticVector: [8,0,0,0,0,0,0,0],
    scenario: SocialDemoScenario.SemanticDiscovery,
  },
  AliceSemanticFeed: {
    id: "AliceSemanticFeed",
    preparedQueryId: "alice_semantic_feed",
    label: "Alice semantic feed",
    shortLabel: "Semantic+Graph",
    feedTitle: "Alice's graph-constrained semantic feed",
    rdbSummary: "A relational implementation must combine two concerns: find posts by vector distance and restrict them to Alice's followees. It can join or pre-filter in the database, but if vector search returns only a small top-k candidate set, filtering afterward can miss eligible posts; over-fetching or filter-aware vector search is needed.",
    graphSummary: "Gleaph expresses eligibility and ranking in one query: `Alice → FOLLOWS → author → POSTED → Post` plus vector `SEARCH`. Dave's nearer post is excluded because he is not a followee, while eligible posts are ranked by semantic distance. The point is composable relationship filtering, not that graphs replace vector indexes.",
    preparedQuery: "MATCH (u:User)-[:FOLLOWS]->(author:User)-[:POSTED]->(p:Post) WHERE u.demo_id = 1 AND p.is_public = TRUE SEARCH p IN (VECTOR INDEX post_vec FOR $query LIMIT 10) DISTANCE AS distance RETURN p.demo_id AS post_id, author.name AS author_name, p.body AS body, distance ORDER BY distance ASC",
    semanticVector: [8,0,0,0,0,0,0,0],
    scenario: SocialDemoScenario.AliceSemanticFeed,
  },
};

export const displayPostId = (postId: bigint): string => postId.toString();

export const scenarioDefinitionById = (id: ScenarioId): ScenarioDefinition => {
  const definition = SCENARIO_DEFINITIONS[id];
  if (!definition) {
    throw new Error(`Unknown social demo scenario: ${id}`);
  }
  return definition;
};
