// Generated by frontend/apps/social-demo/scripts/build-config.mjs.
// Do not edit manually; change the YAML files under config/ and rerun the build.

export const USER_AVATARS: Record<string, string> = {
  "あかり": "/avatars/akari.svg",
  "Alice": "/avatars/alice.svg",
  "Bob": "/avatars/bob.svg",
  "Carol": "/avatars/carol.svg",
  "Dave": "/avatars/dave.svg",
  "えみ": "/avatars/emi.svg",
  "Eve": "/avatars/eve.svg",
  "Fiona": "/avatars/fiona.svg",
  "George": "/avatars/george.svg",
  "Hana": "/avatars/hana.svg",
  "はる": "/avatars/haru.svg",
  "Ian": "/avatars/ian.svg",
  "Jules": "/avatars/jules.svg",
  "Kira": "/avatars/kira.svg",
  "こうじ": "/avatars/koji.svg",
  "Liam": "/avatars/liam.svg",
  "Maya": "/avatars/maya.svg",
  "めい": "/avatars/mei.svg",
  "なな": "/avatars/nana.svg",
  "Noah": "/avatars/noah.svg",
  "Olivia": "/avatars/olivia.svg",
  "Paul": "/avatars/paul.svg",
  "Quinn": "/avatars/quinn.svg",
  "蓮": "/avatars/ren.svg",
  "りく": "/avatars/riku.svg",
  "そら": "/avatars/sora.svg",
  "匠": "/avatars/takumi.svg",
  "ゆい": "/avatars/yui.svg"
};
