// Generated by gleaph-codegen. Do not edit.

import type { ApiValue, GleaphClient, GleaphTransport, GleaphTransportOptions, GqlQueryResult, PreparedManifestColumn, Temporal } from "@gleaph/sdk";
import { GleaphClientWrapper, createGleaphClient, createGleaphClientFromTransport, toApiValue, decodeRows } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "social" as const;

type PreparedResponse<Row> = Omit<GqlQueryResult, "rows"> & { rows: Row[] };

export type PrincipalLike = string | { toText(): string };

/**
 * Alice home feed: fan-out IN_HOME_FEED edges for Alice's followees.
 */
export interface AliceHomeFeedParams {
  /**
   * Page offset (Int64, encoded by the Gateway).
   */
  offset: bigint;
}

export interface AliceHomeFeedRow {
  post_id: bigint;
  parent_post_id: bigint | null;
  parent_author_name: string | null;
  parent_body: string | null;
  parent_created_at: Temporal.Instant | null;
  author_name: string;
  body: string;
  created_at: Temporal.Instant;
}

const ALICE_HOME_FEED_COLUMNS: PreparedManifestColumn[] = [{ name: "post_id", semantic_type: "Int64", nullable: false }, { name: "parent_post_id", semantic_type: "Int64", nullable: true }, { name: "parent_author_name", semantic_type: "Text", nullable: true }, { name: "parent_body", semantic_type: "Text", nullable: true }, { name: "parent_created_at", semantic_type: "DateTime", nullable: true }, { name: "author_name", semantic_type: "Text", nullable: false }, { name: "body", semantic_type: "Text", nullable: false }, { name: "created_at", semantic_type: "DateTime", nullable: false }];

/**
 * Alice semantic feed: graph-constrained SEARCH over Alice's followees.
 */
export interface AliceSemanticFeedParams {
  /**
   * Page offset (Int64, encoded by the Gateway).
   */
  offset: bigint;
  /**
   * Query vector (Bytes, encoded by the Gateway).
   */
  query: Uint8Array;
}

export interface AliceSemanticFeedRow {
  post_id: bigint;
  author_name: string;
  body: string;
  distance: number | null;
}

const ALICE_SEMANTIC_FEED_COLUMNS: PreparedManifestColumn[] = [{ name: "post_id", semantic_type: "Int64", nullable: false }, { name: "author_name", semantic_type: "Text", nullable: false }, { name: "body", semantic_type: "Text", nullable: false }, { name: "distance", semantic_type: "Float64", nullable: true }];

/**
 * Public timeline: materialized IN_PUBLIC_FEED edges in insertion order.
 */
export interface PublicTimelineParams {
  /**
   * Page offset (Int64, encoded by the Gateway).
   */
  offset: bigint;
}

export interface PublicTimelineRow {
  post_id: bigint;
  parent_post_id: bigint | null;
  parent_author_name: string | null;
  parent_body: string | null;
  parent_created_at: Temporal.Instant | null;
  author_name: string;
  body: string;
  created_at: Temporal.Instant;
}

const PUBLIC_TIMELINE_COLUMNS: PreparedManifestColumn[] = [{ name: "post_id", semantic_type: "Int64", nullable: false }, { name: "parent_post_id", semantic_type: "Int64", nullable: true }, { name: "parent_author_name", semantic_type: "Text", nullable: true }, { name: "parent_body", semantic_type: "Text", nullable: true }, { name: "parent_created_at", semantic_type: "DateTime", nullable: true }, { name: "author_name", semantic_type: "Text", nullable: false }, { name: "body", semantic_type: "Text", nullable: false }, { name: "created_at", semantic_type: "DateTime", nullable: false }];

/**
 * Semantic discovery: vector-only SEARCH over public posts.
 */
export interface SemanticDiscoveryParams {
  /**
   * Page offset (Int64, encoded by the Gateway).
   */
  offset: bigint;
  /**
   * Query vector (Bytes, encoded by the Gateway).
   */
  query: Uint8Array;
}

export interface SemanticDiscoveryRow {
  post_id: bigint;
  author_name: string;
  body: string;
  distance: number | null;
}

const SEMANTIC_DISCOVERY_COLUMNS: PreparedManifestColumn[] = [{ name: "post_id", semantic_type: "Int64", nullable: false }, { name: "author_name", semantic_type: "Text", nullable: false }, { name: "body", semantic_type: "Text", nullable: false }, { name: "distance", semantic_type: "Float64", nullable: true }];

/**
 * Topic path: four-edge relationship trail with edge identities.
 */
export interface TopicPathExplanationParams {
  /**
   * Page offset (Int64, encoded by the Gateway).
   */
  offset: bigint;
}

export interface TopicPathExplanationRow {
  post_id: bigint;
  author_name: string;
  topic_id: bigint;
  body: string;
  created_at: Temporal.Instant;
  follows_edge_id: Uint8Array;
  second_follows_edge_id: Uint8Array;
  posted_edge_id: Uint8Array;
  topic_edge_id: Uint8Array;
}

const TOPIC_PATH_EXPLANATION_COLUMNS: PreparedManifestColumn[] = [{ name: "post_id", semantic_type: "Int64", nullable: false }, { name: "author_name", semantic_type: "Text", nullable: false }, { name: "topic_id", semantic_type: "Int64", nullable: false }, { name: "body", semantic_type: "Text", nullable: false }, { name: "created_at", semantic_type: "DateTime", nullable: false }, { name: "follows_edge_id", semantic_type: "Bytes", nullable: false }, { name: "second_follows_edge_id", semantic_type: "Bytes", nullable: false }, { name: "posted_edge_id", semantic_type: "Bytes", nullable: false }, { name: "topic_edge_id", semantic_type: "Bytes", nullable: false }];

/**
 * Yui home feed: fan-out IN_HOME_FEED edges for Yui's (Japanese-clustered) followees.
 */
export interface YuiHomeFeedParams {
  /**
   * Page offset (Int64, encoded by the Gateway).
   */
  offset: bigint;
}

export interface YuiHomeFeedRow {
  post_id: bigint;
  parent_post_id: bigint | null;
  parent_author_name: string | null;
  parent_body: string | null;
  parent_created_at: Temporal.Instant | null;
  author_name: string;
  body: string;
  created_at: Temporal.Instant;
}

const YUI_HOME_FEED_COLUMNS: PreparedManifestColumn[] = [{ name: "post_id", semantic_type: "Int64", nullable: false }, { name: "parent_post_id", semantic_type: "Int64", nullable: true }, { name: "parent_author_name", semantic_type: "Text", nullable: true }, { name: "parent_body", semantic_type: "Text", nullable: true }, { name: "parent_created_at", semantic_type: "DateTime", nullable: true }, { name: "author_name", semantic_type: "Text", nullable: false }, { name: "body", semantic_type: "Text", nullable: false }, { name: "created_at", semantic_type: "DateTime", nullable: false }];

export interface PreparedQueries {
  aliceHomeFeed(params: AliceHomeFeedParams): Promise<PreparedResponse<AliceHomeFeedRow>>;
  aliceSemanticFeed(params: AliceSemanticFeedParams): Promise<PreparedResponse<AliceSemanticFeedRow>>;
  publicTimeline(params: PublicTimelineParams): Promise<PreparedResponse<PublicTimelineRow>>;
  semanticDiscovery(params: SemanticDiscoveryParams): Promise<PreparedResponse<SemanticDiscoveryRow>>;
  topicPathExplanation(params: TopicPathExplanationParams): Promise<PreparedResponse<TopicPathExplanationRow>>;
  yuiHomeFeed(params: YuiHomeFeedParams): Promise<PreparedResponse<YuiHomeFeedRow>>;
}

export class PreparedGleaphClient extends GleaphClientWrapper implements PreparedQueries {
  constructor(client: GleaphClient) {
    super(client);
  }

  /**
   * Alice home feed: fan-out IN_HOME_FEED edges for Alice's followees.
   */
  async aliceHomeFeed(params: AliceHomeFeedParams): Promise<PreparedResponse<AliceHomeFeedRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["offset"] = toApiValue(params["offset"], "Int64");
    const response = await this.preparedQuery("alice-home-feed", encodedParams);
    return { ...response, rows: decodeRows(response.rows, ALICE_HOME_FEED_COLUMNS) as unknown as AliceHomeFeedRow[] };
  }

  /**
   * Alice semantic feed: graph-constrained SEARCH over Alice's followees.
   */
  async aliceSemanticFeed(params: AliceSemanticFeedParams): Promise<PreparedResponse<AliceSemanticFeedRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["offset"] = toApiValue(params["offset"], "Int64");
    encodedParams["query"] = toApiValue(params["query"], "Bytes");
    const response = await this.preparedQuery("alice-semantic-feed", encodedParams);
    return { ...response, rows: decodeRows(response.rows, ALICE_SEMANTIC_FEED_COLUMNS) as unknown as AliceSemanticFeedRow[] };
  }

  /**
   * Public timeline: materialized IN_PUBLIC_FEED edges in insertion order.
   */
  async publicTimeline(params: PublicTimelineParams): Promise<PreparedResponse<PublicTimelineRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["offset"] = toApiValue(params["offset"], "Int64");
    const response = await this.preparedQuery("public-timeline", encodedParams);
    return { ...response, rows: decodeRows(response.rows, PUBLIC_TIMELINE_COLUMNS) as unknown as PublicTimelineRow[] };
  }

  /**
   * Semantic discovery: vector-only SEARCH over public posts.
   */
  async semanticDiscovery(params: SemanticDiscoveryParams): Promise<PreparedResponse<SemanticDiscoveryRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["offset"] = toApiValue(params["offset"], "Int64");
    encodedParams["query"] = toApiValue(params["query"], "Bytes");
    const response = await this.preparedQuery("semantic-discovery", encodedParams);
    return { ...response, rows: decodeRows(response.rows, SEMANTIC_DISCOVERY_COLUMNS) as unknown as SemanticDiscoveryRow[] };
  }

  /**
   * Topic path: four-edge relationship trail with edge identities.
   */
  async topicPathExplanation(params: TopicPathExplanationParams): Promise<PreparedResponse<TopicPathExplanationRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["offset"] = toApiValue(params["offset"], "Int64");
    const response = await this.preparedQuery("topic-path-explanation", encodedParams);
    return { ...response, rows: decodeRows(response.rows, TOPIC_PATH_EXPLANATION_COLUMNS) as unknown as TopicPathExplanationRow[] };
  }

  /**
   * Yui home feed: fan-out IN_HOME_FEED edges for Yui's (Japanese-clustered) followees.
   */
  async yuiHomeFeed(params: YuiHomeFeedParams): Promise<PreparedResponse<YuiHomeFeedRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["offset"] = toApiValue(params["offset"], "Int64");
    const response = await this.preparedQuery("yui-home-feed", encodedParams);
    return { ...response, rows: decodeRows(response.rows, YUI_HOME_FEED_COLUMNS) as unknown as YuiHomeFeedRow[] };
  }
}

export function withPreparedQueries(client: GleaphClient): PreparedGleaphClient {
  return new PreparedGleaphClient(client);
}

/** Construct a client bound to the graph's prepared operations and dynamic GQL. */
export async function createPreparedGleaphClient(options: GleaphTransportOptions): Promise<PreparedGleaphClient> {
  return withPreparedQueries(await createGleaphClient(options));
}

/** Construct a prepared client over an existing SDK transport. */
export function createPreparedGleaphClientFromTransport(transport: GleaphTransport): PreparedGleaphClient {
  return withPreparedQueries(createGleaphClientFromTransport(transport));
}
