use gleaph_types::{PreparedKind, PreparedStatementInfo};

use super::{
    JsParamStyle, doc_parts, format_gql_doc, needs_prepared_sort_import, needs_principal_import,
    render_dts_param_aliases, render_dts_sort_aliases, render_js_sort_objects, sanitize_ident,
    ts_factory_method_signature, ts_interface_method_signature,
};

/// Generate a `.js` file with JSDoc annotations.
pub fn generate_js(
    stmts: &[PreparedStatementInfo],
    canister_id: &str,
    param_style: JsParamStyle,
) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by gleaph codegen — DO NOT EDIT\n");
    out.push_str(&format!("// Source canister: {canister_id}\n\n"));

    out.push_str(&render_js_sort_objects(stmts));

    // createPreparedClient function
    out.push_str("/** @param {import(\"@gleaph/sdk\").GraphClient} graph */\n");
    out.push_str("export function createPreparedClient(graph) {\n");
    out.push_str("  return {\n");

    for (i, info) in stmts.iter().enumerate() {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        // JSDoc comment
        out.push_str(&format_gql_doc(&info.source, "    //"));
        for part in doc_parts(info) {
            out.push_str(&format!("    // {part}\n"));
        }

        out.push_str(&ts_factory_method_signature(info, &ident, param_style));

        if i < stmts.len() - 1 {
            out.push_str(",\n\n");
        } else {
            out.push('\n');
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

/// Generate a `.d.ts` file with full type information.
pub fn generate_dts(
    stmts: &[PreparedStatementInfo],
    canister_id: &str,
    param_style: JsParamStyle,
) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by gleaph codegen — DO NOT EDIT\n");
    out.push_str(&format!("// Source canister: {canister_id}\n\n"));

    // Determine which imports are needed
    let has_query = stmts.iter().any(|s| matches!(s.kind, PreparedKind::Query));
    let has_mutation = stmts
        .iter()
        .any(|s| matches!(s.kind, PreparedKind::Mutation));

    let mut imports = vec!["GraphClient"];
    if has_query {
        imports.push("QueryResultWithContinuation");
        if needs_prepared_sort_import(stmts) {
            imports.push("PreparedSortSpec");
        }
    }
    if has_mutation {
        imports.push("MutationResult");
    }
    out.push_str(&format!(
        "import type {{ {} }} from \"@gleaph/sdk\";\n",
        imports.join(", ")
    ));
    if needs_principal_import(stmts) {
        out.push_str("import { Principal } from \"@icp-sdk/core/principal\";\n");
    }
    out.push('\n');
    out.push_str(&render_dts_param_aliases(stmts, param_style));
    out.push_str(&render_dts_sort_aliases(stmts));

    // Interface
    out.push_str("export interface GleaphPrepared {\n");
    for info in stmts {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        // JSDoc
        out.push_str("  /**\n");
        out.push_str(&format_gql_doc(&info.source, "   *"));
        for part in doc_parts(info) {
            out.push_str(&format!("   * {part}\n"));
        }
        out.push_str("   */\n");

        out.push_str(&ts_interface_method_signature(info, &ident, param_style));
    }
    out.push_str("}\n\n");

    // Factory function declaration
    out.push_str(
        "export declare function createPreparedClient(graph: GraphClient): GleaphPrepared;\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_info(
        name: &str,
        kind: PreparedKind,
        parameters: &[&str],
        columns: &[&str],
        allowed_sorts: &[(&str, &str)],
        default_sort: Option<Vec<gleaph_types::PreparedSortSpec>>,
        requires_caller: bool,
        source: &str,
    ) -> PreparedStatementInfo {
        PreparedStatementInfo {
            name: name.into(),
            kind,
            parameters: parameters
                .iter()
                .map(|s| gleaph_types::PreparedParameterInfo {
                    name: s.trim_start_matches('$').into(),
                    required: true,
                    types: vec![],
                    inferred: false,
                })
                .collect(),
            columns: columns.iter().map(|s| s.to_string()).collect(),
            description: None,
            allowed_sorts: allowed_sorts
                .iter()
                .map(|(key, expr)| gleaph_types::PreparedSortKey {
                    key: (*key).into(),
                    expr: (*expr).into(),
                })
                .collect(),
            default_sort,
            requires_caller,
            source: source.into(),
            type_warnings: vec![],
        }
    }

    #[test]
    fn empty_generates_valid_js() {
        let js = generate_js(&[], "test-canister", JsParamStyle::Camel);
        assert!(js.contains("createPreparedClient"));
        assert!(js.contains("return {"));
    }

    #[test]
    fn empty_generates_valid_dts() {
        let dts = generate_dts(&[], "test-canister", JsParamStyle::Camel);
        assert!(dts.contains("GleaphPrepared"));
        assert!(dts.contains("createPreparedClient"));
        // No query/mutation imports when empty
        assert!(!dts.contains("QueryResultWithContinuation"));
        assert!(!dts.contains("MutationResult"));
    }

    #[test]
    fn query_with_params() {
        let stmts = vec![make_info(
            "get_user",
            PreparedKind::Query,
            &["name"],
            &["name", "age"],
            &[("name", "u.name")],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name, u.age AS age",
        )];

        let js = generate_js(&stmts, "abc", JsParamStyle::Camel);
        assert!(js.contains("get_user: (params, options) =>"));
        assert!(js.contains("executePrepared(\"get_user\", params, options?.sort)"));
        assert!(js.contains("Columns: name, age"));
        assert!(js.contains("Allowed sorts: name (u.name)"));

        let dts = generate_dts(&stmts, "abc", JsParamStyle::Camel);
        assert!(dts.contains(
            "export interface GetUserParams {\n  /** wire param: \"name\" */\n  name: unknown;\n}"
        ));
        assert!(dts.contains(
            "export declare const GetUserSortKey: {\n  /** wire key: \"name\", expr: \"u.name\" */\n  readonly Name: \"name\";\n};"
        ));
        assert!(dts.contains(
            "get_user(params: GetUserParams, options?: { sort?: GetUserSortSpec[] }): Promise<QueryResultWithContinuation>"
        ));
        assert!(dts.contains("Columns: name, age"));
        assert!(dts.contains("QueryResultWithContinuation"));
        assert!(!dts.contains("MutationResult"));
        assert!(js.contains("export const GetUserSortKey = {\n  /** wire key: \"name\", expr: \"u.name\" */\n  Name: \"name\",\n};"));
    }

    #[test]
    fn description_is_emitted_in_docs() {
        let mut info = make_info(
            "get_user",
            PreparedKind::Query,
            &["name"],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name",
        );
        info.description = Some("Fetch a single user by name.".into());
        let js = generate_js(&[info.clone()], "abc", JsParamStyle::Camel);
        let dts = generate_dts(&[info], "abc", JsParamStyle::Camel);
        assert!(js.contains("// Fetch a single user by name."));
        assert!(dts.contains("* Fetch a single user by name."));
    }

    #[test]
    fn mutation_no_params() {
        let stmts = vec![make_info(
            "reset_all",
            PreparedKind::Mutation,
            &[],
            &[],
            &[],
            None,
            false,
            "DELETE (:Temp)",
        )];

        let js = generate_js(&stmts, "abc", JsParamStyle::Camel);
        assert!(js.contains("reset_all: () =>"));
        assert!(js.contains("executePreparedMutation(\"reset_all\", {})"));

        let dts = generate_dts(&stmts, "abc", JsParamStyle::Camel);
        assert!(dts.contains("reset_all(): Promise<MutationResult>"));
    }

    #[test]
    fn requires_caller_annotation() {
        let stmts = vec![make_info(
            "my_posts",
            PreparedKind::Query,
            &[],
            &["title"],
            &[],
            None,
            true,
            "MATCH (p:Post) WHERE p.author = caller() RETURN p.title AS title",
        )];

        let js = generate_js(&stmts, "abc", JsParamStyle::Camel);
        assert!(js.contains("Uses caller()"));

        let dts = generate_dts(&stmts, "abc", JsParamStyle::Camel);
        assert!(dts.contains("Uses caller()"));
    }

    #[test]
    fn hyphenated_name_sanitized() {
        let stmts = vec![make_info(
            "get-user",
            PreparedKind::Query,
            &[],
            &[],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u",
        )];
        let js = generate_js(&stmts, "abc", JsParamStyle::Camel);
        assert!(js.contains("get_user:"));
        assert!(js.contains("executePrepared(\"get-user\""));
    }

    #[test]
    fn dollar_prefix_stripped_in_dts_params() {
        let stmts = vec![make_info(
            "q",
            PreparedKind::Query,
            &["$name", "$age"],
            &[],
            &[],
            None,
            false,
            "MATCH (u) WHERE u.name = $name AND u.age = $age RETURN u",
        )];
        let dts = generate_dts(&stmts, "abc", JsParamStyle::Camel);
        assert!(dts.contains(
            "export interface QParams {\n  /** wire param: \"name\" */\n  name: unknown;\n  /** wire param: \"age\" */\n  age: unknown;\n}"
        ));
        // The GQL source in doc comments will still contain $name — that's expected
    }

    #[test]
    fn preserve_param_style_keeps_snake_case() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &["user_name"],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $user_name RETURN u.name AS name",
        )];

        let js = generate_js(&stmts, "abc", JsParamStyle::Preserve);
        assert!(js.contains("find_user: (params) =>"));
        assert!(js.contains("executePrepared(\"find_user\", params)"));

        let dts = generate_dts(&stmts, "abc", JsParamStyle::Preserve);
        assert!(dts.contains(
            "export interface FindUserParams {\n  /** wire param: \"user_name\" */\n  user_name: unknown;\n}"
        ));
        assert!(
            dts.contains("find_user(params: FindUserParams): Promise<QueryResultWithContinuation>")
        );
    }

    #[test]
    fn camel_param_style_maps_wire_names() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &["user_name"],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $user_name RETURN u.name AS name",
        )];

        let js = generate_js(&stmts, "abc", JsParamStyle::Camel);
        assert!(js.contains("find_user: (params) =>"));
        assert!(js.contains("executePrepared(\"find_user\", { user_name: params.userName })"));

        let dts = generate_dts(&stmts, "abc", JsParamStyle::Camel);
        assert!(dts.contains(
            "export interface FindUserParams {\n  /** wire param: \"user_name\" */\n  userName: unknown;\n}"
        ));
        assert!(
            dts.contains("find_user(params: FindUserParams): Promise<QueryResultWithContinuation>")
        );
    }

    #[test]
    fn sort_key_names_are_stable_for_digits_and_collisions() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &[],
            &["name"],
            &[
                ("1day", "u.one_day"),
                ("user_name", "u.user_name"),
                ("user-name", "u.alt_user_name"),
            ],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        )];

        let js = generate_js(&stmts, "abc", JsParamStyle::Camel);
        assert!(
            js.contains("  /** wire key: \"1day\", expr: \"u.one_day\" */\n  K1day: \"1day\",")
        );
        assert!(js.contains(
            "  /** wire key: \"user_name\", expr: \"u.user_name\" */\n  UserName: \"user_name\","
        ));
        assert!(js.contains("  /** wire key: \"user-name\", expr: \"u.alt_user_name\" */\n  UserName2: \"user-name\","));

        let dts = generate_dts(&stmts, "abc", JsParamStyle::Camel);
        assert!(dts.contains("export declare const FindUserSortKey: {\n  /** wire key: \"1day\", expr: \"u.one_day\" */\n  readonly K1day: \"1day\";"));
        assert!(dts.contains("  /** wire key: \"user_name\", expr: \"u.user_name\" */\n  readonly UserName: \"user_name\";"));
        assert!(dts.contains("  /** wire key: \"user-name\", expr: \"u.alt_user_name\" */\n  readonly UserName2: \"user-name\";"));
    }

    #[test]
    fn optional_params_are_optional_in_dts() {
        let mut info = make_info(
            "search",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        );
        info.parameters = vec![
            gleaph_types::PreparedParameterInfo {
                name: "query".into(),
                required: true,
                types: vec![],
                inferred: false,
            },
            gleaph_types::PreparedParameterInfo {
                name: "offset".into(),
                required: false,
                types: vec![],
                inferred: false,
            },
        ];

        let js = generate_js(&[info.clone()], "abc", JsParamStyle::Camel);
        assert!(js.contains(
            "executePrepared(\"search\", { query: params.query, ...(params.offset !== undefined ? { offset: params.offset } : {}) })"
        ));

        let dts = generate_dts(&[info], "abc", JsParamStyle::Camel);
        assert!(dts.contains("export interface SearchParams {\n  /** wire param: \"query\" */\n  query: unknown;\n  /** wire param: \"offset\" */\n  offset?: unknown;\n}"));
        assert!(dts.contains("search(params: SearchParams): Promise<QueryResultWithContinuation>"));
    }

    #[test]
    fn dts_typed_params_emit_native_types() {
        use gleaph_types::PreparedValueType;
        let mut info = make_info(
            "search",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        );
        info.parameters = vec![
            gleaph_types::PreparedParameterInfo {
                name: "min_age".into(),
                required: true,
                types: vec![PreparedValueType::Int64],
                inferred: true,
            },
            gleaph_types::PreparedParameterInfo {
                name: "name".into(),
                required: true,
                types: vec![PreparedValueType::Text],
                inferred: true,
            },
            gleaph_types::PreparedParameterInfo {
                name: "active".into(),
                required: false,
                types: vec![PreparedValueType::Bool],
                inferred: true,
            },
        ];
        let dts = generate_dts(&[info], "abc", JsParamStyle::Camel);
        assert!(dts.contains("minAge: bigint;"), "expected bigint: {dts}");
        assert!(dts.contains("name: string;"), "expected string: {dts}");
        assert!(
            dts.contains("active?: boolean;"),
            "expected boolean?: {dts}"
        );
    }

    #[test]
    fn dts_typed_list_params_emit_typed_arrays() {
        use gleaph_types::{PreparedScalarType, PreparedValueType};
        let mut info = make_info(
            "search",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        );
        info.parameters = vec![
            gleaph_types::PreparedParameterInfo {
                name: "ids".into(),
                required: true,
                types: vec![PreparedValueType::TypedList(PreparedScalarType::Int64)],
                inferred: true,
            },
            gleaph_types::PreparedParameterInfo {
                name: "tags".into(),
                required: false,
                types: vec![PreparedValueType::TypedList(PreparedScalarType::Text)],
                inferred: true,
            },
        ];
        let dts = generate_dts(&[info], "abc", JsParamStyle::Camel);
        assert!(dts.contains("ids: bigint[];"), "expected bigint[]: {dts}");
        assert!(
            dts.contains("tags?: string[];"),
            "expected string[]?: {dts}"
        );
    }

    #[test]
    fn dts_principal_param_imports_principal() {
        use gleaph_types::PreparedValueType;
        let mut info = make_info(
            "by_owner",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "RETURN 1",
        );
        info.parameters = vec![gleaph_types::PreparedParameterInfo {
            name: "owner".into(),
            required: true,
            types: vec![PreparedValueType::Principal],
            inferred: true,
        }];
        let dts = generate_dts(&[info], "abc", JsParamStyle::Camel);
        assert!(
            dts.contains("import { Principal }"),
            "expected Principal import: {dts}"
        );
        assert!(
            dts.contains("owner: Principal;"),
            "expected Principal type: {dts}"
        );
    }
}
