use gleaph_types::{PreparedKind, PreparedStatementInfo};

use super::{
    JsParamStyle, doc_parts, format_gql_doc, has_dynamic_sort, optional_param_bindings,
    param_bindings, params_type_name, render_rs_union_enums, required_param_bindings,
    rs_param_type_ctx, sanitize_ident, sort_key_bindings, sort_key_type_name, sort_spec_type_name,
};

/// Generate a `.rs` file with a trait-based prepared client.
pub fn generate_rs(stmts: &[PreparedStatementInfo], canister_id: &str) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by gleaph codegen — DO NOT EDIT\n");
    out.push_str(&format!("// Source canister: {canister_id}\n\n"));
    out.push_str("#![allow(unused, clippy::all)]\n\n");
    out.push_str("use gleaph_types::{GleaphError, PreparedSortSpec, Value};\n\n");
    out.push_str(&render_rs_union_enums(stmts));
    out.push_str(&render_rs_types(stmts));

    out.push_str("/// Trait for executing prepared statements on a graph canister.\n");
    out.push_str("/// Implement this for your agent or inter-canister client.\n");
    out.push_str("#[allow(async_fn_in_trait)]\n");
    out.push_str("pub trait GraphOps {\n");
    out.push_str("    async fn execute_prepared(\n");
    out.push_str(
        "        &self,\n        name: &str,\n        params: Vec<(&str, Value)>,\n        sort: Option<Vec<PreparedSortSpec>>,\n",
    );
    out.push_str("    ) -> Result<QueryResult, GleaphError>;\n\n");
    out.push_str("    async fn execute_prepared_mutation(\n");
    out.push_str("        &self,\n        name: &str,\n        params: Vec<(&str, Value)>,\n");
    out.push_str("    ) -> Result<MutationResult, GleaphError>;\n");
    out.push_str("}\n\n");

    out.push_str("// Re-export or define these types to match your SDK.\n");
    out.push_str("pub use gleaph_types::MutationResult;\n");
    out.push_str("pub use gleaph_types::QueryResult;\n\n");

    out.push_str("/// Type-safe wrapper around prepared statements.\n");
    out.push_str("pub struct PreparedClient<'a, C: GraphOps> {\n");
    out.push_str("    graph: &'a C,\n");
    out.push_str("}\n\n");

    out.push_str("impl<'a, C: GraphOps> PreparedClient<'a, C> {\n");
    out.push_str("    pub fn new(graph: &'a C) -> Self {\n");
    out.push_str("        Self { graph }\n");
    out.push_str("    }\n");

    for info in stmts {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        out.push('\n');
        out.push_str(&format_gql_doc(&info.source, "    ///"));
        for part in doc_parts(info) {
            out.push_str(&format!("    /// {part}\n"));
        }

        let return_type = match info.kind {
            PreparedKind::Query => "QueryResult",
            PreparedKind::Mutation => "MutationResult",
        };
        let method = match info.kind {
            PreparedKind::Query => "execute_prepared",
            PreparedKind::Mutation => "execute_prepared_mutation",
        };
        let sort_enabled = has_dynamic_sort(info);

        if info.parameters.is_empty() && !sort_enabled {
            out.push_str(&format!(
                "    pub async fn {ident}(&self) -> Result<{return_type}, GleaphError> {{\n"
            ));
            if matches!(info.kind, PreparedKind::Query) {
                out.push_str(&format!(
                    "        self.graph.{method}(\"{}\", vec![], None).await\n",
                    info.name
                ));
            } else {
                out.push_str(&format!(
                    "        self.graph.{method}(\"{}\", vec![]).await\n",
                    info.name
                ));
            }
            out.push_str("    }\n");
            continue;
        }

        let mut args = Vec::new();
        if !info.parameters.is_empty() {
            args.push(format!("params: {}", params_type_name(&ident)));
        }
        if sort_enabled {
            args.push(format!(
                "sort: Option<Vec<{}>>",
                sort_spec_type_name(&ident)
            ));
        }

        out.push_str(&format!(
            "    pub async fn {ident}(&self, {}) -> Result<{return_type}, GleaphError> {{\n",
            args.join(", ")
        ));

        // Build param name → type info lookup for wire conversion.
        let param_type_map: std::collections::HashMap<&str, Option<String>> = info
            .parameters
            .iter()
            .map(|p| (p.name.as_str(), rs_param_type_ctx(p, Some(&ident))))
            .collect();

        let param_expr = if info.parameters.is_empty() {
            "vec![]".to_string()
        } else {
            let required = required_param_bindings(info, JsParamStyle::Preserve);
            let optional = optional_param_bindings(info, JsParamStyle::Preserve);
            // For native-typed fields, use .into() to convert to Value.
            let make_required_entry = |binding: &super::ParamBinding| -> String {
                let is_native = param_type_map
                    .get(binding.wire_name.as_str())
                    .is_some_and(|t| t.is_some());
                if is_native {
                    format!(
                        "(\"{}\", params.{}.into())",
                        binding.wire_name, binding.api_name
                    )
                } else {
                    format!("(\"{}\", params.{})", binding.wire_name, binding.api_name)
                }
            };
            let make_optional_entry = |binding: &super::ParamBinding| -> String {
                let is_native = param_type_map
                    .get(binding.wire_name.as_str())
                    .is_some_and(|t| t.is_some());
                if is_native {
                    format!(
                        "params.{0}.map(|v| (\"{1}\", v.into()))",
                        binding.api_name, binding.wire_name
                    )
                } else {
                    format!(
                        "params.{0}.clone().map(|value| (\"{1}\", value))",
                        binding.api_name, binding.wire_name
                    )
                }
            };
            let mut entries: Vec<String> = required.iter().map(make_required_entry).collect();
            entries.extend(optional.iter().map(make_optional_entry));
            if optional.is_empty() {
                format!("vec![{}]", entries.join(", "))
            } else {
                let required_entries: Vec<String> =
                    required.iter().map(make_required_entry).collect();
                let optional_entries: Vec<String> =
                    optional.iter().map(make_optional_entry).collect();
                format!(
                    "{{ let mut params_vec = vec![{}]; params_vec.extend([{}].into_iter().flatten()); params_vec }}",
                    required_entries.join(", "),
                    optional_entries.join(", ")
                )
            }
        };

        if matches!(info.kind, PreparedKind::Query) {
            let sort_expr = if sort_enabled {
                "sort.map(|items| items.into_iter().map(Into::into).collect())"
            } else {
                "None"
            };
            out.push_str(&format!(
                "        self.graph.{method}(\"{}\", {}, {}).await\n",
                info.name, param_expr, sort_expr
            ));
        } else {
            out.push_str(&format!(
                "        self.graph.{method}(\"{}\", {}).await\n",
                info.name, param_expr
            ));
        }
        out.push_str("    }\n");
    }

    out.push_str("}\n");
    out
}

fn render_rs_types(stmts: &[PreparedStatementInfo]) -> String {
    let mut out = String::new();

    for info in stmts {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        let params = param_bindings(info, JsParamStyle::Preserve);
        if !params.is_empty() {
            // Build param name → type info lookup (with statement context for union enums).
            let param_type_map: std::collections::HashMap<&str, Option<String>> = info
                .parameters
                .iter()
                .map(|p| (p.name.as_str(), rs_param_type_ctx(p, Some(&ident))))
                .collect();

            let params_type = params_type_name(&ident);
            let builder_type = format!("{params_type}Builder");
            let required = required_param_bindings(info, JsParamStyle::Preserve);
            let optional = optional_param_bindings(info, JsParamStyle::Preserve);
            out.push_str(&format!("/// Parameters for `{}`.\n", info.name));
            out.push_str(&format!("pub struct {params_type} {{\n"));

            // Struct fields — use native types when available.
            for binding in &required {
                let field_type = param_type_map
                    .get(binding.wire_name.as_str())
                    .and_then(|t| t.as_deref())
                    .unwrap_or("Value");
                out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
                out.push_str(&format!("    pub {}: {field_type},\n", binding.api_name));
            }
            for binding in &optional {
                let inner_type = param_type_map
                    .get(binding.wire_name.as_str())
                    .and_then(|t| t.as_deref());
                match inner_type {
                    // If rs_param_type already returned Option<T>, use it directly.
                    Some(t) if t.starts_with("Option<") => {
                        out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
                        out.push_str(&format!("    pub {}: {t},\n", binding.api_name));
                    }
                    Some(t) => {
                        out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
                        out.push_str(&format!("    pub {}: Option<{t}>,\n", binding.api_name));
                    }
                    None => {
                        out.push_str(&format!("    /// wire param: {:?}\n", binding.wire_name));
                        out.push_str(&format!("    pub {}: Option<Value>,\n", binding.api_name));
                    }
                }
            }
            out.push_str("}\n\n");

            // Constructor — accept native types directly.
            let constructor_args: Vec<String> = required
                .iter()
                .map(|binding| {
                    let ty = param_type_map
                        .get(binding.wire_name.as_str())
                        .and_then(|t| t.as_deref())
                        .unwrap_or("Value");
                    format!("{}: {ty}", binding.api_name)
                })
                .collect();

            out.push_str(&format!("impl {params_type} {{\n"));
            if !required.is_empty() {
                out.push_str(&format!(
                    "    pub fn new({}) -> Self {{\n",
                    constructor_args.join(", ")
                ));
                let mut fields: Vec<String> = required
                    .iter()
                    .map(|binding| binding.api_name.clone())
                    .collect();
                fields.extend(
                    optional
                        .iter()
                        .map(|binding| format!("{}: None", binding.api_name)),
                );
                out.push_str(&format!("        Self {{ {} }}\n", fields.join(", ")));
                out.push_str("    }\n");
                if !optional.is_empty() {
                    out.push_str(&format!(
                        "    pub fn builder({}) -> {builder_type} {{\n",
                        constructor_args.join(", ")
                    ));
                    out.push_str(&format!(
                        "        {builder_type} {{ params: Self::new({}) }}\n",
                        required
                            .iter()
                            .map(|binding| binding.api_name.clone())
                            .collect::<Vec<_>>()
                            .join(", ")
                    ));
                    out.push_str("    }\n");
                }
            } else {
                out.push_str("    pub fn new() -> Self {\n");
                out.push_str(&format!(
                    "        Self {{ {} }}\n",
                    optional
                        .iter()
                        .map(|binding| format!("{}: None", binding.api_name))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
                out.push_str("    }\n");
                out.push_str(&format!("    pub fn builder() -> {builder_type} {{\n"));
                out.push_str(&format!(
                    "        {builder_type} {{ params: Self::new() }}\n"
                ));
                out.push_str("    }\n");
            }
            out.push_str("}\n\n");
            if !optional.is_empty() {
                out.push_str(&format!("pub struct {builder_type} {{\n"));
                out.push_str(&format!("    params: {params_type},\n"));
                out.push_str("}\n\n");
                out.push_str(&format!("impl {builder_type} {{\n"));
                for binding in &optional {
                    let inner_type = param_type_map
                        .get(binding.wire_name.as_str())
                        .and_then(|t| t.as_deref());
                    // Extract inner type from Option<T>, or use raw type, or Value.
                    let setter_type = match inner_type {
                        Some(t) if t.starts_with("Option<") => &t[7..t.len() - 1],
                        Some(t) => t,
                        None => "Value",
                    };
                    out.push_str(&format!(
                        "    pub fn {}(mut self, value: {setter_type}) -> Self {{\n",
                        binding.api_name
                    ));
                    out.push_str(&format!(
                        "        self.params.{} = Some(value);\n",
                        binding.api_name
                    ));
                    out.push_str("        self\n");
                    out.push_str("    }\n");
                }
                out.push_str(&format!("    pub fn build(self) -> {params_type} {{\n"));
                out.push_str("        self.params\n");
                out.push_str("    }\n");
                out.push_str("}\n\n");
            }
        }

        if !has_dynamic_sort(info) {
            continue;
        }

        let key_type = sort_key_type_name(&ident);
        let spec_type = sort_spec_type_name(&ident);
        let sort_keys = sort_key_bindings(info);

        out.push_str(&format!("/// Sort keys for `{}`.\n", info.name));
        out.push_str(&format!("pub enum {key_type} {{\n"));
        for (binding, sort) in sort_keys.iter().zip(info.allowed_sorts.iter()) {
            out.push_str(&format!(
                "    /// wire key: {:?}\n    /// expr: {:?}\n    {},\n",
                binding.wire_key, sort.expr, binding.api_name
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!("impl {key_type} {{\n"));
        out.push_str("    pub fn as_wire_key(&self) -> &'static str {\n");
        out.push_str("        match self {\n");
        for binding in &sort_keys {
            out.push_str(&format!(
                "            Self::{} => {:?},\n",
                binding.api_name, binding.wire_key
            ));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str(&format!("/// Sort specification for `{}`.\n", info.name));
        out.push_str(&format!("pub struct {spec_type} {{\n"));
        out.push_str(&format!("    pub key: {key_type},\n"));
        out.push_str("    pub descending: bool,\n");
        out.push_str("    pub nulls_first: Option<bool>,\n");
        out.push_str("}\n\n");

        out.push_str(&format!("impl {spec_type} {{\n"));
        out.push_str(&format!("    pub fn asc(key: {key_type}) -> Self {{\n"));
        out.push_str("        Self { key, descending: false, nulls_first: None }\n");
        out.push_str("    }\n");
        out.push_str(&format!("    pub fn desc(key: {key_type}) -> Self {{\n"));
        out.push_str("        Self { key, descending: true, nulls_first: None }\n");
        out.push_str("    }\n");
        out.push_str("    pub fn with_nulls_first(mut self, nulls_first: bool) -> Self {\n");
        out.push_str("        self.nulls_first = Some(nulls_first);\n");
        out.push_str("        self\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str(&format!("impl From<{spec_type}> for PreparedSortSpec {{\n"));
        out.push_str(&format!("    fn from(value: {spec_type}) -> Self {{\n"));
        out.push_str("        Self {\n");
        out.push_str("            key: value.key.as_wire_key().to_string(),\n");
        out.push_str("            descending: value.descending,\n");
        out.push_str("            nulls_first: value.nulls_first,\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_info(
        name: &str,
        kind: PreparedKind,
        parameters: &[&str],
        columns: &[&str],
        allowed_sorts: &[(&str, &str)],
        default_sort: Option<Vec<gleaph_types::PreparedSortSpec>>,
        requires_caller: bool,
        source: &str,
    ) -> PreparedStatementInfo {
        PreparedStatementInfo {
            name: name.into(),
            kind,
            parameters: parameters
                .iter()
                .map(|s| gleaph_types::PreparedParameterInfo {
                    name: s.trim_start_matches('$').into(),
                    required: true,
                    types: vec![],
                    inferred: false,
                })
                .collect(),
            columns: columns.iter().map(|s| s.to_string()).collect(),
            description: None,
            allowed_sorts: allowed_sorts
                .iter()
                .map(|(key, expr)| gleaph_types::PreparedSortKey {
                    key: (*key).into(),
                    expr: (*expr).into(),
                })
                .collect(),
            default_sort,
            requires_caller,
            source: source.into(),
            type_warnings: vec![],
        }
    }

    #[test]
    fn rs_query_with_params() {
        let stmts = vec![make_info(
            "get_user",
            PreparedKind::Query,
            &["name"],
            &["name", "age"],
            &[("name", "u.name")],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name, u.age AS age",
        )];
        let rs = generate_rs(&stmts, "abc");
        assert!(rs.contains(
            "pub struct GetUserParams {\n    /// wire param: \"name\"\n    pub name: Value,\n}"
        ));
        assert!(rs.contains(
            "impl GetUserParams {\n    pub fn new(name: Value) -> Self {\n        Self { name }\n    }\n}"
        ));
        assert!(rs.contains(
            "pub enum GetUserSortKey {\n    /// wire key: \"name\"\n    /// expr: \"u.name\"\n    Name,\n}"
        ));
        assert!(rs.contains(
            "pub struct GetUserSortSpec {\n    pub key: GetUserSortKey,\n    pub descending: bool,\n    pub nulls_first: Option<bool>,\n}"
        ));
        assert!(rs.contains(
            "impl GetUserSortSpec {\n    pub fn asc(key: GetUserSortKey) -> Self {\n        Self { key, descending: false, nulls_first: None }\n    }\n    pub fn desc(key: GetUserSortKey) -> Self {\n        Self { key, descending: true, nulls_first: None }\n    }"
        ));
        assert!(rs.contains(
            "pub async fn get_user(&self, params: GetUserParams, sort: Option<Vec<GetUserSortSpec>>)"
        ));
        assert!(rs.contains(
            "execute_prepared(\"get_user\", vec![(\"name\", params.name)], sort.map(|items| items.into_iter().map(Into::into).collect()))"
        ));
        assert!(rs.contains("Columns: name, age"));
    }

    #[test]
    fn rs_mutation_no_params() {
        let stmts = vec![make_info(
            "clear",
            PreparedKind::Mutation,
            &[],
            &[],
            &[],
            None,
            false,
            "DELETE (:Temp)",
        )];
        let rs = generate_rs(&stmts, "abc");
        assert!(rs.contains("pub async fn clear(&self) -> Result<MutationResult"));
        assert!(rs.contains("execute_prepared_mutation(\"clear\", vec![])"));
    }

    #[test]
    fn rs_requires_caller_annotation() {
        let stmts = vec![make_info(
            "my_posts",
            PreparedKind::Query,
            &[],
            &["title"],
            &[],
            None,
            true,
            "MATCH (p:Post) WHERE p.author = caller() RETURN p.title",
        )];
        let rs = generate_rs(&stmts, "abc");
        assert!(rs.contains("Uses caller()"));
    }

    #[test]
    fn rs_multiple_params() {
        let stmts = vec![make_info(
            "search",
            PreparedKind::Query,
            &["min_age", "label"],
            &[],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.age > $min_age AND u.label = $label RETURN u",
        )];
        let rs = generate_rs(&stmts, "abc");
        assert!(rs.contains("pub struct SearchParams {"));
        assert!(rs.contains("/// wire param: \"min_age\"\n    pub min_age: Value,"));
        assert!(rs.contains("/// wire param: \"label\"\n    pub label: Value,"));
        assert!(rs.contains(
            "impl SearchParams {\n    pub fn new(min_age: Value, label: Value) -> Self {\n        Self { min_age, label }\n    }\n}"
        ));
        assert!(rs.contains("pub async fn search(&self, params: SearchParams)"));
    }

    #[test]
    fn rs_optional_params_generate_builder() {
        let mut info = make_info(
            "search",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        );
        info.parameters = vec![
            gleaph_types::PreparedParameterInfo {
                name: "query".into(),
                required: true,
                types: vec![],
                inferred: false,
            },
            gleaph_types::PreparedParameterInfo {
                name: "limit".into(),
                required: true,
                types: vec![],
                inferred: false,
            },
            gleaph_types::PreparedParameterInfo {
                name: "offset".into(),
                required: false,
                types: vec![],
                inferred: false,
            },
            gleaph_types::PreparedParameterInfo {
                name: "city".into(),
                required: false,
                types: vec![],
                inferred: false,
            },
        ];
        let rs = generate_rs(&[info], "abc");
        assert!(rs.contains("pub struct SearchParams {"));
        assert!(rs.contains("pub offset: Option<Value>,"));
        assert!(rs.contains("pub city: Option<Value>,"));
        assert!(rs.contains("pub fn builder(query: Value, limit: Value) -> SearchParamsBuilder"));
        assert!(rs.contains("pub struct SearchParamsBuilder {"));
        assert!(rs.contains("pub fn offset(mut self, value: Value) -> Self {"));
        assert!(rs.contains("pub fn city(mut self, value: Value) -> Self {"));
        assert!(rs.contains("pub fn build(self) -> SearchParams {"));
        assert!(rs.contains(
            "let mut params_vec = vec![(\"query\", params.query), (\"limit\", params.limit)]; params_vec.extend([params.offset.clone().map(|value| (\"offset\", value)), params.city.clone().map(|value| (\"city\", value))].into_iter().flatten()); params_vec"
        ));
    }

    #[test]
    fn rs_sort_key_names_are_stable_for_digits_and_collisions() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &[],
            &["name"],
            &[
                ("1day", "u.one_day"),
                ("user_name", "u.user_name"),
                ("user-name", "u.alt_user_name"),
            ],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        )];
        let rs = generate_rs(&stmts, "abc");
        assert!(rs.contains("/// wire key: \"1day\"\n    /// expr: \"u.one_day\"\n    K1day,"));
        assert!(
            rs.contains(
                "/// wire key: \"user_name\"\n    /// expr: \"u.user_name\"\n    UserName,"
            )
        );
        assert!(rs.contains(
            "/// wire key: \"user-name\"\n    /// expr: \"u.alt_user_name\"\n    UserName2,"
        ));
    }

    #[test]
    fn rs_typed_params_emit_native_types() {
        use gleaph_types::PreparedValueType;
        let stmts = vec![PreparedStatementInfo {
            name: "find_users".into(),
            kind: PreparedKind::Query,
            parameters: vec![
                gleaph_types::PreparedParameterInfo {
                    name: "min_age".into(),
                    required: true,
                    types: vec![PreparedValueType::Int64],
                    inferred: true,
                },
                gleaph_types::PreparedParameterInfo {
                    name: "name".into(),
                    required: true,
                    types: vec![PreparedValueType::Text],
                    inferred: true,
                },
                gleaph_types::PreparedParameterInfo {
                    name: "active".into(),
                    required: false,
                    types: vec![PreparedValueType::Bool],
                    inferred: true,
                },
                gleaph_types::PreparedParameterInfo {
                    name: "score".into(),
                    required: false,
                    types: vec![PreparedValueType::Float64],
                    inferred: true,
                },
            ],
            columns: vec!["name".into()],
            description: None,
            allowed_sorts: vec![],
            default_sort: None,
            requires_caller: false,
            source:
                "MATCH (u:User) WHERE u.age > $min_age AND u.name = $name RETURN u.name AS name"
                    .into(),
            type_warnings: vec![],
        }];
        let rs = generate_rs(&stmts, "abc");
        // Required params use native types directly.
        assert!(rs.contains("pub min_age: i64,"), "expected i64 field: {rs}");
        assert!(
            rs.contains("pub name: String,"),
            "expected String field: {rs}"
        );
        // Optional params use Option<native>.
        assert!(
            rs.contains("pub active: Option<bool>,"),
            "expected Option<bool> field: {rs}"
        );
        assert!(
            rs.contains("pub score: Option<f64>,"),
            "expected Option<f64> field: {rs}"
        );
        // Constructor uses native types.
        assert!(
            rs.contains("pub fn new(min_age: i64, name: String)"),
            "expected native constructor: {rs}"
        );
        // Builder setters use native inner type.
        assert!(
            rs.contains("pub fn active(mut self, value: bool)"),
            "expected bool setter: {rs}"
        );
        assert!(
            rs.contains("pub fn score(mut self, value: f64)"),
            "expected f64 setter: {rs}"
        );
        // Wire conversion uses .into().
        assert!(
            rs.contains("params.min_age.into()"),
            "expected .into() for min_age: {rs}"
        );
        assert!(
            rs.contains("params.name.into()"),
            "expected .into() for name: {rs}"
        );
    }

    #[test]
    fn rs_typed_list_params_emit_typed_vecs() {
        use gleaph_types::{PreparedScalarType, PreparedValueType};
        let stmts = vec![PreparedStatementInfo {
            name: "find_users".into(),
            kind: PreparedKind::Query,
            parameters: vec![
                gleaph_types::PreparedParameterInfo {
                    name: "ids".into(),
                    required: true,
                    types: vec![PreparedValueType::TypedList(PreparedScalarType::Int64)],
                    inferred: true,
                },
                gleaph_types::PreparedParameterInfo {
                    name: "names".into(),
                    required: true,
                    types: vec![PreparedValueType::TypedList(PreparedScalarType::Text)],
                    inferred: true,
                },
                gleaph_types::PreparedParameterInfo {
                    name: "flags".into(),
                    required: false,
                    types: vec![PreparedValueType::TypedList(PreparedScalarType::Bool)],
                    inferred: true,
                },
            ],
            columns: vec!["name".into()],
            description: None,
            allowed_sorts: vec![],
            default_sort: None,
            requires_caller: false,
            source: "RETURN 1".into(),
            type_warnings: vec![],
        }];
        let rs = generate_rs(&stmts, "abc");
        assert!(rs.contains("pub ids: Vec<i64>,"), "expected Vec<i64>: {rs}");
        assert!(
            rs.contains("pub names: Vec<String>,"),
            "expected Vec<String>: {rs}"
        );
        assert!(
            rs.contains("pub flags: Option<Vec<bool>>,"),
            "expected Option<Vec<bool>>: {rs}"
        );
    }

    #[test]
    fn rs_union_type_generates_enum() {
        use gleaph_types::PreparedValueType;
        let stmts = vec![PreparedStatementInfo {
            name: "search".into(),
            kind: PreparedKind::Query,
            parameters: vec![gleaph_types::PreparedParameterInfo {
                name: "key".into(),
                required: true,
                types: vec![PreparedValueType::Int64, PreparedValueType::Text],
                inferred: true,
            }],
            columns: vec!["result".into()],
            description: None,
            allowed_sorts: vec![],
            default_sort: None,
            requires_caller: false,
            source: "RETURN 1".into(),
            type_warnings: vec![],
        }];
        let rs = generate_rs(&stmts, "abc");
        // Union enum is generated.
        assert!(
            rs.contains("pub enum SearchParamKey {"),
            "expected union enum: {rs}"
        );
        assert!(rs.contains("Int64(i64),"), "expected Int64 variant: {rs}");
        assert!(rs.contains("Text(String),"), "expected Text variant: {rs}");
        // From<enum> for Value impl exists.
        assert!(
            rs.contains("impl From<SearchParamKey> for Value"),
            "expected From impl: {rs}"
        );
        // Convenience From impls.
        assert!(
            rs.contains("impl From<i64> for SearchParamKey"),
            "expected From<i64>: {rs}"
        );
        assert!(
            rs.contains("impl From<String> for SearchParamKey"),
            "expected From<String>: {rs}"
        );
        // Struct field uses the enum type.
        assert!(
            rs.contains("pub key: SearchParamKey,"),
            "expected enum field type: {rs}"
        );
        // Wire conversion uses .into().
        assert!(
            rs.contains("params.key.into()"),
            "expected .into() for union: {rs}"
        );
    }

    #[test]
    fn rs_description_is_emitted_in_docs() {
        let mut info = make_info(
            "get_user",
            PreparedKind::Query,
            &["name"],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name",
        );
        info.description = Some("Fetch a single user by name.".into());
        let rs = generate_rs(&[info], "abc");
        assert!(rs.contains("/// Fetch a single user by name."));
    }
}
