use gleaph_types::{PreparedKind, PreparedStatementInfo};

use super::{
    JsParamStyle, doc_parts, format_gql_doc, needs_prepared_sort_import, needs_principal_import,
    render_ts_param_aliases, render_ts_sort_aliases, sanitize_ident, ts_factory_method_signature,
    ts_interface_method_signature,
};

/// Generate a single `.ts` file with full type annotations.
pub fn generate_ts(
    stmts: &[PreparedStatementInfo],
    canister_id: &str,
    param_style: JsParamStyle,
) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by gleaph codegen — DO NOT EDIT\n");
    out.push_str(&format!("// Source canister: {canister_id}\n\n"));

    // Imports
    let has_query = stmts.iter().any(|s| matches!(s.kind, PreparedKind::Query));
    let has_mutation = stmts
        .iter()
        .any(|s| matches!(s.kind, PreparedKind::Mutation));

    let mut imports = vec!["GraphClient"];
    if has_query {
        imports.push("QueryResultWithContinuation");
        if needs_prepared_sort_import(stmts) {
            imports.push("PreparedSortSpec");
        }
    }
    if has_mutation {
        imports.push("MutationResult");
    }
    out.push_str(&format!(
        "import type {{ {} }} from \"@gleaph/sdk\";\n",
        imports.join(", ")
    ));
    if needs_principal_import(stmts) {
        out.push_str("import { Principal } from \"@icp-sdk/core/principal\";\n");
    }
    out.push('\n');
    out.push_str(&render_ts_param_aliases(stmts, param_style));
    out.push_str(&render_ts_sort_aliases(stmts));

    // Interface
    out.push_str("export interface GleaphPrepared {\n");
    for info in stmts {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        out.push_str("  /**\n");
        out.push_str(&format_gql_doc(&info.source, "   *"));
        for part in doc_parts(info) {
            out.push_str(&format!("   * {part}\n"));
        }
        out.push_str("   */\n");

        out.push_str(&ts_interface_method_signature(info, &ident, param_style));
    }
    out.push_str("}\n\n");

    // Factory function
    out.push_str("export function createPreparedClient(graph: GraphClient): GleaphPrepared {\n");
    out.push_str("  return {\n");

    for (i, info) in stmts.iter().enumerate() {
        let ident = match sanitize_ident(&info.name) {
            Some(id) => id,
            None => continue,
        };

        out.push_str(&ts_factory_method_signature(info, &ident, param_style));

        if i < stmts.len() - 1 {
            out.push_str(",\n\n");
        } else {
            out.push('\n');
        }
    }

    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::super::{params_type_name, sort_key_type_name, sort_spec_type_name};
    use super::*;

    fn make_info(
        name: &str,
        kind: PreparedKind,
        parameters: &[&str],
        columns: &[&str],
        allowed_sorts: &[(&str, &str)],
        default_sort: Option<Vec<gleaph_types::PreparedSortSpec>>,
        requires_caller: bool,
        source: &str,
    ) -> PreparedStatementInfo {
        PreparedStatementInfo {
            name: name.into(),
            kind,
            parameters: parameters
                .iter()
                .map(|s| gleaph_types::PreparedParameterInfo {
                    name: s.trim_start_matches('$').into(),
                    required: true,
                    types: vec![],
                    inferred: false,
                })
                .collect(),
            columns: columns.iter().map(|s| s.to_string()).collect(),
            description: None,
            allowed_sorts: allowed_sorts
                .iter()
                .map(|(key, expr)| gleaph_types::PreparedSortKey {
                    key: (*key).into(),
                    expr: (*expr).into(),
                })
                .collect(),
            default_sort,
            requires_caller,
            source: source.into(),
            type_warnings: vec![],
        }
    }

    #[test]
    fn ts_query_with_params() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &["name"],
            &["name", "age"],
            &[("name", "u.name")],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name, u.age AS age",
        )];
        let ts = generate_ts(&stmts, "canister-abc", JsParamStyle::Camel);
        assert!(ts.contains(
            "export const FindUserSortKey = {\n  /** wire key: \"name\", expr: \"u.name\" */\n  Name: \"name\",\n} as const;"
        ));
        assert!(ts.contains(
            "export interface FindUserParams {\n  /** wire param: \"name\" */\n  name: unknown;\n}"
        ));
        assert!(ts.contains(
            "find_user(params: FindUserParams, options?: { sort?: FindUserSortSpec[] }): Promise<QueryResultWithContinuation>"
        ));
        assert!(ts.contains(
            "find_user: (params, options) =>\n      graph.executePrepared(\"find_user\", params, options?.sort)"
        ));
        assert_eq!(sort_key_type_name("find_user"), "FindUserSortKey");
        assert_eq!(sort_spec_type_name("find_user"), "FindUserSortSpec");
        assert_eq!(params_type_name("find_user"), "FindUserParams");
    }

    #[test]
    fn ts_mutation_no_params() {
        let stmts = vec![make_info(
            "clear",
            PreparedKind::Mutation,
            &[],
            &[],
            &[],
            None,
            false,
            "DELETE (:Temp)",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("clear(): Promise<MutationResult>"));
        assert!(ts.contains("clear: () =>\n      graph.executePreparedMutation(\"clear\", {})"));
    }

    #[test]
    fn ts_imports_minimal() {
        // Only queries → no MutationResult import
        let stmts = vec![make_info(
            "q",
            PreparedKind::Query,
            &[],
            &[],
            &[],
            None,
            false,
            "RETURN 1",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("QueryResultWithContinuation"));
        assert!(!ts.contains("MutationResult"));
    }

    #[test]
    fn ts_preserve_param_style_keeps_snake_case() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &["user_name"],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $user_name RETURN u.name AS name",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Preserve);
        assert!(ts.contains("export interface FindUserParams {\n  /** wire param: \"user_name\" */\n  user_name: unknown;\n}"));
        assert!(
            ts.contains("find_user(params: FindUserParams): Promise<QueryResultWithContinuation>")
        );
        assert!(ts.contains("graph.executePrepared(\"find_user\", params)"));
    }

    #[test]
    fn ts_camel_param_style_maps_wire_names() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &["user_name"],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $user_name RETURN u.name AS name",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(ts.contains("export interface FindUserParams {\n  /** wire param: \"user_name\" */\n  userName: unknown;\n}"));
        assert!(
            ts.contains("find_user(params: FindUserParams): Promise<QueryResultWithContinuation>")
        );
        assert!(
            ts.contains("graph.executePrepared(\"find_user\", { user_name: params.userName })")
        );
    }

    #[test]
    fn ts_sort_key_names_are_stable_for_digits_and_collisions() {
        let stmts = vec![make_info(
            "find_user",
            PreparedKind::Query,
            &[],
            &["name"],
            &[
                ("1day", "u.one_day"),
                ("user_name", "u.user_name"),
                ("user-name", "u.alt_user_name"),
            ],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        )];
        let ts = generate_ts(&stmts, "abc", JsParamStyle::Camel);
        assert!(
            ts.contains("  /** wire key: \"1day\", expr: \"u.one_day\" */\n  K1day: \"1day\",")
        );
        assert!(ts.contains(
            "  /** wire key: \"user_name\", expr: \"u.user_name\" */\n  UserName: \"user_name\","
        ));
        assert!(ts.contains("  /** wire key: \"user-name\", expr: \"u.alt_user_name\" */\n  UserName2: \"user-name\","));
    }

    #[test]
    fn ts_optional_params_are_optional_in_interface() {
        let mut info = make_info(
            "search",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        );
        info.parameters = vec![
            gleaph_types::PreparedParameterInfo {
                name: "query".into(),
                required: true,
                types: vec![],
                inferred: false,
            },
            gleaph_types::PreparedParameterInfo {
                name: "offset".into(),
                required: false,
                types: vec![],
                inferred: false,
            },
        ];
        let ts = generate_ts(&[info], "abc", JsParamStyle::Camel);
        assert!(ts.contains("export interface SearchParams {\n  /** wire param: \"query\" */\n  query: unknown;\n  /** wire param: \"offset\" */\n  offset?: unknown;\n}"));
        assert!(ts.contains("graph.executePrepared(\"search\", { query: params.query, ...(params.offset !== undefined ? { offset: params.offset } : {}) })"));
    }

    #[test]
    fn ts_description_is_emitted_in_docs() {
        let mut info = make_info(
            "find_user",
            PreparedKind::Query,
            &["name"],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) WHERE u.name = $name RETURN u.name AS name",
        );
        info.description = Some("Find one user by exact name.".into());
        let ts = generate_ts(&[info], "abc", JsParamStyle::Camel);
        assert!(ts.contains("* Find one user by exact name."));
    }

    #[test]
    fn ts_typed_params_emit_native_types() {
        use gleaph_types::PreparedValueType;
        let mut info = make_info(
            "search",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        );
        info.parameters = vec![
            gleaph_types::PreparedParameterInfo {
                name: "min_age".into(),
                required: true,
                types: vec![PreparedValueType::Int64],
                inferred: true,
            },
            gleaph_types::PreparedParameterInfo {
                name: "name".into(),
                required: true,
                types: vec![PreparedValueType::Text],
                inferred: true,
            },
            gleaph_types::PreparedParameterInfo {
                name: "active".into(),
                required: false,
                types: vec![PreparedValueType::Bool],
                inferred: true,
            },
        ];
        let ts = generate_ts(&[info], "abc", JsParamStyle::Camel);
        assert!(ts.contains("minAge: bigint;"), "expected bigint: {ts}");
        assert!(ts.contains("name: string;"), "expected string: {ts}");
        assert!(ts.contains("active?: boolean;"), "expected boolean?: {ts}");
    }

    #[test]
    fn ts_principal_param_imports_principal() {
        use gleaph_types::PreparedValueType;
        let mut info = make_info(
            "by_owner",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "RETURN 1",
        );
        info.parameters = vec![gleaph_types::PreparedParameterInfo {
            name: "owner".into(),
            required: true,
            types: vec![PreparedValueType::Principal],
            inferred: true,
        }];
        let ts = generate_ts(&[info], "abc", JsParamStyle::Camel);
        assert!(
            ts.contains("import { Principal }"),
            "expected Principal import: {ts}"
        );
        assert!(
            ts.contains("owner: Principal;"),
            "expected Principal type: {ts}"
        );
    }

    #[test]
    fn ts_typed_list_params_emit_typed_arrays() {
        use gleaph_types::{PreparedScalarType, PreparedValueType};
        let mut info = make_info(
            "search",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "MATCH (u:User) RETURN u.name AS name",
        );
        info.parameters = vec![
            gleaph_types::PreparedParameterInfo {
                name: "ids".into(),
                required: true,
                types: vec![PreparedValueType::TypedList(PreparedScalarType::Int64)],
                inferred: true,
            },
            gleaph_types::PreparedParameterInfo {
                name: "names".into(),
                required: true,
                types: vec![PreparedValueType::TypedList(PreparedScalarType::Text)],
                inferred: true,
            },
            gleaph_types::PreparedParameterInfo {
                name: "flags".into(),
                required: false,
                types: vec![PreparedValueType::TypedList(PreparedScalarType::Bool)],
                inferred: true,
            },
        ];
        let ts = generate_ts(&[info], "abc", JsParamStyle::Camel);
        assert!(ts.contains("ids: bigint[];"), "expected bigint[]: {ts}");
        assert!(ts.contains("names: string[];"), "expected string[]: {ts}");
        assert!(
            ts.contains("flags?: boolean[];"),
            "expected boolean[]?: {ts}"
        );
    }

    #[test]
    fn ts_typed_list_principal_triggers_import() {
        use gleaph_types::{PreparedScalarType, PreparedValueType};
        let mut info = make_info(
            "by_owners",
            PreparedKind::Query,
            &[],
            &["name"],
            &[],
            None,
            false,
            "RETURN 1",
        );
        info.parameters = vec![gleaph_types::PreparedParameterInfo {
            name: "owners".into(),
            required: true,
            types: vec![PreparedValueType::TypedList(PreparedScalarType::Principal)],
            inferred: true,
        }];
        let ts = generate_ts(&[info], "abc", JsParamStyle::Camel);
        assert!(
            ts.contains("import { Principal }"),
            "expected Principal import: {ts}"
        );
        assert!(
            ts.contains("owners: Principal[];"),
            "expected Principal[]: {ts}"
        );
    }

    #[test]
    fn ts_union_type_emits_union() {
        use gleaph_types::PreparedValueType;
        let mut info = make_info(
            "find",
            PreparedKind::Query,
            &[],
            &["result"],
            &[],
            None,
            false,
            "RETURN 1",
        );
        info.parameters = vec![gleaph_types::PreparedParameterInfo {
            name: "key".into(),
            required: true,
            types: vec![PreparedValueType::Int64, PreparedValueType::Text],
            inferred: true,
        }];
        let ts = generate_ts(&[info], "abc", JsParamStyle::Camel);
        assert!(
            ts.contains("key: bigint | string;"),
            "expected union type: {ts}"
        );
    }
}
