// Generated by gleaph-codegen. Do not edit.

import type { ApiQueryResponse, ApiValue, GraphClient } from "@gleaph/sdk";
import { fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph" as const;

type PreparedResponse<Row> = Omit<ApiQueryResponse, "execution"> & { execution: Omit<ApiQueryResponse["execution"], "rows"> & { rows: Row[] } };

export type PrincipalLike = string | { toText(): string };

/**
 * Find users by their search term.
 */
export interface FindUsersParams {
  /**
   * Text to search for.
   */
  term: string;
}

export interface FindUsersRow {
  user_name: string;
}

export interface PreparedQueries {
  /**
   * Find users by their search term.
   */
  "find-users": (params: FindUsersParams) => Promise<PreparedResponse<FindUsersRow>>;
}

export function withPreparedQueries(client: GraphClient): PreparedQueries {
  return {
    "find-users": async (params) => {
      const encodedParams: Record<string, ApiValue> = {};
      encodedParams["term"] = { Text: params["term"] };
      const response = await client.executePrepared("find-users", encodedParams);
      return { ...response, execution: { ...response.execution, rows: response.execution.rows.map((row) => ({
        user_name: fromApiValue(row["user_name"]) as string,
      })) } };
    },
  };
}
