// Generated by gleaph-codegen. Do not edit.

import { fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph";

export function withPreparedQueries(client) {
  return {
    /**
     * Find users by their search term.
     */
    "find-users": async (params) => {
      const encodedParams = {};
      encodedParams["term"] = { Text: params["term"] };
      const response = await client.executePrepared("find-users", encodedParams);
      return { ...response, rows: response.rows.map((row) => ({
        user_name: fromApiValue(row["user_name"]),
      })) };
    },
  };
}
