// Generated by gleaph-codegen. Do not edit.

import type { ApiValue, GleaphClient, GleaphTransport, GleaphTransportOptions, GqlQueryResult } from "@gleaph/sdk";
import { GleaphClientWrapper, createGleaphClient, createGleaphClientFromTransport, toApiValue, fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph" as const;

type PreparedResponse<Row> = Omit<GqlQueryResult, "rows"> & { rows: Row[] };

export type PrincipalLike = string | { toText(): string };

/**
 * Find users by their search term.
 */
export interface FindUsersParams {
  /**
   * Text to search for.
   */
  term: string;
}

export interface FindUsersRow {
  user_name: string;
}

export interface PreparedQueries {
  findUsers(params: FindUsersParams): Promise<PreparedResponse<FindUsersRow>>;
}

export class PreparedGleaphClient extends GleaphClientWrapper implements PreparedQueries {
  constructor(client: GleaphClient) {
    super(client);
  }

  /**
   * Find users by their search term.
   */
  async findUsers(params: FindUsersParams): Promise<PreparedResponse<FindUsersRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["term"] = toApiValue(params["term"], "Text");
    const response = await this.preparedQuery("find-users", encodedParams);
    return { ...response, rows: response.rows.map((row) => ({
      user_name: fromApiValue(row["user_name"]) as string,
    })) };
  }
}

export function withPreparedQueries(client: GleaphClient): PreparedGleaphClient {
  return new PreparedGleaphClient(client);
}

/** Construct a client bound to the graph's prepared operations and dynamic GQL. */
export async function createPreparedGleaphClient(options: GleaphTransportOptions): Promise<PreparedGleaphClient> {
  return withPreparedQueries(await createGleaphClient(options));
}

/** Construct a prepared client over an existing SDK transport. */
export function createPreparedGleaphClientFromTransport(transport: GleaphTransport): PreparedGleaphClient {
  return withPreparedQueries(createGleaphClientFromTransport(transport));
}
