// Generated by gleaph-codegen. Do not edit.

import { GleaphClientWrapper, createGleaphClient, createGleaphClientFromTransport, toApiValue, fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph";

export class PreparedGleaphClient extends GleaphClientWrapper {
  constructor(client) {
    super(client);
  }

  /**
   * Find users by their search term.
   */
  async findUsers(params) {
    const encodedParams = {};
    encodedParams["term"] = toApiValue(params["term"], "Text");
    const response = await this.preparedQuery("find-users", encodedParams);
    return { ...response, rows: response.rows.map((row) => ({
      user_name: fromApiValue(row["user_name"]),
    })) };
  }
}

export function withPreparedQueries(client) {
  return new PreparedGleaphClient(client);
}

/** Construct a client bound to the graph's prepared operations and dynamic GQL. */
export async function createPreparedGleaphClient(options) {
  return withPreparedQueries(await createGleaphClient(options));
}

/** Construct a prepared client over an existing SDK transport. */
export function createPreparedGleaphClientFromTransport(transport) {
  return withPreparedQueries(createGleaphClientFromTransport(transport));
}
