//! Rust canister output profile for typed prepared operations.
//!
//! Generated code binds typed prepared operations directly to the `gleaph-cdk` client: a
//! `Prepared` marker type and a `PreparedExt` extension trait implemented for
//! `GleaphClient<Prepared>` wrap the Router's `prepared_query` / `prepared_mutate` endpoints.

use super::client::{rust_field, rust_type};
use crate::common::append_line_doc;
use crate::ir::CodegenIr;
use crate::ir::normalize_manifest;
use crate::{ManifestError, OperationKind, PreparedManifest};

/// Generate Rust canister declarations and a `PreparedExt` operations trait.
pub fn generate_rust_canister(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = normalize_manifest(manifest)?;
    Ok(generate_ir(&ir))
}

fn generate_ir(ir: &CodegenIr) -> String {
    let has_gql_params = ir
        .operations
        .iter()
        .any(|operation_ir| !operation_ir.operation.parameters.is_empty());
    let mut out = String::from(
        "//! Generated by gleaph-codegen. Do not edit.\n\n\
         #![allow(dead_code)]\n\n\
         use gleaph_cdk::GqlParams;\n",
    );

    if has_gql_params {
        out.push_str("use gleaph_cdk::GqlValue;\n");
    }
    out.push_str(
        "use gleaph_cdk::candid::CandidType;\n\
         use gleaph_cdk::serde::{Deserialize, Serialize};\n\
         use std::future::Future;\n\n",
    );
    out.push_str(&format!(
        "pub const GLEAPH_GRAPH_ID: &str = {:?};\n\n",
        ir.graph_id
    ));
    out.push_str(
        r#"/// Result returned by a prepared operation.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("gleaph_cdk::candid")]
#[serde(crate = "gleaph_cdk::serde")]
pub struct PreparedResponse<Row> {
    /// Number of rows returned by the Router.
    pub row_count: u64,
    /// Typed rows decoded from the Router response.
    pub rows: Vec<Row>,
}

"#,
    );

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        if let Some(description) = &operation.description {
            append_line_doc(&mut out, "", "///", description);
        }
        out.push_str(&format!(
            "/// Parameters for the prepared operation {}.\n#[derive(Clone, Debug)]\npub struct {}Params {{\n",
            operation.name, type_name
        ));
        for parameter in &operation.parameters {
            let field = rust_field(&parameter.name);
            let mut ty = canister_param_rust_type(&parameter.semantic_type);
            if !parameter.required || parameter.nullable {
                ty = format!("Option<{ty}>");
            }
            if let Some(description) = &parameter.description {
                append_line_doc(&mut out, "    ", "///", description);
            }
            out.push_str(&format!(
                "    /// Wire parameter {}.\n    pub {field}: {ty},\n",
                parameter.name
            ));
        }
        out.push_str("}\n\n");
        // Every manifest semantic type is expressible as a logical GQL value, so the typed
        // parameter conversion is always generated.
        let entries = operation
            .parameters
            .iter()
            .map(|parameter| {
                let field = rust_field(&parameter.name);
                let value = parameter_value_expression(&format!("self.{field}"), parameter);
                format!("({:?}.to_string(), {value})", parameter.name)
            })
            .collect::<Vec<_>>();
        let one_line = format!("Ok(vec![{}])", entries.join(", "));
        let params_body = if !super::format::exceeds_width(&one_line, super::format::ARRAY_WIDTH) {
            format!("        {one_line}\n")
        } else {
            format!(
                "        Ok(vec![\n            {},\n        ])\n",
                entries.join(",\n            ")
            )
        };
        out.push_str(&format!(
            "impl {}Params {{\n    /// Convert typed parameters to ordered logical GQL parameters.\n    pub fn into_gql_params(self) -> Result<GqlParams, gleaph_cdk::CallError> {{\n{params_body}    }}\n}}\n\n",
            type_name
        ));
        out.push_str(&format!(
            "/// One result row from the prepared operation {}.\n#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]\n#[candid_path(\"gleaph_cdk::candid\")]\n#[serde(crate = \"gleaph_cdk::serde\")]\npub struct {}Row {{\n",
            operation.name, type_name
        ));
        for column in &operation.result.columns {
            let field = rust_field(&column.name);
            let ty = if column.nullable {
                format!("Option<{}>", canister_rust_type(&column.semantic_type))
            } else {
                canister_rust_type(&column.semantic_type)
            };
            out.push_str(&format!(
                "    /// Wire column {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                column.name, column.name
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str(
        r#"/// Marker enabling generated prepared operations on `gleaph_cdk::GleaphClient<Prepared>`.
pub struct Prepared;

/// Prepared operations generated from the manifest, available on
/// `gleaph_cdk::GleaphClient<Prepared>`.
///
/// Import this trait to call prepared operations on a client created with
/// `gleaph_cdk::GleaphClient::with_prepared::<Prepared>`.
pub trait PreparedExt {
"#,
    );
    let trait_methods = ir
        .operations
        .iter()
        .map(|operation_ir| {
            let operation = &operation_ir.operation;
            let method = rust_field(&operation.name);
            let params = &operation_ir.params_type_name;
            let row = &operation_ir.row_type_name;
            let key_line = match operation.kind {
                OperationKind::Query => ",",
                OperationKind::Update => ",\n        client_mutation_key: impl Into<String>,",
            };
            format!(
                "    /// Execute the prepared operation {}.\n    fn {method}(\n        &self,\n        params: {params}{key_line}\n    ) -> impl Future<Output = Result<PreparedResponse<{row}>, gleaph_cdk::CallError>> + Send;",
                operation.name
            )
        })
        .collect::<Vec<_>>();
    out.push_str(&trait_methods.join("\n\n"));
    out.push_str("\n}\n\n");
    out.push_str("impl PreparedExt for gleaph_cdk::GleaphClient<Prepared> {\n");
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method = rust_field(&operation.name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let key_line = match operation.kind {
            OperationKind::Query => ",",
            OperationKind::Update => ",\n        client_mutation_key: impl Into<String>,",
        };
        let call_args = match operation.kind {
            OperationKind::Query => format!(
                "{name:?}, params, None, gleaph_cdk::ReadMode::Eventual",
                name = operation.name
            ),
            OperationKind::Update => {
                format!(
                    "{name:?}, params, client_mutation_key",
                    name = operation.name
                )
            }
        };
        let router_method = match operation.kind {
            OperationKind::Query => "prepared_query",
            OperationKind::Update => "prepared_mutate",
        };
        let encode = encode_statement();
        let call = call_statement(router_method, &call_args);
        let rows = rows_field(row);
        out.push_str(&format!(
            "    async fn {method}(\n        &self,\n        params: {params}{key_line}\n    ) -> Result<PreparedResponse<{row}>, gleaph_cdk::CallError> {{\n        {encode}\n        {call}\n        Ok(PreparedResponse {{\n            row_count: result.row_count,\n            {rows}\n        }})\n    }}\n\n",
        ));
    }
    if out.ends_with("\n\n") {
        out.pop();
    }
    out.push_str("}\n");
    out
}

/// One-line form of the parameter encoding statement.
const ENCODE_ONE_LINE: &str = "let params = gleaph_cdk::encode_gql_params(params).map_err(|error| gleaph_cdk::CallError::Decode { message: format!(\"failed to encode GQL params: {error:?}\") })?;";

/// Render the parameter conversion and encoding statements, wrapping the encode closure like
/// rustfmt when the one-line form exceeds the default width.
///
/// `into_gql_params` returns a [`Result`], so the generated operation propagates parameter
/// conversion errors with `?` before encoding.
fn encode_statement() -> String {
    let encode = if super::format::exceeds_width(ENCODE_ONE_LINE, super::format::MAX_WIDTH - 8) {
        "let params = gleaph_cdk::encode_gql_params(params).map_err(|error| {\n            gleaph_cdk::CallError::Decode {\n                message: format!(\"failed to encode GQL params: {error:?}\"),\n            }\n        })?;"
    } else {
        ENCODE_ONE_LINE
    };
    format!("let params = params.into_gql_params()?;\n        {encode}")
}

/// Render the Router call, wrapping the method chain like rustfmt when the chain or the
/// full statement exceeds its width threshold.
fn call_statement(method: &str, call_args: &str) -> String {
    let one_line = format!("let result = self.{method}({call_args}).await?;");
    let chain = format!("self.{method}({call_args}).await");
    let fits = !super::format::exceeds_width(&chain, super::format::CHAIN_WIDTH)
        && !super::format::exceeds_width(&one_line, super::format::MAX_WIDTH - 8);
    if fits {
        one_line
    } else {
        format!("let result = self\n            .{method}({call_args})\n            .await?;")
    }
}

/// Render the `rows` field, wrapping the decoding chain like rustfmt when the chain or the
/// full field exceeds its width threshold.
fn rows_field(row: &str) -> String {
    let one_line = format!("rows: result.decode_serde_rows::<{row}>()?.unwrap_or_default(),");
    let chain = format!("result.decode_serde_rows::<{row}>()?.unwrap_or_default()");
    let fits = !super::format::exceeds_width(&chain, super::format::CHAIN_WIDTH)
        && !super::format::exceeds_width(&one_line, super::format::MAX_WIDTH - 12);
    if fits {
        one_line
    } else {
        format!(
            "rows: result\n                .decode_serde_rows::<{row}>()?\n                .unwrap_or_default(),"
        )
    }
}

fn parameter_value_expression(access: &str, parameter: &crate::Parameter) -> String {
    if parameter.required && !parameter.nullable {
        return gql_value_expression(access, &parameter.semantic_type)
            .expect("parameter conversion was checked before rendering");
    }

    let value = gql_value_expression("value", &parameter.semantic_type)
        .expect("parameter conversion was checked before rendering");
    format!("match {access} {{ Some(value) => {value}, None => GqlValue::Null }}")
}

fn gql_value_expression(access: &str, semantic_type: &crate::SemanticType) -> Option<String> {
    let value = match semantic_type {
        crate::SemanticType::Null => "GqlValue::Null".to_string(),
        crate::SemanticType::Bool => format!("GqlValue::Bool({access})"),
        crate::SemanticType::Int8 => format!("GqlValue::Int8({access})"),
        crate::SemanticType::Int16 => format!("GqlValue::Int16({access})"),
        crate::SemanticType::Int32 => format!("GqlValue::Int32({access})"),
        crate::SemanticType::Int64 => format!("GqlValue::Int64({access})"),
        crate::SemanticType::Uint8 => format!("GqlValue::Uint8({access})"),
        crate::SemanticType::Uint16 => format!("GqlValue::Uint16({access})"),
        crate::SemanticType::Uint32 => format!("GqlValue::Uint32({access})"),
        crate::SemanticType::Uint64 => format!("GqlValue::Uint64({access})"),
        crate::SemanticType::Int128 => format!("GqlValue::Int128({access})"),
        crate::SemanticType::Uint128 => format!("GqlValue::Uint128({access})"),
        crate::SemanticType::Int256 => format!("GqlValue::from({access})"),
        crate::SemanticType::Uint256 => format!("GqlValue::from({access})"),
        crate::SemanticType::Float16 => format!("GqlValue::from({access})"),
        crate::SemanticType::Float32 => format!("GqlValue::Float32({access})"),
        crate::SemanticType::Float64 => format!("GqlValue::Float64({access})"),
        crate::SemanticType::Float128 => format!("GqlValue::Float128({access})"),
        crate::SemanticType::Float256 => format!("GqlValue::Float256({access})"),
        crate::SemanticType::Decimal => format!("GqlValue::from({access})"),
        crate::SemanticType::Text => format!("GqlValue::Text({access})"),
        crate::SemanticType::Bytes => format!("GqlValue::Bytes({access})"),
        crate::SemanticType::Principal => {
            format!("GqlValue::Extension(Box::new(gleaph_cdk::PrincipalValue({access})))")
        }
        crate::SemanticType::Date => format!("GqlValue::from({access})"),
        crate::SemanticType::Time => format!("GqlValue::from({access})"),
        crate::SemanticType::LocalTime => format!("GqlValue::from({access})"),
        crate::SemanticType::DateTime | crate::SemanticType::LocalDateTime => {
            format!("GqlValue::from({access})")
        }
        crate::SemanticType::ZonedDateTime => format!("GqlValue::from({access})"),
        crate::SemanticType::ZonedTime => format!("GqlValue::from({access})"),
        crate::SemanticType::Duration => format!("GqlValue::from({access})"),
        crate::SemanticType::Record { .. } => format!("GqlValue::Record({access})"),
        crate::SemanticType::Path => format!(
            "GqlValue::Path({access}.into_iter().map(gleaph_cdk::PathElement::into_gql).collect())"
        ),
        crate::SemanticType::List { element } => {
            let element = gql_value_expression("value", element)?;
            format!("GqlValue::List({access}.into_iter().map(|value| {element}).collect())")
        }
    };
    Some(value)
}

fn canister_rust_type(semantic_type: &crate::SemanticType) -> String {
    match semantic_type {
        crate::SemanticType::Int256 => "gleaph_cdk::GqlInt256".to_string(),
        crate::SemanticType::Uint256 => "gleaph_cdk::GqlUint256".to_string(),
        crate::SemanticType::Decimal => "gleaph_cdk::GqlDecimal".to_string(),
        crate::SemanticType::Principal => "gleaph_cdk::candid::Principal".to_string(),
        crate::SemanticType::Float16 => "gleaph_cdk::GqlFloat16".to_string(),
        crate::SemanticType::Float128 => "gleaph_cdk::Float128".to_string(),
        crate::SemanticType::Float256 => "gleaph_cdk::Float256".to_string(),
        crate::SemanticType::Date => "gleaph_cdk::GqlDate".to_string(),
        crate::SemanticType::Time => "gleaph_cdk::GqlTime".to_string(),
        crate::SemanticType::LocalTime => "gleaph_cdk::GqlLocalTime".to_string(),
        crate::SemanticType::DateTime => "gleaph_cdk::GqlDateTime".to_string(),
        crate::SemanticType::LocalDateTime => "gleaph_cdk::GqlLocalDateTime".to_string(),
        crate::SemanticType::ZonedDateTime => "gleaph_cdk::GqlZonedDateTime".to_string(),
        crate::SemanticType::ZonedTime => "gleaph_cdk::GqlZonedTime".to_string(),
        crate::SemanticType::Duration => "gleaph_cdk::GqlDuration".to_string(),
        crate::SemanticType::Path => "Vec<gleaph_cdk::PathElement>".to_string(),
        crate::SemanticType::Record { .. } => {
            "std::collections::BTreeMap<String, gleaph_cdk::serde_json::Value>".to_string()
        }
        crate::SemanticType::List { element } => {
            format!("Vec<{}>", canister_rust_type(element))
        }
        _ => rust_type(semantic_type),
    }
}

fn canister_param_rust_type(semantic_type: &crate::SemanticType) -> String {
    match semantic_type {
        crate::SemanticType::Float128 => "f128".to_string(),
        crate::SemanticType::Float256 => "gleaph_cdk::GqlFloat256".to_string(),
        crate::SemanticType::Record { .. } => "gleaph_cdk::GqlRecord".to_string(),
        crate::SemanticType::List { element } => {
            format!("Vec<{}>", canister_param_rust_type(element))
        }
        _ => canister_rust_type(semantic_type),
    }
}
