//! Rust application-client output profile for prepared-query adapters.
//!
//! The generated module contains operation-specific parameter and row declarations plus a small
//! executor trait. Transport, response decoding, and error policy remain owned by the Rust
//! runtime that implements the trait.

use crate::common::append_line_doc;
use crate::ir::normalize_manifest;
use crate::{CodegenIr, ManifestError, OperationKind, PreparedManifest, SemanticType};

/// Generate Rust declarations and an executor facade for a prepared-query manifest.
pub fn generate_rust(manifest: &PreparedManifest) -> Result<String, ManifestError> {
    let ir = normalize_manifest(manifest)?;
    validate_runtime_features(&ir)?;
    Ok(generate_rust_ir(&ir))
}

fn validate_runtime_features(ir: &CodegenIr) -> Result<(), ManifestError> {
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        if operation.supports_consistency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "read consistency options",
            });
        }
        if operation.supports_idempotency {
            return Err(ManifestError::UnsupportedRuntimeFeature {
                operation: operation.name.clone(),
                feature: "idempotent updates",
            });
        }
    }
    Ok(())
}

fn generate_rust_ir(ir: &CodegenIr) -> String {
    let mut out = String::from(
        "//! Generated by gleaph-codegen. Do not edit.\n\n\
         #![allow(dead_code)]\n\n\
         use serde::de::DeserializeOwned;\n\
         use serde::{Deserialize, Serialize};\n\
         use std::collections::BTreeMap;\n\
         use std::future::Future;\n\
         use std::pin::Pin;\n\n",
    );
    out.push_str(&format!(
        "pub const GLEAPH_GRAPH_ID: &str = {:?};\n\n",
        ir.graph_id
    ));
    out.push_str(
        r#"/// Sort specification accepted by a generated prepared query.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedSortSpec {
    /// Stable sort-key identifier.
    pub key: String,
    /// Sort direction.
    pub direction: String,
}

/// Response envelope decoded by a runtime executor.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedResponse<Row> {
    /// Query execution metadata.
    pub explain: serde_json::Value,
    /// Planner summary.
    pub plan_summary: serde_json::Value,
    /// Execution result containing typed rows.
    pub execution: PreparedExecution<Row>,
}

/// Typed execution result inside a prepared response.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedExecution<Row> {
    /// Rows returned by the operation.
    pub rows: Vec<Row>,
    /// Non-fatal execution warnings.
    pub warnings: Vec<String>,
    /// Runtime-specific execution summary.
    pub summary: serde_json::Value,
}

/// Runtime boundary implemented by the selected Rust SDK or canister adapter.
pub trait PreparedExecutor {
    /// Error returned by the runtime boundary.
    type Error;

    /// Execute a read-only prepared operation.
    fn execute_query<'a, Row>(
        &'a self,
        name: &'static str,
        params: BTreeMap<String, serde_json::Value>,
        sort: Option<Vec<PreparedSortSpec>>,
    ) -> Pin<Box<dyn Future<Output = Result<PreparedResponse<Row>, Self::Error>> + 'a>>
    where
        Row: DeserializeOwned + 'a;

    /// Execute a mutating prepared operation.
    fn execute_update<'a, Row>(
        &'a self,
        name: &'static str,
        params: BTreeMap<String, serde_json::Value>,
    ) -> Pin<Box<dyn Future<Output = Result<PreparedResponse<Row>, Self::Error>> + 'a>>
    where
        Row: DeserializeOwned + 'a;
}

"#,
    );
    out.push_str(
        r#"/// Date-time representation used by generated Rust declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedDateTime {
    /// Unix seconds.
    pub seconds: i64,
    /// Nanoseconds within the second.
    pub nanos: u32,
}

/// Zoned date-time representation used by generated Rust declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedZonedDateTime {
    /// Unix seconds.
    pub seconds: i64,
    /// Nanoseconds within the second.
    pub nanos: u32,
    /// UTC offset in seconds.
    pub offset_seconds: i32,
}

/// Zoned time representation used by generated Rust declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedZonedTime {
    /// Nanoseconds since midnight.
    pub nanos: u64,
    /// UTC offset in seconds.
    pub offset_seconds: i32,
}

/// Duration representation used by generated Rust declarations.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedDuration {
    /// Calendar months.
    pub months: i32,
    /// Nanoseconds.
    pub nanos: i64,
}

"#,
    );

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        if let Some(description) = &operation.description {
            append_line_doc(&mut out, "", "///", description);
        }
        out.push_str(&format!(
            "/// Parameters for the `{}` prepared operation.\n#[derive(Clone, Debug, Deserialize, Serialize)]\npub struct {}Params {{\n",
            operation.name, type_name
        ));
        for parameter in &operation.parameters {
            let field = rust_field(&parameter.name);
            let ty = rust_type(&parameter.semantic_type);
            let ty = if parameter.required {
                if parameter.nullable {
                    format!("Option<{ty}>")
                } else {
                    ty
                }
            } else {
                format!("Option<{ty}>")
            };
            if let Some(description) = &parameter.description {
                append_line_doc(&mut out, "    ", "///", description);
            }
            out.push_str(&format!(
                "    /// Wire parameter `{}`.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                parameter.name, parameter.name
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "/// One result row from the `{}` prepared operation.\n#[derive(Clone, Debug, Deserialize, Serialize)]\npub struct {}Row {{\n",
            operation.name, type_name
        ));
        for column in &operation.result.columns {
            let field = rust_field(&column.name);
            let ty = rust_type(&column.semantic_type);
            let ty = if column.nullable {
                format!("Option<{ty}>")
            } else {
                ty
            };
            out.push_str(&format!(
                "    /// Wire column `{}`.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                column.name, column.name
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str("/// Typed facade over a [`PreparedExecutor`].\npub struct PreparedQueries<'a, E: PreparedExecutor> {\n    executor: &'a E,\n}\n\nimpl<'a, E: PreparedExecutor> PreparedQueries<'a, E> {\n    /// Bind generated operations to a runtime executor.\n    pub fn new(executor: &'a E) -> Self {\n        Self { executor }\n    }\n\n");
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method = rust_field(&operation.name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let executor_method = match operation.kind {
            OperationKind::Query => "execute_query",
            OperationKind::Update => "execute_update",
        };
        let mut method_args = Vec::new();
        if !operation.parameters.is_empty() {
            method_args.push(format!("params: {params}"));
        }
        if !operation.allowed_sorts.is_empty() {
            method_args.push("sort: Option<Vec<PreparedSortSpec>>".to_string());
        }
        let method_signature = if method_args.is_empty() {
            "(&self)".to_string()
        } else {
            format!(
                "(\n        &self,\n        {},\n    )",
                method_args.join(",\n        ")
            )
        };
        let params_body = if operation.parameters.is_empty() {
            "        let params = BTreeMap::new();\n".to_string()
        } else {
            "        let params = serde_json::to_value(params)\n            .expect(\"generated parameter struct must serialize\")\n            .as_object()\n            .expect(\"generated parameter struct must serialize to an object\")\n            .clone()\n            .into_iter()\n            .collect();\n"
                .to_string()
        };
        let call = if operation.kind == OperationKind::Query {
            let one_line = format!(
                "self.executor.{executor_method}::<{row}>({:?}, params, {}).await",
                operation.name,
                if operation.allowed_sorts.is_empty() {
                    "None"
                } else {
                    "sort"
                }
            );
            if super::format::exceeds_width(
                &one_line,
                super::format::FN_CALL_WIDTH.max(super::format::CHAIN_WIDTH),
            ) || super::format::exceeds_default_width(&one_line)
            {
                format!(
                    "self.executor\n            .{executor_method}::<{row}>({:?}, params, {})\n            .await",
                    operation.name,
                    if operation.allowed_sorts.is_empty() {
                        "None"
                    } else {
                        "sort"
                    }
                )
            } else {
                one_line
            }
        } else {
            let one_line = format!(
                "self.executor.{executor_method}::<{row}>({:?}, params).await",
                operation.name
            );
            if super::format::exceeds_width(
                &one_line,
                super::format::FN_CALL_WIDTH.max(super::format::CHAIN_WIDTH),
            ) || super::format::exceeds_default_width(&one_line)
            {
                format!(
                    "self.executor\n            .{executor_method}::<{row}>({:?}, params)\n            .await",
                    operation.name
                )
            } else {
                one_line
            }
        };
        if let Some(description) = &operation.description {
            append_line_doc(&mut out, "    ", "///", description);
        }
        out.push_str(&format!(
            "    /// Execute the `{}` prepared operation.\n    pub async fn {method}{method_signature} -> Result<PreparedResponse<{row}>, E::Error> {{\n{params_body}        {call}\n    }}\n\n",
            operation.name
        ));
    }
    if out.ends_with("\n\n") {
        out.pop();
    }
    out.push_str("}\n");
    out
}

pub(crate) fn rust_field(name: &str) -> String {
    let mut result = String::new();
    for (index, c) in name.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' {
            if index == 0 && c.is_ascii_digit() {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push('_');
        }
    }
    if result.is_empty() {
        "value".to_string()
    } else if matches!(
        result.as_str(),
        "type" | "match" | "ref" | "self" | "Self" | "crate"
    ) {
        format!("r#{result}")
    } else {
        result
    }
}

pub(crate) fn rust_type(semantic_type: &SemanticType) -> String {
    match semantic_type {
        SemanticType::Null => "()".to_string(),
        SemanticType::Bool => "bool".to_string(),
        SemanticType::Int8 => "i8".to_string(),
        SemanticType::Int16 => "i16".to_string(),
        SemanticType::Int32 => "i32".to_string(),
        SemanticType::Int64 => "i64".to_string(),
        SemanticType::Uint8 => "u8".to_string(),
        SemanticType::Uint16 => "u16".to_string(),
        SemanticType::Uint32 => "u32".to_string(),
        SemanticType::Uint64 => "u64".to_string(),
        SemanticType::Int128 => "i128".to_string(),
        SemanticType::Uint128 => "u128".to_string(),
        SemanticType::Int256 | SemanticType::Uint256 | SemanticType::Decimal => {
            "String".to_string()
        }
        SemanticType::Float16 => "u16".to_string(),
        SemanticType::Float32 => "f32".to_string(),
        SemanticType::Float64 => "f64".to_string(),
        SemanticType::Float128 | SemanticType::Float256 => "Vec<u8>".to_string(),
        SemanticType::Text => "String".to_string(),
        SemanticType::Bytes => "Vec<u8>".to_string(),
        SemanticType::Date => "i32".to_string(),
        SemanticType::Time | SemanticType::LocalTime => "u64".to_string(),
        SemanticType::DateTime | SemanticType::LocalDateTime => "PreparedDateTime".to_string(),
        SemanticType::ZonedDateTime => "PreparedZonedDateTime".to_string(),
        SemanticType::ZonedTime => "PreparedZonedTime".to_string(),
        SemanticType::Duration => "PreparedDuration".to_string(),
        SemanticType::Principal => "String".to_string(),
        SemanticType::List { element } => format!("Vec<{}>", rust_type(element)),
        SemanticType::Path => "Vec<gleaph_gql_params::PathElement>".to_string(),
        SemanticType::Record { .. } => "BTreeMap<String, serde_json::Value>".to_string(),
    }
}
