//! Shared Rust renderer for the canister and client prepared-operation profiles.
//!
//! The Rust canister and Rust application-client profiles differ only in the runtime they bind
//! to: `gleaph_cdk` (canister inter-canister calls) versus `gleaph_sdk` (application `ic-agent`
//! transport). Every generated construct — parameter/row type mapping, GQL parameter conversion,
//! the `PreparedResponse` envelope, the `PreparedExt` trait, and its `GleaphClient<Prepared>`
//! implementation — is identical except for the runtime path and whether the module is returned
//! over a Candid interface. This module owns that shared renderer so the two profiles cannot
//! drift.

use super::client::rust_field;
use crate::common::append_line_doc;
use crate::ir::CodegenIr;
use crate::{ManifestError, OperationKind, PreparedManifest, SemanticType};

/// Which runtime a generated Rust module binds to.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RuntimeProfile {
    /// Rust module path to the SDK, e.g. `gleaph_cdk` or `gleaph_sdk`.
    pub path: &'static str,
    /// Emit `CandidType` derives on row and envelope types. Canisters return prepared rows over
    /// their Candid interface; application clients only deserialize locally.
    pub candid_row_derive: bool,
}

/// Render a full `PreparedExt` module for `profile` from a prepared manifest.
pub fn generate_rust_prepared(
    manifest: &PreparedManifest,
    profile: RuntimeProfile,
) -> Result<String, ManifestError> {
    let ir = crate::ir::normalize_manifest(manifest)?;
    Ok(generate_ir(&ir, profile))
}

fn generate_ir(ir: &CodegenIr, profile: RuntimeProfile) -> String {
    let rt = profile.path;
    let has_gql_params = ir
        .operations
        .iter()
        .any(|operation_ir| !operation_ir.operation.parameters.is_empty());
    let mut out = String::from(
        "//! Generated by gleaph-codegen. Do not edit.\n\n\
         #![allow(dead_code)]\n\n",
    );
    if profile.candid_row_derive {
        out.push_str(&format!(
            "use {rt}::candid::CandidType;\n\
             use {rt}::serde::{{Deserialize, Serialize}};\n",
        ));
    } else {
        out.push_str("use serde::{Deserialize, Serialize};\n");
    }
    out.push_str(&format!("use {rt}::GqlParams;\n"));
    if has_gql_params {
        out.push_str(&format!("use {rt}::GqlValue;\n"));
    }
    out.push_str("use std::future::Future;\n\n");
    out.push_str(&format!(
        "pub const GLEAPH_GRAPH_ID: &str = {:?};\n\n",
        ir.graph_id
    ));
    if profile.candid_row_derive {
        out.push_str(&format!(
            r#"/// Result returned by a prepared operation.
#[derive(Clone, Debug, Deserialize, Serialize, CandidType)]
#[candid_path("{rt}::candid")]
#[serde(crate = "{rt}::serde")]
pub struct PreparedResponse<Row> {{
    /// Number of rows returned by the Router.
    pub row_count: u64,
    /// Typed rows decoded from the Router response.
    pub rows: Vec<Row>,
}}

"#,
        ));
    } else {
        out.push_str(
            r#"/// Result returned by a prepared operation.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedResponse<Row> {
    /// Number of rows returned by the Router.
    pub row_count: u64,
    /// Typed rows decoded from the Router response.
    pub rows: Vec<Row>,
}

"#,
        );
    }

    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let type_name = &operation_ir.type_name;
        if let Some(description) = &operation.description {
            append_line_doc(&mut out, "", "///", description);
        }
        out.push_str(&format!(
            "/// Parameters for the prepared operation {}.\n#[derive(Clone, Debug)]\npub struct {}Params {{\n",
            operation.name, type_name
        ));
        for parameter in &operation.parameters {
            let field = rust_field(&parameter.name);
            let mut ty = param_rust_type(&parameter.semantic_type, rt);
            if !parameter.required || parameter.nullable {
                ty = format!("Option<{ty}>");
            }
            if let Some(description) = &parameter.description {
                append_line_doc(&mut out, "    ", "///", description);
            }
            out.push_str(&format!(
                "    /// Wire parameter {}.\n    pub {field}: {ty},\n",
                parameter.name
            ));
        }
        out.push_str("}\n\n");
        // Every manifest semantic type is expressible as a logical GQL value, so the typed
        // parameter conversion is always generated.
        let entries = operation
            .parameters
            .iter()
            .map(|parameter| {
                let field = rust_field(&parameter.name);
                let value = parameter_value_expression(&format!("self.{field}"), parameter, rt);
                format!("({:?}.to_string(), {value})", parameter.name)
            })
            .collect::<Vec<_>>();
        let one_line = format!("Ok(vec![{}])", entries.join(", "));
        let params_body = if !super::format::exceeds_width(&one_line, super::format::ARRAY_WIDTH) {
            format!("        {one_line}\n")
        } else {
            format!(
                "        Ok(vec![\n            {},\n        ])\n",
                entries.join(",\n            ")
            )
        };
        out.push_str(&format!(
            "impl {}Params {{\n    /// Convert typed parameters to ordered logical GQL parameters.\n    pub fn into_gql_params(self) -> Result<GqlParams, {rt}::CallError> {{\n{params_body}    }}\n}}\n\n",
            type_name
        ));
        let row_derive = if profile.candid_row_derive {
            format!(
                "Clone, Debug, Deserialize, Serialize, CandidType\n#[candid_path(\"{rt}::candid\")]\n#[serde(crate = \"{rt}::serde\")]"
            )
        } else {
            "Clone, Debug, Deserialize, Serialize".to_string()
        };
        out.push_str(&format!(
            "/// One result row from the prepared operation {}.\n#[derive({row_derive})]\npub struct {}Row {{\n",
            operation.name, type_name
        ));
        for column in &operation.result.columns {
            let field = rust_field(&column.name);
            let ty = if column.nullable {
                format!("Option<{}>", row_rust_type(&column.semantic_type, rt))
            } else {
                row_rust_type(&column.semantic_type, rt)
            };
            out.push_str(&format!(
                "    /// Wire column {}.\n    #[serde(rename = {:?})]\n    pub {field}: {ty},\n",
                column.name, column.name
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str(&format!(
        r#"/// Marker enabling generated prepared operations on `{rt}::GleaphClient<Prepared>`.
pub struct Prepared;

/// Prepared operations generated from the manifest, available on
/// `{rt}::GleaphClient<Prepared>`.
///
/// Import this trait to call prepared operations on a client created with
/// `{rt}::GleaphClient::with_prepared::<Prepared>`.
pub trait PreparedExt {{
"#,
    ));
    let trait_methods = ir
        .operations
        .iter()
        .map(|operation_ir| {
            let operation = &operation_ir.operation;
            let method = rust_field(&operation.name);
            let params = &operation_ir.params_type_name;
            let row = &operation_ir.row_type_name;
            let key_line = match operation.kind {
                OperationKind::Query => ",",
                OperationKind::Update => ",\n        client_mutation_key: impl Into<String>,",
            };
            format!(
                "    /// Execute the prepared operation {}.\n    fn {method}(\n        &self,\n        params: {params}{key_line}\n    ) -> impl Future<Output = Result<PreparedResponse<{row}>, {rt}::CallError>> + Send;",
                operation.name
            )
        })
        .collect::<Vec<_>>();
    out.push_str(&trait_methods.join("\n\n"));
    out.push_str("\n}\n\n");
    out.push_str(&format!(
        "impl PreparedExt for {rt}::GleaphClient<Prepared> {{\n"
    ));
    for operation_ir in &ir.operations {
        let operation = &operation_ir.operation;
        let method = rust_field(&operation.name);
        let params = &operation_ir.params_type_name;
        let row = &operation_ir.row_type_name;
        let key_line = match operation.kind {
            OperationKind::Query => ",",
            OperationKind::Update => ",\n        client_mutation_key: impl Into<String>,",
        };
        let call_args = match operation.kind {
            OperationKind::Query => format!(
                "{name:?}, params, None, {rt}::ReadMode::Eventual",
                name = operation.name
            ),
            OperationKind::Update => {
                format!(
                    "{name:?}, params, client_mutation_key",
                    name = operation.name
                )
            }
        };
        let router_method = match operation.kind {
            OperationKind::Query => "prepared_query",
            OperationKind::Update => "prepared_mutate",
        };
        let encode = encode_statement(rt);
        let call = call_statement(router_method, &call_args);
        let rows = rows_field(row);
        out.push_str(&format!(
            "    async fn {method}(\n        &self,\n        params: {params}{key_line}\n    ) -> Result<PreparedResponse<{row}>, {rt}::CallError> {{\n        {encode}\n        {call}\n        Ok(PreparedResponse {{\n            row_count: result.row_count,\n            {rows}\n        }})\n    }}\n\n",
        ));
    }
    if out.ends_with("\n\n") {
        out.pop();
    }
    out.push_str("}\n");
    out
}

/// Render the parameter conversion and encoding statements, wrapping the encode closure like
/// rustfmt when the one-line form exceeds the default width.
///
/// `into_gql_params` returns a [`Result`], so the generated operation propagates parameter
/// conversion errors with `?` before encoding.
fn encode_statement(rt: &str) -> String {
    let one_line = format!(
        "let params = {rt}::encode_gql_params(params).map_err(|error| {rt}::CallError::Decode {{ message: format!(\"failed to encode GQL params: {{error:?}}\") }})?;"
    );
    let encode = if super::format::exceeds_width(&one_line, super::format::MAX_WIDTH - 8) {
        format!(
            "let params = {rt}::encode_gql_params(params).map_err(|error| {{\n            {rt}::CallError::Decode {{\n                message: format!(\"failed to encode GQL params: {{error:?}}\"),\n            }}\n        }})?;"
        )
    } else {
        one_line
    };
    format!("let params = params.into_gql_params()?;\n        {encode}")
}

/// Render the Router call, wrapping the method chain like rustfmt when the chain or the
/// full statement exceeds its width threshold.
fn call_statement(method: &str, call_args: &str) -> String {
    let one_line = format!("let result = self.{method}({call_args}).await?;");
    let chain = format!("self.{method}({call_args}).await");
    let fits = !super::format::exceeds_width(&chain, super::format::CHAIN_WIDTH)
        && !super::format::exceeds_width(&one_line, super::format::MAX_WIDTH - 8);
    if fits {
        one_line
    } else {
        format!("let result = self\n            .{method}({call_args})\n            .await?;")
    }
}

/// Render the `rows` field, wrapping the decoding chain like rustfmt when the chain or the
/// full field exceeds its width threshold.
fn rows_field(row: &str) -> String {
    let one_line = format!("rows: result.decode_serde_rows::<{row}>()?.unwrap_or_default(),");
    let chain = format!("result.decode_serde_rows::<{row}>()?.unwrap_or_default()");
    let fits = !super::format::exceeds_width(&chain, super::format::CHAIN_WIDTH)
        && !super::format::exceeds_width(&one_line, super::format::MAX_WIDTH - 12);
    if fits {
        one_line
    } else {
        format!(
            "rows: result\n                .decode_serde_rows::<{row}>()?\n                .unwrap_or_default(),"
        )
    }
}

fn parameter_value_expression(access: &str, parameter: &crate::Parameter, rt: &str) -> String {
    if parameter.required && !parameter.nullable {
        return gql_value_expression(access, &parameter.semantic_type, rt)
            .expect("parameter conversion was checked before rendering");
    }

    let value = gql_value_expression("value", &parameter.semantic_type, rt)
        .expect("parameter conversion was checked before rendering");
    format!("match {access} {{ Some(value) => {value}, None => GqlValue::Null }}")
}

fn gql_value_expression(access: &str, semantic_type: &SemanticType, rt: &str) -> Option<String> {
    let value = match semantic_type {
        SemanticType::Null => "GqlValue::Null".to_string(),
        SemanticType::Bool => format!("GqlValue::Bool({access})"),
        SemanticType::Int8 => format!("GqlValue::Int8({access})"),
        SemanticType::Int16 => format!("GqlValue::Int16({access})"),
        SemanticType::Int32 => format!("GqlValue::Int32({access})"),
        SemanticType::Int64 => format!("GqlValue::Int64({access})"),
        SemanticType::Uint8 => format!("GqlValue::Uint8({access})"),
        SemanticType::Uint16 => format!("GqlValue::Uint16({access})"),
        SemanticType::Uint32 => format!("GqlValue::Uint32({access})"),
        SemanticType::Uint64 => format!("GqlValue::Uint64({access})"),
        SemanticType::Int128 => format!("GqlValue::Int128({access})"),
        SemanticType::Uint128 => format!("GqlValue::Uint128({access})"),
        SemanticType::Int256 => format!("GqlValue::from({access})"),
        SemanticType::Uint256 => format!("GqlValue::from({access})"),
        SemanticType::Float16 => format!("GqlValue::from({access})"),
        SemanticType::Float32 => format!("GqlValue::Float32({access})"),
        SemanticType::Float64 => format!("GqlValue::Float64({access})"),
        SemanticType::Float128 => format!("GqlValue::Float128({access})"),
        SemanticType::Float256 => format!("GqlValue::Float256({access})"),
        SemanticType::Decimal => format!("GqlValue::from({access})"),
        SemanticType::Text => format!("GqlValue::Text({access})"),
        SemanticType::Bytes => format!("GqlValue::Bytes({access})"),
        SemanticType::Principal => {
            format!("GqlValue::Extension(Box::new({rt}::PrincipalValue({access})))")
        }
        SemanticType::Date => format!("GqlValue::from({access})"),
        SemanticType::Time => format!("GqlValue::from({access})"),
        SemanticType::LocalTime => format!("GqlValue::from({access})"),
        SemanticType::DateTime | SemanticType::LocalDateTime => {
            format!("GqlValue::from({access})")
        }
        SemanticType::ZonedDateTime => format!("GqlValue::from({access})"),
        SemanticType::ZonedTime => format!("GqlValue::from({access})"),
        SemanticType::Duration => format!("GqlValue::from({access})"),
        SemanticType::Record { .. } => format!("GqlValue::Record({access})"),
        SemanticType::Path => format!(
            "GqlValue::Path({access}.into_iter().map({rt}::PathElement::into_gql).collect())"
        ),
        SemanticType::List { element } => {
            let element = gql_value_expression("value", element, rt)?;
            format!("GqlValue::List({access}.into_iter().map(|value| {element}).collect())")
        }
    };
    Some(value)
}

/// Row field Rust type, binding exotic scalars through the SDK row-binding wrappers.
fn row_rust_type(semantic_type: &SemanticType, rt: &str) -> String {
    match semantic_type {
        SemanticType::Int256 => format!("{rt}::GqlInt256"),
        SemanticType::Uint256 => format!("{rt}::GqlUint256"),
        SemanticType::Decimal => format!("{rt}::GqlDecimal"),
        SemanticType::Principal => format!("{rt}::candid::Principal"),
        SemanticType::Float16 => format!("{rt}::GqlFloat16"),
        SemanticType::Float128 => format!("{rt}::Float128"),
        SemanticType::Float256 => format!("{rt}::Float256"),
        SemanticType::Date => format!("{rt}::GqlDate"),
        SemanticType::Time => format!("{rt}::GqlTime"),
        SemanticType::LocalTime => format!("{rt}::GqlLocalTime"),
        SemanticType::DateTime => format!("{rt}::GqlDateTime"),
        SemanticType::LocalDateTime => format!("{rt}::GqlLocalDateTime"),
        SemanticType::ZonedDateTime => format!("{rt}::GqlZonedDateTime"),
        SemanticType::ZonedTime => format!("{rt}::GqlZonedTime"),
        SemanticType::Duration => format!("{rt}::GqlDuration"),
        SemanticType::Path => format!("Vec<{rt}::PathElement>"),
        SemanticType::Record { .. } => {
            format!("std::collections::BTreeMap<String, {rt}::serde_json::Value>")
        }
        SemanticType::List { element } => format!("Vec<{}>", row_rust_type(element, rt)),
        _ => super::client::rust_type(semantic_type),
    }
}

/// Parameter field Rust type, which differs from row types for Float128 and records.
fn param_rust_type(semantic_type: &SemanticType, rt: &str) -> String {
    match semantic_type {
        SemanticType::Float128 => "f128".to_string(),
        SemanticType::Float256 => format!("{rt}::GqlFloat256"),
        SemanticType::Record { .. } => format!("{rt}::GqlRecord"),
        SemanticType::List { element } => format!("Vec<{}>", param_rust_type(element, rt)),
        _ => row_rust_type(semantic_type, rt),
    }
}
