// Generated by gleaph-codegen. Do not edit.

import type { ApiValue, GleaphClient, GleaphTransport, GleaphTransportOptions, GqlMutationResult, GqlQueryResult, PreparedSortSpec, ApiPathElement, GqlDecimal, GqlFloat16, GqlFloat128, GqlFloat256, GqlZonedTime, Temporal } from "@gleaph/sdk";
import { GleaphClientWrapper, createGleaphClient, createGleaphClientFromTransport, toApiValue, fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph" as const;

type PreparedResponse<Row> = Omit<GqlQueryResult, "rows"> & { rows: Row[] };

export type PrincipalLike = string | { toText(): string };

/**
 * Find related records from a graph path.
 */
export interface FindRelatedParams {
  /**
   * Path to start the traversal from.
   */
  route: ApiPathElement[];
}

export interface FindRelatedRow {
  display_name: string;
  next_route: ApiPathElement[] | null;
}

/**
 * Report a metrics snapshot with exotic scalar types.
 */
export interface ReportMetricsParams {
  balance: bigint;
  quota: bigint;
  amount: GqlDecimal;
  score?: GqlFloat16 | null;
  wider?: GqlFloat128 | null;
  widest?: GqlFloat256 | null;
  day: Temporal.PlainDate;
  at: Temporal.Instant;
  local_at: Temporal.PlainDateTime;
  zoned_at: Temporal.ZonedDateTime;
  local_time: Temporal.PlainTime;
  offset_time: GqlZonedTime;
  elapsed: Temporal.Duration;
  owner: PrincipalLike;
  blob: Uint8Array;
  counters: Array<bigint>;
  meta: { kind: string; rank: bigint | null };
}

export interface ReportMetricsRow {
  balance: bigint;
  amount: GqlDecimal;
  score: GqlFloat16 | null;
  wider: GqlFloat128 | null;
  day: Temporal.PlainDate;
  zoned_at: Temporal.ZonedDateTime;
  elapsed: Temporal.Duration;
  counters: Array<bigint>;
}

/**
 * Store a metrics snapshot.
 */
export interface RecordMetricsParams {
  amount: GqlDecimal;
  at: Temporal.Instant;
}

export interface RecordMetricsRow {
  stored: boolean;
}

export interface PreparedQueries {
  findRelated(params: FindRelatedParams, sort?: PreparedSortSpec[]): Promise<PreparedResponse<FindRelatedRow>>;
  reportMetrics(params: ReportMetricsParams): Promise<PreparedResponse<ReportMetricsRow>>;
  recordMetrics(params: RecordMetricsParams, clientMutationKey: string): Promise<GqlMutationResult>;
}

export class PreparedGleaphClient extends GleaphClientWrapper implements PreparedQueries {
  constructor(client: GleaphClient) {
    super(client);
  }

  /**
   * Find related records from a graph path.
   */
  async findRelated(params: FindRelatedParams, sort?: PreparedSortSpec[]): Promise<PreparedResponse<FindRelatedRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["route"] = toApiValue(params["route"], "Path");
    const response = await this.preparedQuery("find-related", encodedParams, sort);
    return { ...response, rows: response.rows.map((row) => ({
      display_name: fromApiValue(row["display_name"]) as string,
      next_route: fromApiValue(row["next_route"]) as ApiPathElement[] | null,
    })) };
  }

  /**
   * Report a metrics snapshot with exotic scalar types.
   */
  async reportMetrics(params: ReportMetricsParams): Promise<PreparedResponse<ReportMetricsRow>> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["balance"] = toApiValue(params["balance"], "Int256");
    encodedParams["quota"] = toApiValue(params["quota"], "Uint256");
    encodedParams["amount"] = toApiValue(params["amount"], "Decimal");
    if (params["score"] !== undefined) encodedParams["score"] = toApiValue(params["score"], "Float16");
    if (params["wider"] !== undefined) encodedParams["wider"] = toApiValue(params["wider"], "Float128");
    if (params["widest"] !== undefined) encodedParams["widest"] = toApiValue(params["widest"], "Float256");
    encodedParams["day"] = toApiValue(params["day"], "Date");
    encodedParams["at"] = toApiValue(params["at"], "DateTime");
    encodedParams["local_at"] = toApiValue(params["local_at"], "LocalDateTime");
    encodedParams["zoned_at"] = toApiValue(params["zoned_at"], "ZonedDateTime");
    encodedParams["local_time"] = toApiValue(params["local_time"], "LocalTime");
    encodedParams["offset_time"] = toApiValue(params["offset_time"], "ZonedTime");
    encodedParams["elapsed"] = toApiValue(params["elapsed"], "Duration");
    encodedParams["owner"] = toApiValue(params["owner"], "Principal");
    encodedParams["blob"] = toApiValue(params["blob"], "Bytes");
    encodedParams["counters"] = { List: params["counters"].map((value) => toApiValue(value, "Uint256")) };
    encodedParams["meta"] = { Record: Object.fromEntries([["kind", toApiValue(params["meta"]["kind"], "Text")], ["rank", toApiValue(params["meta"]["rank"], "Int64")]]) };
    const response = await this.preparedQuery("report-metrics", encodedParams);
    return { ...response, rows: response.rows.map((row) => ({
      balance: fromApiValue(row["balance"]) as bigint,
      amount: fromApiValue(row["amount"]) as GqlDecimal,
      score: fromApiValue(row["score"]) as GqlFloat16 | null,
      wider: fromApiValue(row["wider"]) as GqlFloat128 | null,
      day: fromApiValue(row["day"]) as Temporal.PlainDate,
      zoned_at: fromApiValue(row["zoned_at"]) as Temporal.ZonedDateTime,
      elapsed: fromApiValue(row["elapsed"]) as Temporal.Duration,
      counters: fromApiValue(row["counters"]) as Array<bigint>,
    })) };
  }

  /**
   * Store a metrics snapshot.
   */
  async recordMetrics(params: RecordMetricsParams, clientMutationKey: string): Promise<GqlMutationResult> {
    const encodedParams: Record<string, ApiValue> = {};
    encodedParams["amount"] = toApiValue(params["amount"], "Decimal");
    encodedParams["at"] = toApiValue(params["at"], "DateTime");
    const response = await this.preparedMutate("record-metrics", encodedParams, clientMutationKey);
    return response;
  }
}

export function withPreparedQueries(client: GleaphClient): PreparedGleaphClient {
  return new PreparedGleaphClient(client);
}

/** Construct a client bound to the graph's prepared operations and dynamic GQL. */
export async function createPreparedGleaphClient(options: GleaphTransportOptions): Promise<PreparedGleaphClient> {
  return withPreparedQueries(await createGleaphClient(options));
}

/** Construct a prepared client over an existing SDK transport. */
export function createPreparedGleaphClientFromTransport(transport: GleaphTransport): PreparedGleaphClient {
  return withPreparedQueries(createGleaphClientFromTransport(transport));
}
