// Generated by gleaph-codegen. Do not edit.

import { GleaphClientWrapper, createGleaphClient, createGleaphClientFromTransport, toApiValue, fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph";

export class PreparedGleaphClient extends GleaphClientWrapper {
  constructor(client) {
    super(client);
  }

  /**
   * Find related records from a graph path.
   */
  async findRelated(params, sort) {
    const encodedParams = {};
    encodedParams["route"] = toApiValue(params["route"], "Path");
    const response = await this.executePrepared("find-related", encodedParams, sort);
    return { ...response, rows: response.rows.map((row) => ({
      display_name: fromApiValue(row["display_name"]),
      next_route: fromApiValue(row["next_route"]),
    })) };
  }

  /**
   * Report a metrics snapshot with exotic scalar types.
   */
  async reportMetrics(params) {
    const encodedParams = {};
    encodedParams["balance"] = toApiValue(params["balance"], "Int256");
    encodedParams["quota"] = toApiValue(params["quota"], "Uint256");
    encodedParams["amount"] = toApiValue(params["amount"], "Decimal");
    if (params["score"] !== undefined) encodedParams["score"] = toApiValue(params["score"], "Float16");
    if (params["wider"] !== undefined) encodedParams["wider"] = toApiValue(params["wider"], "Float128");
    if (params["widest"] !== undefined) encodedParams["widest"] = toApiValue(params["widest"], "Float256");
    encodedParams["day"] = toApiValue(params["day"], "Date");
    encodedParams["at"] = toApiValue(params["at"], "DateTime");
    encodedParams["local_at"] = toApiValue(params["local_at"], "LocalDateTime");
    encodedParams["zoned_at"] = toApiValue(params["zoned_at"], "ZonedDateTime");
    encodedParams["local_time"] = toApiValue(params["local_time"], "LocalTime");
    encodedParams["offset_time"] = toApiValue(params["offset_time"], "ZonedTime");
    encodedParams["elapsed"] = toApiValue(params["elapsed"], "Duration");
    encodedParams["owner"] = toApiValue(params["owner"], "Principal");
    encodedParams["blob"] = toApiValue(params["blob"], "Bytes");
    encodedParams["counters"] = { List: params["counters"].map((value) => toApiValue(value, "Uint256")) };
    encodedParams["meta"] = { Record: Object.fromEntries([["kind", toApiValue(params["meta"]["kind"], "Text")], ["rank", toApiValue(params["meta"]["rank"], "Int64")]]) };
    const response = await this.executePrepared("report-metrics", encodedParams);
    return { ...response, rows: response.rows.map((row) => ({
      balance: fromApiValue(row["balance"]),
      amount: fromApiValue(row["amount"]),
      score: fromApiValue(row["score"]),
      wider: fromApiValue(row["wider"]),
      day: fromApiValue(row["day"]),
      zoned_at: fromApiValue(row["zoned_at"]),
      elapsed: fromApiValue(row["elapsed"]),
      counters: fromApiValue(row["counters"]),
    })) };
  }

  /**
   * Store a metrics snapshot.
   */
  async recordMetrics(params, clientMutationKey) {
    const encodedParams = {};
    encodedParams["amount"] = toApiValue(params["amount"], "Decimal");
    encodedParams["at"] = toApiValue(params["at"], "DateTime");
    const response = await this.executePreparedMutation("record-metrics", encodedParams, clientMutationKey);
    return response;
  }
}

export function withPreparedQueries(client) {
  return new PreparedGleaphClient(client);
}

/** Construct a client bound to the graph's prepared operations and dynamic GQL. */
export async function createPreparedGleaphClient(options) {
  return withPreparedQueries(await createGleaphClient(options));
}

/** Construct a prepared client over an existing SDK transport. */
export function createPreparedGleaphClientFromTransport(transport) {
  return withPreparedQueries(createGleaphClientFromTransport(transport));
}
