// Generated by gleaph-codegen. Do not edit.

import { fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph";

export function withPreparedQueries(client) {
  return {
    /**
     * Find related records from a graph path.
     */
    "find-related": async (params, sort) => {
      const encodedParams = {};
      encodedParams["route"] = { Path: params["route"] };
      const response = await client.executePrepared("find-related", encodedParams, sort);
      return { ...response, rows: response.rows.map((row) => ({
        display_name: fromApiValue(row["display_name"]),
        next_route: fromApiValue(row["next_route"]),
      })) };
    },
  };
}
