// Generated by gleaph-codegen. Do not edit.

import type { ApiValue, GqlQueryResult, GraphClient, PreparedSortSpec } from "@gleaph/sdk";
import type { ApiPathElement } from "@gleaph/sdk";
import { fromApiValue } from "@gleaph/sdk";

export const GLEAPH_GRAPH_ID = "fixture-graph" as const;

type PreparedResponse<Row> = Omit<GqlQueryResult, "rows"> & { rows: Row[] };

export type PrincipalLike = string | { toText(): string };

/**
 * Find related records from a graph path.
 */
export interface FindRelatedParams {
  /**
   * Path to start the traversal from.
   */
  route: ApiPathElement[];
}

export interface FindRelatedRow {
  display_name: string;
  next_route: ApiPathElement[] | null;
}

export interface PreparedQueries {
  /**
   * Find related records from a graph path.
   */
  "find-related": (params: FindRelatedParams, sort?: PreparedSortSpec[]) => Promise<PreparedResponse<FindRelatedRow>>;
}

export function withPreparedQueries(client: GraphClient): PreparedQueries {
  return {
    "find-related": async (params, sort?: PreparedSortSpec[]) => {
      const encodedParams: Record<string, ApiValue> = {};
      encodedParams["route"] = { Path: params["route"] };
      const response = await client.executePrepared("find-related", encodedParams, sort);
      return { ...response, rows: response.rows.map((row) => ({
        display_name: fromApiValue(row["display_name"]) as string,
        next_route: fromApiValue(row["next_route"]) as ApiPathElement[] | null,
      })) };
    },
  };
}
